### ISSUE TITLE
Optionals are strangely rendered

### ISSUE THREAD

**Issue by octatone** [tgreyuk/typedoc-plugin-markdown#10]
Hello there, thank you for this plugin. I have run into an issue where optionals of an object type render strangely (missing space between `Optional` and the object property.  As an example:

Input:

```ts
export type SomeOptions = {
  aFunction?: () => void
}
```

Output:
```md
## Type aliases
<a id="someoptions"></a>

###  SomeOptions

**Τ SomeOptions**:  *object* 



#### Type declaration

OptionalaFunction?: `undefined`⎮function

```

Command run:
`typedoc ./src/Class.ts --mdHideSources --out ./docs --options ./config/typedoc.js`

Config:
```js
module.exports = {
  mode: 'modules',
  externalPattern: '**/node_modules/*',
  excludeExternals: true,
  excludePrivate: true,
  readme: 'none',
  theme: 'markdown'
}
```

**Comment by tgreyuk** [comment]
Thanks for the feedback and for the detailed description.

I have published a new version (v1.0.9) that should fix this issue. 

Please do raise any further issues - feedback welcome.

Thanks.

**Comment by octatone** [comment]
Thanks for the quick update! It's already looking much better.

Now I am going to feel like I am nit-picking a little bit, but the output seems to be very redundant:

Output:
```
«Optional» aFunction?: undefined⎮function
```

To me, this is saying the same thing three times.  `<<Optional>>` and `?` and `undefined|function` all mean the same thing.

Not sure how the other themes look here, but to me I would expect something a little simplified:
```
«Optional» aFunction: function
```

What do you think?

**Comment by tgreyuk** [comment]
I don't think you are nit-picking and I agree that there is no point with the ? symbol and have removed in v1.0.10.
 
The Typescript compiler emits 'undefined' as a type when --strictNullChecks compiler option is set to true,. Barring setting --strictNullChecks to false I think this is something that we will probably have to live with as this is not something that can be filtered in a clean fashion.

Hope this makes sense.
