### ISSUE TITLE
Docsify Theme?

### ISSUE THREAD

**Issue by wovalle** [tgreyuk/typedoc-plugin-markdown#100]
Hello!

Nice work wit this plugin! I'm currently working in a documentation site built with [docsify](https://docsify.js.org/) and [created a typedoc theme](https://github.com/wovalle/fireorm/blob/master/docgen/typedoc-docsify/theme.js) to support it (I took the gitbook theme as base and did the required modifications to work with docsify).

Are you interested in a pull request adding this to the main library?

Thanks!

**Comment by tgreyuk** [comment]
Hi,

Sure... However I was actually planning on separating the sub-themes out of the main library so this has given me the impetuous to do it now. I will let you know.

Thanks

**Comment by wovalle** [comment]
Since they won't be part of typedoc, should I publish it individually? Will it have a special API to get the themes or just like typedoc documentation (a folder with a `theme.js` file)?

**Comment by tgreyuk** [comment]
If you are happy to publish individually as an npm module then i think that is better way to go. 

So yes all it needs is a folder with theme.js.

So it would be installed along with the plugin and run from its path (in the same way as other html themes such as https://github.com/google/typedoc-neo-theme and https://www.npmjs.com/package/typedoc-neo-theme).

So to run it would be something like:

install:
```
npm install typedoc typedoc-plugin-markdown typedoc-docsify-theme --save-dev
```
run:
```
typedoc --theme ./node_modules/typedoc-docsify-theme/dist
```

**Comment by wovalle** [comment]
Nice, thanks! I will create an npm module then.

**Comment by b4nst** [comment]
Hey @wovalle, could you post an update here when you publish your theme, I'm really interested. In the meantime is it ok for you if I use your [file](https://github.com/wovalle/fireorm/blob/master/docgen/typedoc-docsify/theme.js) ?

**Comment by wovalle** [comment]
I will sit down today or tomorrow to clean it up and publish it as an NPM module. You can use my file as well b4nst.

**Comment by badihi** [comment]
@wovalle 
Are you still seating down?!
