### ISSUE TITLE
Manual Control Over Sidebar

### ISSUE THREAD

**Issue by tusharmath** [tgreyuk/typedoc-plugin-markdown#107]
I would like to have manual control over the sidebar. Right now typedoc outputs a bit too many items which I don't want to publish on my documentation site.

I want to be able to control if this plugin should update the sidebar.json or not.

**Comment by tusharmath** [comment]
PR created here — https://github.com/tom-grey/typedoc-plugin-markdown/pull/108

**Comment by edchapel** [comment]
#124 is a PR to extend the arg to docusaurus2 as well.
