### ISSUE TITLE
No reflection on object literals

### ISSUE THREAD

**Issue by liamross** [tgreyuk/typedoc-plugin-markdown#114]
I'm having an issue with object types collapsing into "object" rather than expanding in the documentation:

```ts
export type TOptions = string | {number?: number; [target: string]: any};
```

Generated:

```ts
TOptions
Ƭ TOptions: string | object
```

Config:

```sh
"typedoc": "typedoc --out packages/site/docs/api packages/core/src/index.ts --mode library --readme none --excludePrivate --plugin typedoc-plugin-markdown --theme docusaurus2",
```

See comment here:

https://github.com/TypeStrong/typedoc/issues/901#issuecomment-578377443

According to a contributor:

> I can't reproduce with the default theme - this seems to be a bug with typedoc-plugin-markdown.

**Comment by tgreyuk** [comment]
Fixed in 3.0.0. apologies for slow response.
