### ISSUE TITLE
Github wiki firendly ?

### ISSUE THREAD

**Issue by GuichaouaT** [tgreyuk/typedoc-plugin-markdown#118]
Is there any way to make the docs Github wiki friendly ?
I tried to upload the generated docs to my repo wiki, but it's seems that github wiki cannot manage subfolders.

Is there any option or script I can run to convert the generated docs ?

I read this #47 but I'm not sure to undertand how to solve the problem.

**Comment by AZMCode** [comment]
They basically didn't solve it, which is kinda sad

**Comment by AZMCode** [comment]
They're using a custom post-processing script but I'm finding it difficult to make it work

**Comment by tgreyuk** [comment]
If this is still of interest I have created a theme that exports to a compatible file structure and also creates a Sidebar.md file.

https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-github-wiki-theme

**Comment by AZMCode** [comment]
Absolutely it is, I'll try it out sometime!
