### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by jayarjo** [tgreyuk/typedoc-plugin-markdown#125]
I get `Error: Cannot find module 'typescript'` error.

**Comment by tom-grey** [comment]
@jayarjo looks like node can't install typescript module - have you installed it locally?

**Comment by jayarjo** [comment]
@tgreyuk it is installed both in the project (which is actually written in typescript) and globally. Also I noticed that while error manifests itself after I install `typedoc-plugin-markdown` (so until that moment `typedoc works just fine`), it is actually thrown by `typedoc`.

**Comment by jayarjo** [comment]
All of a sudden it started to work. So please ignore.
