### ISSUE TITLE
Support for --mode library

### ISSUE THREAD

**Issue by jayarjo** [tgreyuk/typedoc-plugin-markdown#129]
`typedoc` prepares to release version with support of what they call library mode: https://github.com/TypeStrong/typedoc/pull/1184. Also there are some breaking changes, so that `typedoc-plugin-markdown` doesn't work with it out of the box.

**Comment by jamesandersen** [comment]
A quick update. The `--mode library` feature has evolved a bit as discussed on https://github.com/TypeStrong/typedoc/issues/1364 but it is expected to be part of the `0.20` release currently in beta. 

I'm hoping I'll be able to use that in combination with `typedoc-plugin-markdown` when it becomes available.

**Comment by tgreyuk** [comment]
Thanks @jamesandersen . Yes there are quite a few breaking changes - I do have a branch that is 0.20 compatible but I haven't published to npm yet. I will have a look at publishing it as a beta version.

**Comment by boenfu** [comment]
I like this plugin，but..

The command i used
`typedoc --plugin typedoc-plugin-markdown --out docs src`

The version i used
```
 "typedoc": "^0.20.0-beta.27",
 "typedoc-plugin-markdown": "^3.1.1",
 "typescript": "^4.1.3"
```
I get
```
TypeError: Right-hand side of 'instanceof' is not an object
    at TemplateLiteralType.type (C:\Boen\node_modules\typedoc-plugin-markdown\dist\resources\helpers\type.js:27:14)
```
0.0 What should i do

**Comment by tgreyuk** [comment]
@boenfu sorry the version is not compatible with 0.20 - i am working on it.

**Comment by binjospookie** [comment]
@tgreyuk how can I help you?

**Comment by Xunnamius** [comment]
Perhaps strangely, I'm using typedoc-plugin-markdown@3.1.1 with the latest beta (which has now been released as [typedoc@0.20.1]()) and it [seems like it's working in my CI pipeline](https://github.com/Xunnamius/workflow-playground/blob/main/docs/README.md).

```
"typedoc": "0.20.1",
"typedoc-plugin-markdown": "3.1.1",
```
And I run `typedoc --plugin typedoc-plugin-markdown --out docs --readme none src/index.ts`

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@3.2.0 should now be compatible. @binjospookie thanks if you could try it out and log and issues that would be useful.

**Comment by binjospookie** [comment]
Looks like it works perfectly. It's generate `readme.md` and `modules.md` files for me. `modules.md` content looks well.

**Comment by tgreyuk** [comment]
thanks @binjospookie ..

**Comment by binjospookie** [comment]
thanks for your job!
