### ISSUE TITLE
Arrays of union type rendered without parentheses

### ISSUE THREAD

**Issue by derkallevombau** [tgreyuk/typedoc-plugin-markdown#130]
### HTML from typedoc (correct)
callFn(name: string, functionName: string, passDevHash?: boolean, functionReturnsHash?: boolean, ...args: **(string | number)[]**): Promise<string | number | void | **(string | number)[]** | Map<string | number, string | number>>
### Markdown from plugin (wrong)
▸ callFn(name: string, functionName: string, passDevHash?: boolean, functionReturnsHash?: boolean, ...args: **string | number[]**): Promise‹string | number | void | **string | number[]** | Map‹string | number, string | number››

**Comment by tgreyuk** [comment]
Fixed in 2.4.0
