### ISSUE TITLE
No comments for types inside interfaces

### ISSUE THREAD

**Issue by zemlanin** [tgreyuk/typedoc-plugin-markdown#131]
Plugin loses comments for object fields inside interfaces

In other words, docs for interfaces like this one:

```ts
export interface Demo {
  /**
   * Hello world
   */
  hello: {
    /**
     * Lorem ipsum
     */
    lorem: string
  }
}
```

won't include `Lorem ipsum` comment

Demo repo: https://github.com/zemlanin/typedoc-plugin-markdown-loses-comments

**Comment by tgreyuk** [comment]
Fixed in 3.0.0. apologies for slow response.
