### ISSUE TITLE
How to change page title?

### ISSUE THREAD

**Issue by shubhamzanwar** [tgreyuk/typedoc-plugin-markdown#134]
I am trying to document an interface called `CustomButtonProps`. However, I would like the document title to be `Custom Button`. Is these anyway I can achieve this?

**Comment by felipecrs** [comment]
It would be also useful if we could customize the README title.

**Comment by shubhamzanwar** [comment]
Exactly!

**Comment by tgreyuk** [comment]
@felipecrs do you mean customise the front-matter title? The visible inline title will be whatever is in the README file.

@shubhamzanwar i suppose the cleanest way to do this would be with an annotation but I am not sure much of a common use case this is..

**Comment by felipecrs** [comment]
> @felipecrs do you mean customise the front-matter title? The visible inline title will be whatever is in the README file.

Yes, this title is displayed in the page name (in your Chrome's tab) rather than the title set in the README.md itself.

Also, the `sidebar_label` infers from it, despite you intentionally set it to _README_ anyway.

**Comment by tgreyuk** [comment]
Would something like `readmeTitle` make sense as an option?  I am not sure how else it could be inferred?

**Comment by felipecrs** [comment]
For me it does, but as I said [here](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/143#issuecomment-697526076), I'm not entirely sure.

**Comment by shubhamzanwar** [comment]
@tgreyuk but we'd need to change this for different pages. I have a project that documents 5 components and want a different title for each of the readmes generated for the 5 components. Would that be possible?

**Comment by tgreyuk** [comment]
@shubhamzanwar so each component gets compiled on a separate typedoc instance hence multiple readme? Also just to confirm you are talking about the docusaurus document/browser title (i am just checking you and @felipecrs are talking about the same thing) ? Since v3.0 no additional titles are added to the readme template itself.

**Comment by shubhamzanwar** [comment]
Yuppp, I'm talking about the docusaurus page title. (I'm not worried about the browser tab title).
I have multiple readmes because I have 1 class each in 5 .ts files. Hence when i run `typedoc`, 5 readmes are generated (one for each .ts file). The title of the readme is the name of the class. I want to change this title.

**Comment by tgreyuk** [comment]
I don't suppose you have this setup on a public repo? I think we are talking cross-purposes.

**Comment by shubhamzanwar** [comment]
Sure I do. Using it for documenting https://github.com/nodegui/vue-nodegui

Reference files: I am documenting ButtonProps interface in: https://github.com/nodegui/vue-nodegui/blob/master/src/widgets/Button/VNButton.ts

The result is: https://github.com/nodegui/vue-nodegui/blob/master/website/docs/api/interfaces/buttonprops.md

I want the title to be `VN-Button`

**Comment by felipecrs** [comment]
@shubhamzanwar when you say "readme", I believe you're in fact referring to the `.md` files generated for each class. The _README_ I mentioned was the actual _README.md_ (just to clear things out). :)

**Comment by felipecrs** [comment]
> I want the title to be `VN-Button`

I think this should be a request for TypeDoc itself, not for this plugin, since it appears that you can't change the title even using the plain `typedoc`. 

Did you search their docs to check if there is not anything to help?

I looked at [Docs comments section](https://typedoc.org/guides/doccomments/) and I could not find anything useful.

**Comment by tgreyuk** [comment]
Yeah the themes just derive the page title from the kind/name of the reflection. There is no concept of a display title in the models. 

@felipecrs it might be worth raising a separate ticket for the specific README issue?

**Comment by felipecrs** [comment]
Yes, just did it. :)

You might also want to rename this one to something more specific.

**Comment by shubhamzanwar** [comment]
Oh man! I can't believe I was stupid enough to call the `.md` files as README files. Apologies for that! 😅
I'll take this issue to typedoc. Thanks for your help! 🙂

**Comment by tgreyuk** [comment]
@shubhamzanwar if you don't mind I am going to close this issue as I don't think there will be any actions from it. In theory you could customise the theme with a custom header and map the titles to whatever you want although that seems like quite a brittle solution.
