### ISSUE TITLE
Any way to add a path prefix?

### ISSUE THREAD

**Issue by nsainaney** [tgreyuk/typedoc-plugin-markdown#135]
I need to embed the generated docs into a larger document repository. The generated documents are like so: (excerpt from README.md)

```markdown
### Classes

* [Cluster](classes/cluster.md)
* [Config](classes/config.md)
* [Event](classes/event.md)
```

I would like the links to be absolute so need to add a prefix e.g. `/myrepo/lib/` so the output is:

```markdown
### Classes

* [Cluster](/myrepo/lib/classes/cluster.md)
* [Config](/myrepo/lib/classes/config.md)
* [Event](/myrepo/lib/classes/event.md)
```

Any suggestions on how to do this?

**Comment by tgreyuk** [comment]
@nsainaney I have added a `publicPath` option which should resolve your issue. (available in 2.4.0)

`--publicPath /myrepo/lib/`

Let me know if any issues.
