### ISSUE TITLE
The .vuepress config.js file not generated.

### ISSUE THREAD

**Issue by antonedvard** [tgreyuk/typedoc-plugin-markdown#138]
In this MD file [THEMES.md](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/master/THEMES.md) it is stated that when selecting vuepress it will generate a config.json file
```
Will create:

- .vuepress/api-sidebar.json to be used with sidebar.
- .vuepress/api-sidebar-relative.json to be used with multiple sidebars.
- .vuepress/config.json
```

I am only seeing the tool generating the 2 api-sidebar json files and not the config.json file. (Which i guess should be a JS file?)

Is this a normal behaviour or am i doing something wrong?

**Comment by tgreyuk** [comment]
@antonedvard apologies this looks like a documentation error. The config.js is not created but the examples describe what should be included in the config.js file. I have updated the docs accordingly. I hope this clears things up?

**Comment by antonedvard** [comment]
ah thanks for clearing that up... i guess it would be a good idea to make the config.js be created alongside? since if your running other compilers after the typedoc generated then you will manually have to come in to create the file etc... or am i complicating this process in my head?

**Comment by tgreyuk** [comment]
no i think you have a point - will take a look.

**Comment by antonedvard** [comment]
you could perhaps have a vuepressconfig.js in the root which would be used as a template, just adding on to the idea.

**Comment by tgreyuk** [comment]
Have completely changed the approach on this. See https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/vuepress-plugin-typedoc.
