### ISSUE TITLE
While rendering: "Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by SimonCockx** [tgreyuk/typedoc-plugin-markdown#140]
When I turn on this plugin, I get the following output:

    > npx typedoc src/app --options typedoc.json
    
    Loaded plugin typedoc-plugin-markdown
    
    Using TypeScript 3.9.5 from C:\Users\Werk\Desktop\beerhive\venuewebsite\node_modules\typescript\lib
    No 'out' or 'json' option has been set
    The './docs' directory has be set as the output location by default
    Rendering [==============--------------------------] 35%Cannot read property 'toString' of undefined

Without this plugin, TypeDoc works fine.

I'm using the following configuration:

    {
        "plugin": ["typedoc-plugin-markdown"],
        "exclude": "**/*.spec.ts",
        "out": "documentation/typedoc"
    }

I can't find a trace of the error, so it's hard to properly debug, although it must have something to do with this plugin. Suggestions?

**Comment by tgreyuk** [comment]
@SimonCockx thanks can you please re-install and try again (2.4.1). I can only see one place in the code that can be causing this.

**Comment by SimonCockx** [comment]
@tgreyuk Okay, updating to 2.4.1 fixed it!
