### ISSUE TITLE
docusaurus: add sidebarFile option

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#144]
Add a new option `sidebarFile` which defaults to `sidebars.js`, so users have the option to manage their own sidebar file separately and import the TypeDoc's sidebar from it. 

This also enables users to set a parent category for the TypeDoc's generated docs, such as:

```javascript
module.exports = {
  someSidebar: {
    Guides: ['autoheight', 'features'],
    API: require('typedoc-siderbar.js'),
  }
};
```

Thanks, @jsamr for this suggestion.

This also enables users to keep this file in their `.gitignore`, therefore minimizing the number of files in commits since this would be always generated by this plugin in build time anyway.

**Comment by tgreyuk** [comment]
@felipecrs Yes I agree this makes sense. I am just wondering what should happen if the api is rendered with `readme--none` as there will be no landing page without the globals. I guess in this situation we keep the globals file. I will have a look but let me know if you think there is a better approach.

**Comment by felipecrs** [comment]
@tgreyuk I believe that the overwhelming majority of users who use `--readme none` is because they're maintaining the entry point documentation on their own.

But I'm still not sure about what I would do.

**Comment by felipecrs** [comment]
There will be cases where:

1. Users use `--readme none` because they manage their own entry-point
2. Users use `--readme none` but still want the `global` files to be generated

We should at least provide options for all the use cases.

**Comment by tgreyuk** [comment]
No TypeDoc don't provide options around the globals page. I have been going round in circles on this one. Are we saying there are situations when neither the readme or globals would need to be included in the docs. the `readme` option also takes a path to another location..

**Comment by felipecrs** [comment]
> Are we saying there are situations when neither the readme or globals would need to be included in the docs.

Yes! Since docusaurus is not exclusively used for TypeDoc documentations, there are plenty of doc portals which might consider adding the TypeDoc's stuff on it (and for sure: they already have a entry-point).

In my case, for example, I want to deploy a doc portal where I have:

1. An entry-point other than the README, managed by myself in `docs/index.md` (there is no point to call `typedoc --readme docs/index.md` since it's already configured and I explicitly don't want TypeDoc to mess it around).
1. A CLI documentation, which I generate by myself using Markdown Magic in the `docs/usage` folder.
1. TypeDoc's documentation under `docs/api` folder.

**Comment by tgreyuk** [comment]
Sure makes total sense. Maybe having globals disabled by default makes sense I will have a play with some scenarios.

**Comment by jsamr** [comment]
Disabling globals might make sense:

- when readme is !== "none"
- (perhaps, see remark below) when the doc is compiled [in modules-mode](http://typedoc.org/guides/options/#mode)?

My use case is that I do have readme = none and I do have the "file" mode, because I use [api-extractor](https://api-extractor.com/) to bundle a single declaration file.

I don't know if it is related to file-mode, but my globals file has a bunch of important definitions such as type aliases and variables. I certainly don't want to lose. It **is not** only some kind of TOC for the whole api reference (see screenshot below).

![2020-09-19-050935_1654x638_scrot](https://user-images.githubusercontent.com/3646758/93662429-605b5e00-fa36-11ea-8049-198cfc68a917.png)

**Comment by tgreyuk** [comment]
@jsamr yes thats a good point - with `mode --file` reflections that do not have its own document are hoisted to the globals page.

**Comment by felipecrs** [comment]
So disabling globals may not be a good idea, that's why `typedoc` does not give you an option for that, I think.

Perhaps, just wrapping the items in the sidebar to an _**API**_ category, as of @jsamr's example, might solve the problem about the confusedness. That's actually my preferred layout as well since I have the CLI documentation that I don't want to overlap between the API.

How about generating the `sidebars.js` with a parent category called API by default? Something like:

```javascript
module.exports = {
  "typedoc": [
    "api/index",
    {
      "type": "category",
      "label": "API",
      "items": [
        "api/globals",
        {
          "type": "category",
          "label": "Modules",
          "items": [
            "api/modules/_commands_save_image_",
            "api/modules/_index_",
            "api/modules/_model_image_"
          ]
        },
        {
          "type": "category",
          "label": "Classes",
          "items": [
            "api/classes/_commands_save_image_.saveimage",
            "api/classes/_model_image_.image"
          ]
        }
      ]
    },
  ]
};
```
I'm not sure rather the README should be in this category as well or not.

**Comment by jsamr** [comment]
This is how I do:

```js
const { typedocSidebar } = require('./typedoc-sidebars');

module.exports = {
  someSidebar: {
    Guides: ['autoheight', 'features'],
    API: typedocSidebar,
  }
};
```
Then, I just needed to slightly patch the plugin to specify where I want the sidebar to be serialized by providing the `sidebarFile` option. This is the patch I applied to version 0.0.3:
```diff
diff --git a/dist/plugin/index.js b/dist/plugin/index.js
index 2e3531802ec6e30ff4310fbf4e127231b72b0b16..eefd55a2e246f9b2de91f446ab6c8c42a055351b 100644
--- a/dist/plugin/index.js
+++ b/dist/plugin/index.js
@@ -10,12 +10,14 @@ function pluginDocusaurus(context, options) {
     const outFolder = options.out !== undefined ? options.out : 'api';
     const out = docsRoot + (outFolder ? '/' + outFolder : '');
     const skipSidebar = options.skipSidebar || false;
+    const sidebarFile = options.sidebarFile || 'sidebars.js';
     options.hideBreadcrumbs = true;
     delete options.skipSidebar;
     delete options.inputFiles;
     delete options.out;
     delete options.id;
     delete options.docsRoot;
+    delete options.sidebarFile;
     return {
         name: 'docusaurus-plugin-typedoc',
         async loadContent() {
@@ -25,7 +27,7 @@ function pluginDocusaurus(context, options) {
                 const project = app.convert(app.expandInputFiles(inputFiles));
                 app.generateDocs(project, out);
                 if (app.renderer.theme.isOutputDirectory(out) && !skipSidebar) {
-                    const sidebarPath = path.resolve(siteDir, 'sidebars.js');
+                    const sidebarPath = path.resolve(siteDir, sidebarFile);
                     const theme = app.renderer.theme;
                     const navigation = theme.getNavigationV3(project);
                     const sidebarContent = getSidebarJson(navigation, outFolder);

```

@tgreyuk What do you think of generalizing this approach of serializing in a separate file / importing? I believe it is much more flexible.

**Comment by felipecrs** [comment]
This seems more to be a must-have if you ask me. Awesome!

**Comment by tgreyuk** [comment]
@jsamr this approach is much better - i will add it in. @felipecrs i have already added a parent category option but writing to a separate file probably makes this redundant.

These are the current sidebar options

```
// options for auto generated sidebars.json (pass `null` to skip generation completely)
        sidebar: {
          // display full names with module path if applicable - (defaults to 'false')
          fullNames: false,
          // the parent category label for sidebar - (defaults to `none` - no parent category)
          parentCategory: 'none',
        },
```

We could simply add an additional option `sidebarFile` which defaults to sidebar.js.

**Comment by felipecrs** [comment]
> We could simply add an additional option sidebarFile which defaults to sidebar.js.

I also think so. :D

**Comment by felipecrs** [comment]
@tgreyuk should I rename this Issue to "add sidebarFile option" or should we close this and open another one for that?

**Comment by tgreyuk** [comment]
@felipecrs yeah good suggestion - i've renamed it..

**Comment by felipecrs** [comment]
@tgreyuk I also rewrote the description. :)

**Comment by tgreyuk** [comment]
@felipecrs @jsamr if you have any time please review 0.2.0 which now has a sidebarFile option (which defaults to `typedoc-sidebar`. We now assume that the sidebar will be written to a completely separate file which is much better and lets the user do what they want with the sidebars (thanks @jsamr) . I have updated the README accordingly.

**Comment by felipecrs** [comment]
This is working really fine! I used it in PR https://github.com/felipecrs/megatar/pull/63 and it's deployed at https://felipesantos.dev/megatar.

**Comment by tgreyuk** [comment]
No worries...

**Comment by jsamr** [comment]
@tgreyuk I works great, thank you!
