### ISSUE TITLE
docusaurus: index title being duplicated from README

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#146]
If the README already contains a title (aka `# Title`), this plugin is regenerating the title for the `index.md`, causing something like:

`README.md`:
```Markdown
megatar
=======

Create full offline Helm chart packages.
```

`docs/api/index.md`:
```Markdown
---
id: "index"
title: "megatar"
sidebar_label: "README"
hide_title: "true"
---

# megatar

# megatar

Create full offline Helm chart packages.
```

**Comment by tgreyuk** [comment]
@felipecrs Fixed - the readme no longer has its own title.
