### ISSUE TITLE
docusaurus: hide_title property being generated as string rather than boolean

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#147]
How it is:

```Markdown
---
hide_title: "true"
---
```

How it is supposed to be (according to [their docs](https://v2.docusaurus.io/docs/markdown-features#markdown-headers)):

```Markdown
---
hide_title: true
---
```

It works on Docusaurus, though.

**Comment by tgreyuk** [comment]
@felipecrs Fixed in docusaurus-plugin-typedoc 0.1.0.

**Comment by felipecrs** [comment]
@tgreyuk thank you very much!
