### ISSUE TITLE
docusaurus: document and example repository structure with this plugin

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#150]
I'm kinda confused. Docusaurus v2 suggests having a repository structure like that:

```console
- src/ # TypeScript source folder
- website/ # Docusaurus root
  - docs/ # Folder where this plugin will generate files on
  - package.json # Docusaurus'
- package.json # Project's
```

So, where am I supposed to install this plugin? On the project root, or in Docusaurus root? 

- If it's the first case: how will Docusaurus be able to find the plugin?
- If it's the second case, I will then also need to install `typescript` in Docusaurus' root, thus opening the possibility of having a mismatch in their versions.

Or did I get something very wrong?

Refs https://github.com/facebook/docusaurus/issues/3463.

**Comment by felipecrs** [comment]
Ok, I noticed that this plugin uses the `typescript` installation from the project directory if it's not present in the website directory.

The problem with that is that TypeScript can also be present in the website directory, see: https://v2.docusaurus.io/docs/typescript-support.

So I think that this project should look for the `typescript` interpreter in the parent directory first, then, falling back to the website's typescript.

**Comment by jsamr** [comment]
@felipecrs I personally have a nice working setup with yarn 2 workspaces and nodeLinker. But conceptually yes, the "website" is a sub-project and the plugin dependency should be declared here.

**Comment by felipecrs** [comment]
@jsamr that makes sense. I believe the outcome of this issue is now just the TypeScript installation issue that I talked about in my last comment.

**Comment by felipecrs** [comment]
@jsamr if the project you're referring to is open source, could you share?

**Comment by jsamr** [comment]
@felipecrs Sure! But the current branch where this setup is implemented is very unstable and will be squashed a lot, be advised! https://github.com/formidable-webview/webshell/tree/dev/v2

**Comment by tgreyuk** [comment]
> So I think that this project should look for the typescript interpreter in the parent directory first, then, if not found, falls back to the website's typescript.

TypeDoc simply does a require.solve to get the typescript path:

```
 /**
     * Return the path to the TypeScript compiler.
     */
    public getTypeScriptPath(): string {
        return Path.dirname(require.resolve("typescript"));
    }
```

I am not sure it is a good idea trying to change this at plugin level (although possible by extending the Application class).

> If it's the first case: how will Docusaurus be able to find the plugin?

Plugins can be referenced by path - so the following would work:
```
 plugins: [
    [
      "../node_modules/docusaurus-plugin-typedoc",
      // plugin options
    ],
  ],
```

So that is a potential workaround if there issues with mis-match typescript versions. However i think it makes more sense to keep all docusaurus related dependencies in the website folder as a recommended approach.

**Comment by felipecrs** [comment]
> I am not sure it is a good idea trying to change this at plugin level (although possible by extending the Application class).

So I believe it worth an Issue in the TypeDoc to check what they have to tell about it. If this comes to be a Docusaurus specific need, then I believe it would make sense to be implemented here.

> So that is a potential workaround if there are issues with mis-match typescript versions. However i think it makes more sense to keep all docusaurus related dependencies in the website folder as a recommended approach.

Agreed.
