### ISSUE TITLE
Change README.md title on the generated headers

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#152]
It seems to default to `README`. In my case for example I would like to set it to `Introduction`.

This is the continuation of the conversation started in https://github.com/tgreyuk/typedoc-plugin-markdown/issues/134.

**Comment by tgreyuk** [comment]
Can I assume that your readme is marked as follows?

```
# Introduction

Some content
```

Because in theory the title can be inferred from the content (if matched) rather than supplying additional options.

**Comment by felipecrs** [comment]
Not really. :-( 

This is my original file: https://github.com/felipecrs/megatar/blob/master/README.md

And this is the headers that I wanted to include for it: 

https://github.com/felipecrs/megatar/blob/master/website/scripts/import-readme.sh#L10-L14

If Docusaurus implement https://github.com/facebook/docusaurus/issues/3475, we would not need to bother about this.

**Comment by tgreyuk** [comment]
sure let's just monitor this one for the moment.

**Comment by tgreyuk** [comment]
@felipecrs We now have a sidebar option `readmeLabel` which updates the sidebar label and the frontmatter title.

```
sidebar:{
  readmeLabel: 'Introduction'
}
```

If you are happy that I will close this issue.

**Comment by felipecrs** [comment]
Absolutely, this is working really well. 

However, I would like to note one thing:

I see that `sidebar_label` is being set.
![image](https://user-images.githubusercontent.com/29582865/95022790-b2fc6300-064f-11eb-9a01-66382e0ed36d.png)

But it's not needed. Docusaurus already uses `title` if `sidebar_label` is not set.

Because of that I believe the right option name would be

```javascript
sidebar: {
  readmeTitle: 'Introduction'
}
```

rather than `readmeLabel`.

**Comment by tgreyuk** [comment]
> But it's not needed. Docusaurus already uses title if sidebar_label is not set.

Good point 

> Because of that, I believe the right option name would be `readmeTitle: 'Introduction'`

Initially i thought this would be confusing because it doesn't effect the visual h1 title but yeah i don't mind. @jsamr what do you think? I think if this is updated we should probably go with `globalsTitle` for consistency?

**Comment by jsamr** [comment]
@tgreyuk Yes I had thought about that... The thing is, one *might* want to keep the title to "name of the package" whilst customizing the label, thus the `globalsLabel` **and** `globalsTitle` suggestion I made. But in the end, I don't mind. I think it's your call, at some point you might think your are overwhelming the API legibility with too much options, if these options are requested by 0.1% of the users... For consistency, I agree you should go with `globalsTitle` if you retain only 2 of the 4 options.

**Comment by felipecrs** [comment]
> The thing is, one might want to keep the title to "name of the package" whilst customizing the label, thus the globalsLabel and globalsTitle suggestion I made.

This is really valid, but there is no option to set `readmeTitle` to some value different than the label yet. If we had, then it would be right.

> at some point you might think your are overwhelming the API legibility with too much options

I think a good balance would be to implement only options that are only applicable to docusaurus. One good example is https://github.com/tgreyuk/typedoc-plugin-markdown/issues/134. The `readmeTitle` (what I'm requesting) can be a good example as well, since `typedoc` itself does not provide the option to customize it, so why this plugin should bother?

> if these options are requested by 0.1% of the users...

I 100% agree. If VSCode for example would implement every new feature request they receive, they would never introduce their own ideas.

**Comment by tgreyuk** [comment]
I think it's a good idea to have a `readmeTitle` and `globalsTitle`. For consistency though they should work in the same way as each other (ie the document and inline h1 title will derive from the front-matter `title`). This will mean removing from the h1 from the template and removing `hide_title:true` but thats fine. This will also mean that authors should not define an h1 in their `README.md` file or there will be duplicate titles.

Also these aren't really sidebar options but page level options so i would envisage the options hierarchy looking like:

```
sidebar:{
 readmeLabel: 'README',
 globalsLabel: 'Globals'
 ...
},
readmeTitle: '{Project name}'
globalsTitle: `{Project name}'
```

Let me know if the above seems logical....

**Comment by jsamr** [comment]
@tgreyuk LGTM!

**Comment by felipecrs** [comment]
LGTM as well, except for: 

> This will also mean that authors should not define an h1 in their README.md file or there will be duplicate titles.

I believe that README.md should be the exception of the rule, because:

1. It is not autogenerated (different than any other .md).
2. It is built with GitHub in mind, not docusaurus. Dropping the `h1` in the README.md would make it display incorrectly when rendered in GitHub.

Therefore, for README, I believe it should include `hide_title: true` even when the user sets a customized title with `readmeTitle`. This custom title would be used to display in the sidebar and in the tab name in the browser.

**Comment by tgreyuk** [comment]
> Therefore, for README, I believe it should include hide_title: true even when the user sets a customized title with readmeTitle. 

Ok yes that makes sense.

> This custom title would be used to display in the sidebar and in the tab name in the browser. 

With the above proposal we have both 'readmeLabel` and `readmeTitle` so actually the sidebar and tab name would have to be explicitly set to over-ride the default value?

**Comment by felipecrs** [comment]
> With the above proposal we have both `readmeLabel` and `readmeTitle` so actually the sidebar and tab name would have to be explicitly set to over-ride the default value?

No no, as long as you have:

```md
---
title: "Introduction"
---
``` 

Docusaurus will automatically infer the `sidebar_label` from the `title`.

**Comment by tgreyuk** [comment]
> Docusaurus will automatically infer the sidebar_label from the title.

Yeah i get that but this assumes that by setting the `readmeTitle` the user wants to update both the default `readmeTitle` AND the default `readmeLabel`.

**Comment by tgreyuk** [comment]
As discussed - `readmeTitle` and `globalsTitle` options added.

docusaurus-plugin-typedoc@0.4.0
