### ISSUE TITLE
Blank documentation for type parameters in classes and interfaces

### ISSUE THREAD

**Issue by jsamr** [tgreyuk/typedoc-plugin-markdown#153]
In source:

![2020-09-30-205503_684x338_scrot](https://user-images.githubusercontent.com/3646758/94751518-3de31200-035f-11eb-8fc6-a436bcf36f89.png)

In doc:

![2020-09-30-205552_793x279_scrot](https://user-images.githubusercontent.com/3646758/94751545-59e6b380-035f-11eb-9226-349a03bca3c0.png)

@tgreyuk If that is unexpected, I am willing to create a full reproduction :-) 

Libraries:

- docusaurus-plugin-typedoc@0.2.0
- typedoc-plugin-markdown@3.0.3

**Comment by tgreyuk** [comment]
@jsamr I have reproduced. I think this should probably be displayed in tabular format as elsewhere what do you think?

**Input:**
```
/**
 * Named parameters for xyz
 * @typeparam T - Some type param
 * @typeparam V - Some other type param
 */
export interface ReflectionWithTypeParams<T, V> {
  propT: T;
  propV: V;
}
```

**output:**
![type-params](https://user-images.githubusercontent.com/11680870/94787706-8edc2000-03ca-11eb-9fc1-d4a42ada7323.png)

**Comment by jsamr** [comment]
@tgreyuk Yes Tom, that would be perfect!

**Comment by tgreyuk** [comment]
Implemented in typedoc-plugin-markdown@3.0.4

**Comment by jsamr** [comment]
@tgreyuk Thank you so much for your prompt action! Works beautifully :+1:

**Comment by tgreyuk** [comment]
@jsamr no problem - if you notice anything else or think things could work better let me know..
