### ISSUE TITLE
Support custom Typedoc Theme class?

### ISSUE THREAD

**Issue by jsamr** [tgreyuk/typedoc-plugin-markdown#154]
I have patched the DefaultTheme class of typedoc (0.19.2) in order to have distinct files for functions and variables:

```diff
diff --git a/dist/lib/output/themes/DefaultTheme.js b/dist/lib/output/themes/DefaultTheme.js
index 46b5fae75b8945d6d1f1b42c8f7025b721e3b61e..80f90e0787aa8b49a0e8ec6a42009d83a3547330 100644
--- a/dist/lib/output/themes/DefaultTheme.js
+++ b/dist/lib/output/themes/DefaultTheme.js
@@ -227,6 +227,22 @@ DefaultTheme.MAPPINGS = [{
         isLeaf: false,
         directory: 'enums',
         template: 'reflection.hbs'
+    },{
+        kind: [index_1.ReflectionKind.Variable],
+        isLeaf: false,
+        directory: 'variables',
+        template: 'reflection.hbs'
+    },{
+        kind: [index_1.ReflectionKind.Function],
+        isLeaf: false,
+        directory: 'functions',
+        template: 'reflection.hbs'
+    }, {
+    },{
+        kind: [index_1.ReflectionKind.TypeAlias],
+        isLeaf: false,
+        directory: 'types',
+        template: 'reflection.hbs'
     }, {
         kind: [index_1.ReflectionKind.Namespace, index_1.ReflectionKind.Module],
         isLeaf: false,
```
typedoc-plugin-markdown + docusaurus-plugin-typedoc does generate the expected markdown files (`docs/api/*`) in an orderly file structure, reflecting the changes in the DefaultTheme class, with the appropriate links from index.md. However, the generated sidebar is now empty:
``` js
// typedoc-sidebars.js
module.exports = [];
```
Did I miss something in my patch, or is the issue in your codebase, where you might hold hard-coded assumptions on the used Theme class? I am willing to provide a full reproduction if you need one :-)

**EDIT**: reproduction here https://github.com/jsamr/typedoc-docusaurus-custom-theme

**Comment by jsamr** [comment]
@tgreyuk Here is a repro https://github.com/jsamr/typedoc-docusaurus-custom-theme

**Comment by tgreyuk** [comment]
@jsamr i can see why this is happening. The sidebar returns an empty array if it thinks the docs were not generated but this code returns a false positive in this case. I will get a fix out later..

**Comment by tgreyuk** [comment]
@jsamr please try with:

 - docusaurus-plugin-typedoc@0.2.1
 - typedoc-plugin-markdown@3.0.5

**Comment by jsamr** [comment]
@tgreyuk Your fix worked! Once again, thank you.

**Comment by jsamr** [comment]
@tgreyuk I noticed I am missing some information:

- Type aliases don't have the "signature" expression ![2020-10-02-125726_801x337_scrot](https://user-images.githubusercontent.com/3646758/94943914-d5a34600-04ae-11eb-8ca1-ce68807ad9fa.png)
- Variable don't have their associated type: 
![2020-10-02-125807_792x312_scrot](https://user-images.githubusercontent.com/3646758/94943986-eeabf700-04ae-11eb-94c1-0b965982a8f9.png)
- However, function do have their signature: 
![2020-10-02-125850_795x358_scrot](https://user-images.githubusercontent.com/3646758/94944036-084d3e80-04af-11eb-9d82-023874086dbb.png)

Should I open a separate issue?

**Comment by tgreyuk** [comment]
Ok sure - I can create it..

**Comment by tgreyuk** [comment]
Actually i will re-open this one as its all related.

**Comment by tgreyuk** [comment]
@jsamr as discussed in #158 -  behaviour can be implemented with `allRefelectionsHaveOwnDocument` option (I am not sure that is the best name or not). The sidebar categories are sorted in the order as the TypeDoc toc.

docusaurus-plugin-typedoc@0.3.0
typedoc-plugin-markdown@3.0.6

Let me know how you get on. I think any further issues mentioned with globals/navigation can be looked at with another issue.

**Comment by jsamr** [comment]
@tgreyuk It's almost working fine. Just noticed some parametrized types missing default.

Example with feature definition: 
![2020-10-04-151233_1048x351_scrot](https://user-images.githubusercontent.com/3646758/95023547-0ec8eb00-0654-11eb-803d-4950a86cfe62.png)


- typedoc-plugin-markdown@3.0.5 
![2020-10-04-151012_887x570_scrot](https://user-images.githubusercontent.com/3646758/95023513-daedc580-0653-11eb-8b07-d9448048dd6b.png)
- typedoc-plugin-markdown@3.0.6 
![2020-10-04-150953_858x567_scrot](https://user-images.githubusercontent.com/3646758/95023519-ea6d0e80-0653-11eb-9b2f-c0e36412098e.png)

**Comment by tgreyuk** [comment]
oops- yeah i will sort that..

**Comment by tgreyuk** [comment]
ok this should now all be working (have got some tests to avoid further regression)  typedoc-plugin-markdown@3.0.7

**Comment by jsamr** [comment]
@tgreyuk Working great! Thank you.
