### ISSUE TITLE
vuepress-plugin-typedoc unavailable

### ISSUE THREAD

**Issue by Lzw2016** [tgreyuk/typedoc-plugin-markdown#160]
```
    "typescript": "^4.0.3",
    "vuepress": "^1.7.1",
    "typedoc": "^0.19.2",
    "typedoc-plugin-markdown": "^3.0.9",
    "vuepress-plugin-typedoc": "^0.1.0"

```

![039}VB4L`)EA5TF(TOYV~_G](https://user-images.githubusercontent.com/19291563/96219073-9c8fc900-0fb8-11eb-9e95-1ba24d775726.png)

**Comment by tgreyuk** [comment]
@Lzw2016 I think the issue here was that TypeDoc did not compile and the error was not being handled properly. If you try with vuepress-plugin-typedoc@0.1.1 I am expecting that TypeDoc will gracefully log the error to the console.

**Comment by Lzw2016** [comment]
Sorry, due to other things delayed, so the reply is late.

use vuepress-plugin-typedoc@0.1.1 After that, no error was reported, but the document generation failed because the custom d.ts file could not be parsed

![OLYUC1SE83V`U1PT(805L~9](https://user-images.githubusercontent.com/19291563/96679983-3edbf200-13a7-11eb-8def-85e28f92a397.png)



![image](https://user-images.githubusercontent.com/19291563/96680159-967a5d80-13a7-11eb-8dfa-bd1064337739.png)

**Comment by tgreyuk** [comment]
@Lzw2016 so this is a TypeDoc compile issue (not this plugin). If you run with option `--ignoreCompilerErrors` then these errors should be ignored.

**Comment by Lzw2016** [comment]
I can now generate documents, thank you
