### ISSUE TITLE
bad ref since v 3.0.0

### ISSUE THREAD

**Issue by kaktus40** [tgreyuk/typedoc-plugin-markdown#161]
Hello, I updated the version of your plugin from 2.4.2 to 3.0.0 and I found a regression. For information, I use Hugo in order to convert the markdown pages to html and the regression stop the conversion.
In 2.4.2 I have 
``▸ **addEventListener**(`events`: string, `callBack`: [configurationCallback]({{< ref "_src_definitions_project_.md#configurationcallback" >}}), `uuid`: string, `scope?`: any): *string*

*Defined in [src/common/configuration.ts:327](https://github.com/kaktus40/shriveling_world/blob/36033bc/src/common/configuration.ts#L327)*``

and in 3.0.0 I have:

`` `addEventListener` | function | (events: string,callBack: [configurationCallback]({{< ref "\_src\_definitions\_project\_.md#configurationcallback" >}}),uuid: string,scope?: any) => string | - |``

The ref in the latest version (`\_src\_definitions\_project\_.md#configurationcallback`) points to nothing and it's different than others ref in the file (`{{< ref "../modules/_src_cone_conemeshshader_.md" >}}`).
I tested with the latest version of your plugin and it's the same issue.
Do you have an idea how to to remove bad ref?

**Comment by tgreyuk** [comment]
@kaktus40 Comparing the two refs the only difference is the escaped underscores. I have updated so the url refs are no longer escaped. Hopefully this resolves the issue but let me know if it doesn't.

typedoc-plugin-markdown@3.0.10

**Comment by kaktus40** [comment]
thanks, it works!
