### ISSUE TITLE
typedoc options ignored?

### ISSUE THREAD

**Issue by compojoom** [tgreyuk/typedoc-plugin-markdown#162]
We are using git submodules to include a github project. Out of the sources of that project we are generating API docs.

Ideally I would like to pass the tdconfig.json from the submodules folder. However it seems that passing `options: './submodules/submoduleA/tdconfig.json',` is being ignored. Is this expected? 
When I add 
```
"module": "commonjs",
        "target": "ES6",
        "readme": "none",
```

those are picked up, but if they are specified in the tdconfig.json - they are ignored.

**Comment by tgreyuk** [comment]
I think the options config only works with the CLI (it looks like you are using the TypeDoc api here?).  The functionality of parsing options is not actually handled by this plugin.

**Comment by compojoom** [comment]
Well, I just looked at the full example in the README and it has this line:
```
        // Additional TypeDoc options (see typedoc --help)
        mode: 'file',
        target: `ES2017`
```

so I typed typedoc --help and I saw the options and I tried to add them there and that's why I'm asking :)

**Comment by tgreyuk** [comment]
Ah ok sorry i didn't realise you were using docusaurus plugin. I should be able to make this work I will have a look.

**Comment by tgreyuk** [comment]
@compojoom thinking about this the most logical thing would be to just do an object spread?

```
someOption:true,
...require('./submodules/submoduleA/tdconfig.json'),
```

**Comment by compojoom** [comment]
wooooow, didn't think about this :D. Sounds like a nice "workaround".

**Comment by tgreyuk** [comment]
closing issue. options config is only relevant to TypeDoc CLI and workaround has been provided. Will update docs.
