### ISSUE TITLE
question: why is the gitbook theme no longer maintained from v3?

### ISSUE THREAD

**Issue by eelanagaraj** [tgreyuk/typedoc-plugin-markdown#163]
Out of curiosity (raised while debugging something with our project's gitbook), thanks!

**Comment by tgreyuk** [comment]
Basically decoupled all the custom theme stuff from the main package and the output was the same. Although the auto generation of `SUMMARY.md` i guess was useful. I can create a new package to generate this if useful?

**Comment by tgreyuk** [comment]
closing issue as no plan to support gitbook.

**Comment by eelanagaraj** [comment]
Sorry didn't see your response earlier, thank you for your answer!
