### ISSUE TITLE
root README.md inclusion

### ISSUE THREAD

**Issue by FranckFreiburger** [tgreyuk/typedoc-plugin-markdown#164]
Is it possible to avoid the root `README.md` file to be included in the output directory ?

My directory structure is :
```
.git/
build/
src/
docs/
README.md
package.json
...
```

The command line :
```
typedoc
 --plugin typedoc-plugin-markdown
 --mode file
 --tsconfig ./build/tsconfig.json
 --inputFiles ./src/index.ts
 --out ./docs
 --hideProjectName true
 --hideBreadcrumbs true
 --namedAnchors true
 --publicPath https://github.com/FranckFreiburger/vue3-sfc-loader/docs/
```

Then I end up with the README.md in the `docs/` directory.

**Comment by tgreyuk** [comment]
@FranckFreiburger try `--readme none`

**Comment by FranckFreiburger** [comment]
@tgreyuk thanks for the trick (`--readme false`)

Where can I found a complete list of typedoc-plugin-markdown command line options ?

**Comment by tgreyuk** [comment]
@FranckFreiburger  So the plugin options are the ones listed in the README. However in addition you use all applicable TypeDoc arguments https://github.com/TypeStrong/typedoc#arguments

**Comment by FranckFreiburger** [comment]
My bad, I thought that README.md inclusion was directly related to typedoc-plugin-markdown.
Thanks for your help.
