### ISSUE TITLE
How to properly set entryPoint?

### ISSUE THREAD

**Issue by AndyOGo** [tgreyuk/typedoc-plugin-markdown#165]
Using `--entryPoint '"index"'` option does not work.
https://typedoc.org/guides/options/#entrypoint

Assuming that `src/index.ts` becomes the entry point and being displayed within the toc under index.

**Comment by tgreyuk** [comment]
please see https://github.com/TypeStrong/typedoc#usage

**Comment by AndyOGo** [comment]
Thank you for your answer @tgreyuk 

I'm using a `typedoc.json` file and with `inputFiles` and `entryPoint` properties.
I consulted the docs from here:
https://typedoc.org/guides/options/#options

**Comment by tgreyuk** [comment]
So if using options file with typedoc0.20 you will need to use `entryPoints: ['../src/index.ts']`. The error above is a  typescript compilation error is the correct tsconfig file being read? https://typedoc.org/guides/options/#tsconfig

**Comment by AndyOGo** [comment]
thanks @tgreyuk 

Well, the thing is my typescript build and lint is working properly with custom declaration files.

I seems `typedoc` can't find them 😞 
https://github.com/TypeStrong/typedoc/issues/1089

This is my project:
https://github.com/AndyOGo/stylelint-declaration-strict-value/pull/132
