### ISSUE TITLE
Escaping angle brackets in mdx - left or right?

### ISSUE THREAD

**Issue by Avnerus** [tgreyuk/typedoc-plugin-markdown#167]
Hi!
I am using _typedoc-plugin-markdown_ to generate docs to be included in a custom _gatsby_ site that uses _gatsby-plugin-mdx_. 
When building the gatsby side with the generated docs I get the following error (among others of similar nature):
```
error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
unknown: Expected corresponding JSX closing tag for <number> (113:156)

  111 | <hr></hr>
  112 | <h3>{`setElevationRange`}</h3>
> 113 | <p>...{`: ReadonlyArray\\`}<number>{`): void`}</p>
```

I noticed that _typedoc-plugin-markdown_ escapes only the left angle bracket, but it seems that at least for _gatsby-plugin-mdx_, it is the right angle bracket that should be escaped. Changing the code to escape the right angle bracket **instead** of the left angle bracket fixes my error and shows the docs correctly. I also found some evidence for this [here](https://maxschmitt.me/posts/escape-html-mdx/).
I am not sure what is the reason for this inconsistency, I am assuming the left angle bracket solution works correctly in other cases of markdown. 
Any ideas?
Thank you!

/Avner

**Comment by tgreyuk** [comment]
Thanks for this. Yes having run some initial tests it does seem like escaping the right bracket is the correct approach. I will run some more tests and get a fix out.

**Comment by tgreyuk** [comment]
@Avnerus please try with 3.1.0 . Let me know if it still broken -thanks.

**Comment by Avnerus** [comment]
@tgreyuk It works perfectly now, thank you for the swift fix!
