### ISSUE TITLE
misses class properties

### ISSUE THREAD

**Issue by trueflywood** [tgreyuk/typedoc-plugin-markdown#17]
class
`
export abstract class DatabaseProviderBase {

    private webSQLBase: any;
    private base: SQLiteObject;

    constructor() {
       ........
    }

    /**
     * Создание связи с БД и создание необходимых таблиц в БД.
     *
     * @param {string[]} arrCreateTable
     */
    createDB(arrCreateTable: string[], platform, sqlite, ga) {
        ............
    }

    /**
     * Выполнение запроса к Базе данных
     *
     * @param {string} sql SQL строка
     * @param {any[]} data Данные для запроса
     * @returns {Promise<any>}
     */
    executeSql(sql: string, data: any[]): Promise<any> {
       ........
    }

    /**
     * Преобразование ответа от базы в масив нужного типа
     *
     * @param obj
     * @param {{new(l: any): T}} type
     * @returns {T[]}
     */
    getRowsType<T>(obj: any, type: { new (l: any): T; }): T[] {
        .........
    }

    /**
     * преобразование ответа от базы в масив елементов простого типа(number, string и т.д.)
     *
     * @param obj
     * @returns {T[]}
     */
    getRowsSimple<T>(obj: any): T[] {
       ........
    }
}
`

generated html
https://yadi.sk/i/E9H3iaRd3SLgJe

generated markdown
https://yadi.sk/i/bnF-xUiS3SLgd6

**Comment by tgreyuk** [comment]
Thanks for the detailed description. There was a bug where private props were being suppressed. Should be fixed in 1.0.13.
