### ISSUE TITLE
It no longer works with the latest TypeDoc

### ISSUE THREAD

**Issue by Vinnl** [tgreyuk/typedoc-plugin-markdown#173]
Just to have this logged somewhere: [TypeDoc released a breaking new version](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0), which causes an error in typedoc-plugin-markdown for me:

```
> npx typedoc src/index.ts --out docs/api/source/api

Info: Loaded plugin (..)/node_modules/typedoc-plugin-markdown
TypeDoc exiting with unexpected error:
TypeError: Right-hand side of 'instanceof' is not an object
    at ReflectionType.type ((..)/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:27:14)
    at getType ((..)/node_modules/typedoc-plugin-markdown/dist/resources/helpers/declaration-title.js:30:24)
```

The source of that error is this `instanceof` call in type.js:

```
    if (this instanceof types_1.StringLiteralType && this.value) {
        return getStringLiteralType(this);
    }
```

**Comment by tgreyuk** [comment]
@Vinnl please try typedoc-plugin-markdown@3.2.0 .

**Comment by Vinnl** [comment]
Huh. Sorry about that - I'd assumed I was on the latest version already, but for some reason Dependabot did not update typedoc-plugin-markdown. It does indeed work with the latest version, apologies for the noise.

**Comment by tgreyuk** [comment]
@Vinnl no need to apologise. When you initially upgraded I hadn't released the new version.
