### ISSUE TITLE
How to rename the output markdown files?

### ISSUE THREAD

**Issue by arvinxx** [tgreyuk/typedoc-plugin-markdown#175]
Look like the image below. I need to handle the generated markdown filename customly.
![image](https://user-images.githubusercontent.com/28616219/103305779-fc89fd80-4a46-11eb-92b3-c31966befca1.png)

for example `chromeextension.voice.md` -> `chromeextension-voice.md` to match my doc generator framework [dumi](https://d.umijs.org/) ,which can't recongize the `.` seperator

**Comment by tgreyuk** [comment]
Try `--filenameSeparator='-'` , available in typedoc-plugin-markdown@3.2.1

**Comment by arvinxx** [comment]
That works well! Thanks😁
