### ISSUE TITLE
how to rename the generated REAMDE.md to index.md ?

### ISSUE THREAD

**Issue by arvinxx** [tgreyuk/typedoc-plugin-markdown#176]
![image](https://user-images.githubusercontent.com/28616219/103486114-44899580-4e36-11eb-8611-2873c15a67f4.png)

 it seems that it will always generate readme File as README.md. By in my case I want to generated the README.md to index.md.

is there any configuration to control this?

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@3.3.0 contains new option `entryDocument`

`entryDocument 'index.md'`

**Comment by arvinxx** [comment]
work well~ thanks a lot.
