### ISSUE TITLE
question: is the naming rule change?

### ISSUE THREAD

**Issue by re4388** [tgreyuk/typedoc-plugin-markdown#178]
I upgrade packages as below
![image](https://user-images.githubusercontent.com/5414334/103509610-7a626480-4e9e-11eb-96e4-b443a9a2d32b.png)

file naming change from 
`_outterfolder_innerfolder_.filename.md`  -> `outterfolder_innerfolder.filename.md`

Since I also link these file into confluence pages..is it any way to convert back?

- I checked and try to use `filenameSeparator` in typedoc.json..but I think this is only related to the filename rule...
- or this is more about `typedoc` change?

**Comment by tgreyuk** [comment]
The filename pattern follows that of TypeDoc html theme, however I can see that this has caused a some unnecessary breaking change. I will get back to you with a solution.

**Comment by tgreyuk** [comment]
ok this was a bit more of an issue than i thought but I have sort of hacked a fix together. Please try `filenameSeparator=legacy`. This should render filenames as per older versions.

Available in @typedoc-plugin-markdown@3.3.0

**Comment by re4388** [comment]
I really really appreciate your fast response and action!
Unfortunately, I just found out that this kindly fix solves half of my problem.
Because the leading `_` is still there and this seems due to TypeDoc breaking change, also this change seems to be an "enhancement" for various reason (better compatible to other downstream systems, e.g. gh pages)

Still thanks a lot !!

**Comment by tgreyuk** [comment]
Ok - happy to have another look if you had a couple of examples i can test against.

**Comment by tgreyuk** [comment]
Closing this ticket as 'As designed'.
