### ISSUE TITLE
Tried to set an option (excludeNotExported) that was not declared

### ISSUE THREAD

**Issue by bennycode** [tgreyuk/typedoc-plugin-markdown#180]
I updated "typedoc-plugin-markdown" from 3.2.1 to 3.4.0 and now I am getting the following errors:

> Info: Loaded plugin C:\dev\projects\bennycode\coinbase-pro-node\node_modules\typedoc-plugin-markdown
> Error: Tried to set an option (excludeNotExported) that was not declared.
> Error: Tried to set an option (includeDeclarations) that was not declared.
> Error: Tried to set an option (inputFiles) that was not declared.
> Error: Tried to set an option (mode) that was not declared.

This is my "typedoc.json" file:

```json
{
  "disableOutputCheck": true,
  "exclude": ["**/demo/**/*", "**/payload/**/*", "**/test/**/*", "**/*+(index|.test*).ts"],
  "excludeExternals": true,
  "excludeNotExported": true,
  "excludePrivate": true,
  "excludeProtected": true,
  "includeDeclarations": false,
  "inputFiles": ["src"],
  "mode": "modules",
  "out": "docs",
  "theme": "markdown"
}
```

Have there been breaking changes in the config property naming? Could be also related to my typedoc upgrade to 0.20.14. When downgrading to typedoc v0.19.2 & typedoc-plugin-markdown v3.1.1, everything works just fine.

**Comment by tgreyuk** [comment]
Yes `excludeNotExported` has been removed in TypeDoc - see https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0 .

**Comment by bennycode** [comment]
Thanks for the hint! 

There were several problems in my setup:

1. I was using typedoc v0.19.2 and typedoc-plugin-markdown v3.1.1
2. I upgraded typedoc-plugin-markdown v3.1.1 to 3.4.0
3. I received an error about "entryPoints", so I guess v3.4.0 is incompatible with typedoc v0.19
4. I upgraded typedoc v0.19.2 to v0.20.14 and [migrated my config](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0)
5. Now it works!

So I guess [this version of typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown/releases/tag/typedoc-plugin-markdown%403.2.0) breaks compatibility with typedoc v0.19?

Can you list "typedoc" as "[peerDependency](https://nodejs.org/es/blog/npm/peer-dependencies/)" in your "package.json", so others would know which versions are compatible?

**Comment by tgreyuk** [comment]
Thanks @bennycode - it actually already is a peerDependency - not sure why you didn't get an npm warning.

**Comment by bennycode** [comment]
You are absolutely right:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/27e7cb7564c5fa2676781664094a7a128a7da404/packages/typedoc-plugin-markdown/package.json#L42-L44

I will close my ticket then. Thanks for being patient with me. :)
