### ISSUE TITLE
Question: vuepress plugin 

### ISSUE THREAD

**Issue by nadouani** [tgreyuk/typedoc-plugin-markdown#181]
Hello guys,

First of all thanks for the work and for sharing these plugins.
I've got a question about the workflow of using `typedoc-plugin-markdown` and `vuepress-plugin-typedoc`.

I've a typescript library I would like to generate a vuepress documentation for. When following the documentation of this repository, I end up with the following error:

```
Error: Invalid structure in plugin typedoc-github-wiki-theme, no function found.
Info: Loaded plugin typedoc-plugin-markdown
Error: The plugin vuepress-plugin-typedoc could not be loaded.
Info: TypeError: Cannot read property 'sourceDir' of undefined
    at exports.typedocPlugin (path/to/project/node_modules/vuepress-plugin-typedoc/dist/plugin.js:17:27)
    at PluginHost.load (path/to/project/node_modules/typedoc/dist/lib/utils/plugins.js:39:21)
    at Application.bootstrap (path/to/project/node_modules/typedoc/dist/lib/application.js:82:22)
    at Object.<anonymous> (path/to/project/node_modules/typedoc/bin/typedoc:25:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

I'm guessing the issue comes from one of the following errors:
- bad install of vuepress, or at least it's not bootstrapped on the correct folder
- missing plugin configurations
- bad command lines to build the docs

So the question is: "what's the right workflow"?

Thanks in advance for your answer.

**Comment by tgreyuk** [comment]
It's strange that there is a reference to `typedoc-github-wiki-theme` in the log. I don't suppose it is possible to share your setup?

**Comment by nadouani** [comment]
Hello @tgreyuk de can ignore that plugin, I had the issue before using it too. I can try to build a sample project with same config and share it with you

**Comment by nadouani** [comment]
What is mean by `This guide assumes that VuePress has already been locally installed`. Should vuepress project be installed on the same location as the project root?

**Comment by nadouani** [comment]
Well, I got something working that way:

- installed vuepress using `npm install -D vuepress`
- created a simple `.vuepress/config.js` on my TS project's root folder
- added the `docs:dev` and `doc:build` npm scripts to my project's `package.js`
- generated my markdown docs using `typedoc` and `typedoc-plugin-markdown` plugin

After that, running `npm run docs:build`  builds the vuepress site on `.vuepress/dist`

Is that the expected process?

**Comment by tgreyuk** [comment]
@nadouani thanks. yes apologies the readme needs to be improved. I will update with some clearer steps.

**Comment by Xia-Ao** [comment]
I have the same problem, did you update？

**Comment by tgreyuk** [comment]
Updated docs
