### ISSUE TITLE
modules output files sometimes in correct subdirectory and sometimes not

### ISSUE THREAD

**Issue by ctusch** [tgreyuk/typedoc-plugin-markdown#182]
In the output's `modules` directory some of the files are in the their respective subdirectory (e.g. `modules/folder1/module_name.md`) but others are located directly under `modules` with the folders prepended to their file name (e.g. `modules/folder2_module_name2.md`, like typedoc's HTML output).

I haven't found any pattern for which files are moved to the right subdirectory and which files are kept in the root and have their name prepended with their subdirectory.

Do you have any insight what might go wrong?

**Comment by tgreyuk** [comment]
I don't suppose your setup is available on a public repo? If not can you copy some of the titles of the pages that have the strange file patterns as that will give a clue to the type of reflections that are being affected. thanks.

**Comment by ctusch** [comment]
Yeah sorry, it's my company's code, so I can't share it. I just checked the output of another project and noticed that all module docs (no matter the nesting) should be in a flat list. So the strange thing with this project seems to be that some module docs are put in subdirectories.

Here are some examples:

Normal (I think):
`modules\classes_countries.md` (original `classes\countries.ts`)
`modules\components_tree_model_lazy_tree_node.md` (original `components\tree\model\lazy-tree-node.ts`)

But:
`modules\components\tree\tree.components_tree_tree_component.md` (original `components\tree\tree.component.ts`)
`modules\services\permissions\permissions.services_permissions_permissions_service.md` (original `services\permissions\permissions.service.ts`)

I think I can spot the problem now: If the original filename has an additional `.` the doc file isn't moved to `modules`. Also it seems to be prefixed with the part of the module name before the additional dot?

**Comment by tgreyuk** [comment]
@ctusch should be fixed with typedoc-plugin-markdown@3.4.1 - let me know.

**Comment by ctusch** [comment]
Thank you for looking into this so fast! Your fix worked, the output structure is now the same as normal typedoc output.

This is also true for the output in classes directory etc. To be honest I thought it was a feature that the files were in their respective directory since this hierarchical file structure is also used as TOC in the wiki we are using. I guess I'll write a script for that.

Thank you again for your quick help!
