### ISSUE TITLE
Vertical bar in table is not properly escaped

### ISSUE THREAD

**Issue by tomchen** [tgreyuk/typedoc-plugin-markdown#187]
Vertical bar (`|`) in a table is not properly escaped.

## Bug

Consider:

```ts
/**
 * @param n - a|b
 */
export function func(n: number | null): number | null {
  return n
}
```

It generates (only the "Parameters:" section is shown below):

```markdown
Name | Type | Description |
------ | ------ | ------ |
`n` | *number* | *null* | a|b    |
```

The text in both "Type" and "Description" contains unescaped `|`, making it render wrongly as:

Name | Type | Description |
------ | ------ | ------ |
`n` | *number* | *null* | a|b    |

## Solution

`|` should be escaped as `\|`

```markdown
Name | Type | Description |
------ | ------ | ------ |
`n` | *number* \| *null* | a\|b    |
```

Name | Type | Description |
------ | ------ | ------ |
`n` | *number* \| *null* | a\|b    |

## Environment

* typedoc: 0.20.19
* typedoc-plugin-markdown: 3.4.4

**Comment by tgreyuk** [comment]
@tomchen yes thanks for this - fix in typedoc-plugin-markdown: 3.4.5

**Comment by tomchen** [comment]
Umm, so now all vertical bars are escaped, not only those in tables but also those outside table...

OK, although we don't need to escape them outside a table, I can see all markdown parsers treat escaped `\|` and unescaped `|` the same way, so it should not be a problem.

**Comment by tomchen** [comment]
Very quick fix and release btw. Thx.
