### ISSUE TITLE
improve markdown formatting

### ISSUE THREAD

**Issue by amilajack** [tgreyuk/typedoc-plugin-markdown#188]
The current formatting is difficult to read because of how dividers are used to separate content.

## Current Output

```
# Interfaces

### Properties

#### foo

...

# Classes

...

---

#### bar

...

---

```

## Expected Output

I think rendering dividers between top level headers (Interfaces and Classes) and rendering line breaks between similar items renders more readable markdown:

```

# Interfaces

...

### Properties

#### foo

...

<br/>

#### bar

...

---

# Classes

...

```

Would a PR to make this change be welcome?

**Comment by tgreyuk** [comment]
hi @amilajack i am not recognising the output (multiple h1 on same doc) - are you using an additional tool?

**Comment by tgreyuk** [comment]
Closing as per above comments. Please re-open if there is still. an issue.
