### ISSUE TITLE
Question: Markdown theme

### ISSUE THREAD

**Issue by lukaszjedrasik** [tgreyuk/typedoc-plugin-markdown#189]
How can I apply my own custom theme for md files?

I have only information like: `is not a recognised markdown theme. If an html theme is required, please disable this plugin.`

**Comment by tgreyuk** [comment]
You can in theory customise the markdown theme. Have created a branch with some basic notes - https://github.com/tgreyuk/typedoc-plugin-markdown/blob/custom-theme-doc/packages/typedoc-plugin-markdown/CUSTOM_THEME.md

Not really promoting it at the moment as there may be a move away from handlebars at some point.

**Comment by lukaszjedrasik** [comment]
Ohh.. and that's all? I mean, I should only create this file? Where is the catch? :D

```js
import MarkdownTheme from 'typedoc-plugin-markdown/dist/theme';

export default class MyCustomTheme extends MarkdownTheme {
  constructor(renderer, basePath) {
    super(renderer, basePath);
  }
}```

**Comment by tgreyuk** [comment]
Yeah it depends what you want to customise.

Theme can be extended like:

https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-github-wiki-theme

or  you can override any of the handlebars resources using this file structure:

![image](https://user-images.githubusercontent.com/11680870/106156935-0a33bf80-617a-11eb-8deb-e51b9228ff53.png).

Basically the same principle as customising the default html theme.

**Comment by lukaszjedrasik** [comment]
I think something is wrong for me. I have installed `typedoc: 0.20.20` and `typedoc-plugin-markdown: 3.4.5`.

I have created `mytheme` folder with `theme.js` file which includes this simple script:

```js
import MarkdownTheme from 'typedoc-plugin-markdown/dist/theme';

export default class VsfTheme extends MarkdownTheme {
  constructor(renderer, basePath) {
    super(renderer, basePath);
  }
}
```

I set the path in `typedoc.json` and it looks like below:
```
{
  "includeVersion": true,
  "hideBreadcrumbs": true,
  "hideInPageTOC": true,
  "plugin": ["typedoc-plugin-markdown"],
  "theme": "./mytheme/theme"
}
```

Unfortunately, still I have 
`Warning: [typedoc-plugin-markdown] './mytheme/theme' is not a recognised markdown theme. If an html theme is required, please disable this plugin.` 

Do you have any idea? @tgreyuk

**Comment by tgreyuk** [comment]
you will need to transpile the theme.js or just write something like:
```const {
  default: MarkdownTheme,
} = require("typedoc-plugin-markdown/dist/theme");

exports.default = class CustomTheme extends MarkdownTheme {
  constructor(renderer, basePath) {
    super(renderer, basePath);
  }
};
```
