### ISSUE TITLE
Support custom_edit_url

### ISSUE THREAD

**Issue by stephenhandley** [tgreyuk/typedoc-plugin-markdown#190]
Would it be possible to default `custom_edit_url` to null in typedoc generated documentation so that an `Edit` link isn't shown? I think that makes sense to avoid giving people the impression they should be editing generated documentation.. 

https://github.com/facebook/docusaurus/pull/2166/files#diff-c889574cdba5bf5bc3aeef35c24ca9806089814ffc71a27daf7924d4aa2210d7R2

**Comment by tgreyuk** [comment]
yes good suggestion. have disabled by default - i can see no use-case to make this configurable. available in `0.9.0`

**Comment by stephenhandley** [comment]
awesome thanks for the quick turn around on this!
