### ISSUE TITLE
How to hide Hierarchy from markdown?

### ISSUE THREAD

**Issue by gpbl** [tgreyuk/typedoc-plugin-markdown#192]
I'm using the Docusaurus plugin and I would like to hide the "Hierarchy" paragraph – since the interfaces I am documenting never extend anything.

<img width="400" alt="Screenshot 2021-02-10 at 17 45 08" src="https://user-images.githubusercontent.com/120693/107583187-90afbe80-6bc8-11eb-8986-f480d4f2a0cb.png">

Do others have the same need? Any idea how to hide it?

**Comment by tgreyuk** [comment]
@gpbl this follows the pattern of the html theme but you make a  valid point. I can add some functionality so the hierarchy block will only be shown if relevant. Just need to decide whether to do it globally (would be preferable to providing an additional option). I can't see any use-case for keeping it in this scenario though.

**Comment by tgreyuk** [comment]
As of 3.5.0 hierarchy block will only display if relevant.

**Comment by gpbl** [comment]
Thanks – working great!
