### ISSUE TITLE
Watch mode for Docusaurus plugin?

### ISSUE THREAD

**Issue by gpbl** [tgreyuk/typedoc-plugin-markdown#193]
Typedoc [recently added](https://github.com/TypeStrong/typedoc/pull/1482) a `--watch` option. I already miss it when using the Docusaurus plugin – it would be a good improvement for the dev experience. 

How to trigger a Docusaurus rebuild when saving the TS sources?

**Comment by tgreyuk** [comment]
@gpbl ok will have a look.

**Comment by tgreyuk** [comment]
@gpbl support for watch provided in docusaurus-plugin-typedoc@0.10.0.

This does appear to work as expected, however please note that  docusaurus simultaenous fires off multiple console messages. In addition if the sidebar structure changes there will be some error logs about missing files while the docs catch up. 

I think this will be fixed when debounce reload functionality is released - https://github.com/facebook/docusaurus/issues/4050.

**Comment by gpbl** [comment]
Yeah there were some strange logs (I had to add a `sidebars.js` into the root, for example), but it works great so far! Thanks this makes easier writing better docs!

**Comment by tgreyuk** [comment]
> Wondering however about the best way to toggle the watch setting only in development 

Interesting question. I think the way to do this is to move the watch out of `docusaurus.config` and into cli with a custom command. Something like:

```
 "start": "docusaurus typedoc:start-and-watch",
 "build": "docusaurus build",
```

I will get back to you...

**Comment by gpbl** [comment]
> I think the way to do this is to move the watch out of docusaurus.config and into cli with a custom command. 

I'm not familiar with the internals there – maybe we can use a different `typedoc.json`? Since in typedoc we can pass it via CLI: `typedoc --options typedoc.dev.json`. Or specify a different docusaurus config on dev that would merge the production one (I don't think is possible)?

**Comment by tgreyuk** [comment]
How about environment variable?

package.json:
```
"start": "WATCH=true docusaurus start",
```

docusaurus.config.js:
```
watch: process.env.WATCH,
```

**Comment by gpbl** [comment]
This could work too! But the `process.env.WATCH` should be added to the webpack `DefinePlugin` (I think the Docusaurus plugin had a lifecycle for that), and maybe name it `TYPEDOC_WATCH` or something?

**Comment by gpbl** [comment]
Thanks a lot @tgreyuk works great! 👍🏽
