### ISSUE TITLE
Split static and non-static class methods

### ISSUE THREAD

**Issue by YashTotale** [tgreyuk/typedoc-plugin-markdown#195]
Right now, both static and non-static class methods are grouped in the `Methods` section. It would be great if there was an option to split the `Methods` section into `Static Methods` and `Non Static Methods` sections.

**Comment by tgreyuk** [comment]
Possibly - although this kind of functionality I think would better implemented in a separate plugin or TypeDoc core. Will leave open for discussion.

**Comment by tgreyuk** [comment]
As mentioned this is not something for this plugin to fix. Although not exactly what you want the new sorting option may be of interest https://typedoc.org/guides/options/#sort.
