### ISSUE TITLE
Render @example sections as fenced code blocks

### ISSUE THREAD

**Issue by justinkambic** [tgreyuk/typedoc-plugin-markdown#196]
## Feature request

I would love it if there were a feature that would convert my `@example` comments to fenced code blocks.

### Example

```typescript
  /**
   * Initializes a class instance from a file in memory.
   * @param buffer the file data
   * @example
   * const buffer = fs.readFileSync('./my.file');
   * const instance = new Class();
   * instance.readBuffer(buffer);
   */
```

this yields markdown text today that looks like:

\**\`example`** 
const buffer = fs.readFileSync('./my.file');
const instance = new Class();
instance.readBuffer(buffer);

It would be super cool if the plugin instead rendered it like:
\**\`example`** 
\```typescript
const buffer = fs.readFileSync('./my.file');
const instance = new Class();
instance.readBuffer(buffer);
\```

Then when my docs are viewed by users on GitHub they'd see the examples rendered as:

**`example`** 
```typescript
const buffer = fs.readFileSync('./my.file');
const instance = new Class();
instance.readBuffer(buffer);
```

**Comment by tgreyuk** [comment]
hi @justinkambic . You can use fenced code blocks in Doc comments which would achieve the output you require (although there may be a reason you don't want to do that?).

```typescript
/**
 * Initializes a class instance from a file in memory.
 * @param buffer the file data
 * @example
 * ```typescript
 * const buffer = fs.readFileSync('./my.file');
 * const instance = new Class();
 * instance.readBuffer(buffer);
 * ```
 */
```
