### ISSUE TITLE
Doesn't build anymore

### ISSUE THREAD

**Issue by mrousavy** [tgreyuk/typedoc-plugin-markdown#198]
Hi!

I've managed to install your plugin once, but now I can't get it to build anymore. I've reverted my commits to when it worked, but I couldn't manage to get it working again.

Could you please take a quick look and tell me what I did wrong?

* [my `tsconfig.json`](https://github.com/cuvent/react-native-vision-camera/blob/main/tsconfig.json)
* [my docs/ directory (includes docusaurus config, etc)](https://github.com/cuvent/react-native-vision-camera/tree/main/docs)

I'm a bit lost, as I don't see any error messages at all - I just noticed that nothing is being built into the `api` folder and the sidebar is also empty :(

**Comment by mrousavy** [comment]
Nevermind, i downgraded typescript to 4.1.5 and it started working again. Apparently it's not yet compatible with 4.2, but doesn't throw errors.

**Comment by mrousavy** [comment]
Actually, I'm still experiencing issues on TS 4.1.5. I also tested TS 4.0.7, but this also didn't help. `docs/api` markdown files and the sidebar simply doesn't build anymore, no errors are being output - do you maybe have an idea if something's wrong with my configs?

**Comment by mrousavy** [comment]
I've been debugging the JS a bit and I think this happens because this plugin (or typedoc) tries to also consume/parse the `example/` folder, even though it is excluded in the `tsconfig.json` (and will also not be built with typedoc because of the entry files being set to `src/`)

Is there a way I can explicitly tell this plugin (or typedoc) to only parse a specific folder and completely ignore the rest?

Also, apparently such errors are being swallowed, might be good to cancel the docusaurus build if anything goes wrong in this plugin.

**Comment by tgreyuk** [comment]
@mrousavy you can create a `tsconfig.json` in the docs folder like this:
```
{
  "extends": "../tsconfig.json",
  "exclude": ["../example"]
}
```

and then reference it in `docusaurus.config.js`:

```
  tsconfig: './tsconfig.json',
```

**Comment by mrousavy** [comment]
Oh right, my bad I thought I was using `tsconfig.build.json`. Thanks!
