### ISSUE TITLE
links without the .md extension

### ISSUE THREAD

**Issue by nrob81** [tgreyuk/typedoc-plugin-markdown#199]
Hello, 
thanks for this great plugin!

I am trying to use it in gitlab wiki, but that wiki uses links to subpages without the md extension.
Can i somehow set up this plugin to ignore the file excention in links? 

Thank you!

**Comment by tgreyuk** [comment]
This will be possible but I will need to get back to you with the solution.

**Comment by nrob81** [comment]
Thank you! I will be here

**Comment by tgreyuk** [comment]
Have created a custom theme for Gitlab Wiki https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-gitlab-wiki-theme

Let me know if it works ok for you....

thanks..

**Comment by nrob81** [comment]
It works like a charm.
Thank you, Tom!

**Comment by tgreyuk** [comment]
No probs - feel free to raise new issues if you spot anything not working.
