### ISSUE TITLE
exclude options

### ISSUE THREAD

**Issue by danmarshall** [tgreyuk/typedoc-plugin-markdown#2]
Hello, cool project! I'm super glad this is happening :)

I gave it a try and the first thing I want to do is exclude some stuff
https://github.com/TypeStrong/typedoc#source-file-handling

--excludeExternals
Prevent externally resolved TypeScript files from being documented.

--excludePrivate
Prevent private members from being included in the generated documentation.

Do the main options get passed to the markdown plugin?

**Comment by tgreyuk** [comment]
Thanks for feedback.  Yes all the options will get passed to the plugin but these specific options are being ignored at the moment as Typedoc hides the items with CSS rather than filters from build. This will be easy to fix though will have a look at it next.

**Comment by danmarshall** [comment]
Also I see others seem to be working on a markdown theme: https://github.com/TypeStrong/typedoc/issues/533

**Comment by tgreyuk** [comment]
Have run some tests and both --excludeExternals and --excludePrivate should work as expected as per version 0.0.12.
