### ISSUE TITLE
docusaurus: How to set typedoc configuration?

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#200]
I tried to put a `typedoc.json` or a `typedoc.js` in both my `website` folder and my project's folder, but none seem to work. It would be good if we could use custom TypeDoc configs, so we could customize more fields, such as `name`, `includeVersion`, etc.

If it was possible, we could also customize the markdown plugin's configuration as well through `typedoc.json`.

**Comment by felipecrs** [comment]
Ok, I found that we can specify any option, and it will be passed to TypeDoc. Example:

```js
name: "Megatar"
```

**Comment by felipecrs** [comment]
> I think you have highlighted 2 things:
> 
> 1. Documentation is not clear how to pass TypeDoc options
> 2. It would be good to be able to use an options file as per TypeDoc cli.
> I will look at addressing both of these things....
> 
> Thanks.....

Awesome! I didn't try, but maybe `options: "path/to/typeconfig.json"` could work.

**Comment by tgreyuk** [comment]
Additional plugins/options can be set 
a) using `typedoc.json`
b) `options: path.resolve(__dirname, "path/to/typeconfig.json")`

**Comment by tgreyuk** [comment]
Just to add for reference options can be added to tsconfig too:
> When TypeDoc loads a tsconfig.json file, it also will read TypeDoc options declared under the typedocOptions key.
