### ISSUE TITLE
docusaurus: TypeDoc doesn't load additional plugins

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#201]
I think that for similar reasons to #200, the TypeDoc is not loading additional plugins installed.

I need to load [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules) because of https://github.com/TypeStrong/typedoc/issues/1526.

**Comment by felipecrs** [comment]
Ok:

```js
plugin: ["typedoc-plugin-merge-modules"],
``

This works.

**Comment by tgreyuk** [comment]
I think you have highlighted 2 things:

1. Documentation is not clear how to pass TypeDoc options
2. It would be good to be able to use an options file as per TypeDoc cli.

I will look at addressing both of these things....

Thanks.....

**Comment by felipecrs** [comment]
Awesome! Let's move this conversation to #200.
