### ISSUE TITLE
feat(docusaurus): new option sidebar.omitReadme: boolean

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#203]
In my project, I'd like to move the Readme page one level higher in the sidebars. This could be easily achieved by adding a new option:

```js
sidebar: { 
  omitReadme: true, // defaults to false
},
```

So I would manually tweak my `sidebars.js` to:

```js
module.exports = {
  sidebar: [
    "api/index", // the README page generated by this plugin
    {
      API: require("./typedoc-sidebar.js"),
    },
  ],
};

```

**Comment by tgreyuk** [comment]
@felipecrs with the introduction of autogenerated sidebars I don't think this will be possible (see #217). I think the solution here would be to use `readme:none` and manage the readme file independently?

**Comment by felipecrs** [comment]
Hm.. interesting, I will play with it in the weekend and see what are the options, but it can be indeed the only solution.
