### ISSUE TITLE
Nested Parameters with Interface

### ISSUE THREAD

**Issue by joshkarges** [tgreyuk/typedoc-plugin-markdown#204]
Working off https://github.com/tgreyuk/typedoc-plugin-markdown/issues/191, it seems like nested parameters only works if you explicitly define the object shape in the function signature.  If that shape is defined outside in another interface or type, it doesn't work.

```
/** This works 
 * @param __namedParameters This is an options object
 * @param __namedParameters.one This is option 1.
 * @param __namedParameters.two This is option 2.
 */
export const myFunc({one, two}: {one: string, two: string}) => one + two;

interface Options {
  one: string;
  two: string;
}

/** This doesn't
 * @param __namedParameters This is an options object
 * @param __namedParameters.one This is option 1. (not documented)
 * @param __namedParameters.two This is option 2. (not documented)
 */
export const myFunc2({one, two}: Options) => one + two;
```

A hacky solution would be to just export the `Options`, but I don't think the user should have to have it, and it will also put those docs in a separate place than the `myFunc2` docs, which isn't desirable.

Any help would be appreciated!  Thanks!  I love the tool overall!

Versions:
- `typedoc@0.20.29`
- `typedoc-plugin-markdown@3.6.0`

**Comment by tgreyuk** [comment]
I am not seeing any comments in the model from the converter and actually the same issue is present with the default html theme.  I will follow this up.

Thanks for feedback!!

**Comment by tgreyuk** [comment]
Apologies for the delay in the follow up. 

This appears to be the same issue/requirement as https://github.com/TypeStrong/typedoc/issues/1569. 

As `Options` is not exported then this is 'As Designed' unfortunately. The referenced ticket will provide further info.  

In any case this is not something that can be controlled at plugin level.
