### ISSUE TITLE
typedoc-plugin-markdown v3.6.0 does not work

### ISSUE THREAD

**Issue by rendunia** [tgreyuk/typedoc-plugin-markdown#205]
In the latest 3.6.0 version the typedoc-plugin-markdown does not work. Typdoc generates documents with  `.md` extension, but `html` inside the file. After downgrading to v3.5.0 everything is back to normal and documents are generated correctly.

**Comment by tgreyuk** [comment]
Hi.. Would you please copy the options you were using to generate - i am trying to replicate this behaviour. Thank you.

**Comment by rendunia** [comment]
I will come back with this issue after deeper investigation on my side. I am closing this issue for now.

**Comment by dmytroap** [comment]
@a-tylenda, did you figure out the reason? I have a similar issue with one of my project and at the same time, everything is working with the same configuration and versions on another project.

**Comment by tgreyuk** [comment]
@dmytroap is your project on a public repo? If so i can try and replicate. thanks.

**Comment by dmytroap** [comment]
Unfortunately, no, it's in a private repo. I'm trying to find how to replicate the issue from scratch, but for now without any success.

**Comment by a-tylenda** [comment]
Hi there,
to be honest I don't remember. My colleague helped me sort it out, I will ask if he remembers. At this moment typedoc & markdown-plugin work just fine.

These are my options in `tsconfig.json`:
```
    "typedocOptions": {
      "entryPoints": ["src/index.ts"],
      "out": "../../docs",
      "plugin": "typedoc-plugin-markdown",
      "readme": "none",
      "toc": "true"
  }
```

and devDependencies:
```
{
"devDependencies": {
        "typedoc": "0.20.28",
        "typedoc-plugin-markdown": "3.4.5",
    }
}
```

**Comment by dmytroap** [comment]
@a-tylenda, thanks, for provided config and versions, unfortunately, no luck with them as well. If you or your colleague will remember something I will be very appreciated.

**Comment by a-tylenda** [comment]
Hi, my colleague said that there was some kind of issue between typedoc-plugin-markdown version and typescript version, after upgrading both typedoc-plugin-markdown started to work.
```
{
    "typedoc": "0.20.28",
    "typedoc-plugin-markdown": "3.4.5",
    "typescript": "4.1.4"
}
```
that is all I know. I hope it helps.

**Comment by dmytroap** [comment]
@a-tylenda, thanks for the reply, unfortunately, these direct versions also didn't help :(
