### ISSUE TITLE
Question(ish): Why will it not dump html in my pipeline? [vuepress plugin]

### ISSUE THREAD

**Issue by Neunerlei** [tgreyuk/typedoc-plugin-markdown#206]
Hello there,

I'm not sure if I'm running into a bug, or if I'm doing something wrong on my end, and I would really appreciate a word of advice 🙏 .

I'm trying to integrate your "vuepress-plugin-typedoc" plugin with a vuepress installation. 
Just for reference: my [package.json](https://github.com/labor-digital/bits/blob/master/docs/package.json), my [vuepress config.js](https://github.com/labor-digital/bits/blob/master/docs/.vuepress/config.js). I'm trying to build the latest vuepress with the latest version of your plugin. 

It works as expected on my windows machine, both with "vuepress dev ." and with "vuepress build ." but fails to generate the api html when I build it in a github action. 

As far as the log output goes everything works fine: 
```
> @labor-digital/bits-docs@1.0.0 build:vuepress /github/workspace/docs
> vuepress build .

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin typedoc (i.e. "vuepress-plugin-typedoc") ...
Info: Loaded plugin typedoc-plugin-markdown

Info: Documentation generated at /github/workspace/docs/api
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Server: Compiled successfully in 8.33s
[success] [webpackbar] Client: Compiled successfully in 13.09s
wait Rendering static HTML...
success Generated static files in .vuepress/dist.
``` 

I let the script run an "ls -la" on the working dir /docs, which looks ok
```
drwxr-xr-x   6 1001  121   4096 Mar 16 20:44 .
drwxr-xr-x  10 1001  121   4096 Mar 16 20:44 ..
drwxr-xr-x   5 1001  121   4096 Mar 16 20:44 .vuepress
-rw-r--r--   1 1001  121   3628 Mar 16 20:43 README.md
drwxr-xr-x   4 root root   4096 Mar 16 20:44 api
drwxr-xr-x   2 1001  121   4096 Mar 16 20:43 guide
drwxr-xr-x 828 1001  121  36864 Mar 16 20:44 node_modules
-rw-r--r--   1 1001  121 412582 Mar 16 20:43 package-lock.json
-rw-r--r--   1 1001  121   1019 Mar 16 20:43 package.json
```

The insides of the "/docs/api" directory, look like something I would expect 🤔 
```
drwxr-xr-x 4 root root 4096 Mar 16 20:44 .
drwxr-xr-x 6 1001  121 4096 Mar 16 20:44 ..
-rw-r--r-- 1 root root 5180 Mar 16 20:44 README.md
drwxr-xr-x 2 root root 4096 Mar 16 20:44 classes
drwxr-xr-x 2 root root 4096 Mar 16 20:44 interfaces
```

But then, the ".vuepress/dist" directory does not have an "api" directory :(
```
drwxr-xr-x 5 root root  4096 Mar 16 20:44 .
drwxr-xr-x 5 1001  121  4096 Mar 16 20:44 ..
-rw-r--r-- 1 root root     0 Mar 16 20:44 .keep
-rw-r--r-- 1 root root  1983 Mar 16 20:44 404.html
drwxr-xr-x 5 root root  4096 Mar 16 20:44 assets
drwxr-xr-x 4 root root  4096 Mar 16 20:44 demo
-rw-r--r-- 1 root root   318 Mar 16 20:44 favicon.ico
drwxr-xr-x 2 root root  4096 Mar 16 20:44 guide
-rw-r--r-- 1 root root 10888 Mar 16 20:44 index.html
```

And from here on out, I don't see whats wrong...
* I added a console.log() in your "plugin.js" to see if it generates the "Sidebar" -> It does
* I removed all my additional scripts that run before vuepress gets build -> No change
* I downgraded to 3.5.0 -> No change
* I removed all .gitignores to see if that helped -> It did not
* I added an older version of typescript as dependency -> no change

I'm using [this action](https://github.com/marketplace/actions/vuepress-deploy) to deploy vuepress to github pages, but I don't see why that would make any difference. I ran the script on a normal "node" image to build it, but as expected no change. 

Do know anything I could try? 

Thanks in advance!

**Comment by tgreyuk** [comment]
I have had a brief look at this and I can't see anything obvious. I will try and replicate with github action and get back to you.

**Comment by tgreyuk** [comment]
@Neunerlei apologies for the delay I had to do a bit of digging to work out what was going on. 

Please try with vuepress-plugin-typedoc@0.6.0

**Comment by Neunerlei** [comment]
@tgreyuk Thank you, very, very much 😁 
That worked 👍

Have a great day and stay save 😷 

P.S. If there is something I can do to support you, or your work, let me know.
