### ISSUE TITLE
Table of contents: remove in 0.12?

### ISSUE THREAD

**Issue by tony** [tgreyuk/typedoc-plugin-markdown#209]
Hi there @tgreyuk ! Thank you for this project!

In https://github.com/tgreyuk/typedoc-plugin-markdown/commit/07ed9738a1abf136e523fcd353b6a97691317c4c (0.12 release) `hide_table_of_contents: true` is added to frontmatter of `index.md` files.

Do we have any more information on why this was removed?

If pointing to an `entryPoints: ['../mypackage/src/index.ts']` and using `allReflectionsHaveOwnDocument: false`, having a ToC on the index works well for me.

**Comment by tony** [comment]
Wow good timing! You just pushed something

@tgreyuk Here's an example of me using the ToC in 0.11.x: https://social-embed.git-pull.com/docs/lib/api / [config](https://github.com/social-embed/social-embed/blob/6547f8d5ee6d0022038c65069ba8d1dd7d08b21f/packages/site/docusaurus.config.js#L24-L37)

**Comment by tgreyuk** [comment]
Yes thanks @tony .. It was to prevent duplicating the main content TOC, but actually this is not always the case. Will only remove if `allReflectionsHaveOwnDocument: true` for now which will fix for your use case. Fixed in 0.12.1.

**Comment by tony** [comment]
Live here: https://social-embed.git-pull.com/docs/lib/api

Looking good @tgreyuk ! Thank you very much!

I will close this issue for now assuming this is solved.
