### ISSUE TITLE
RFC (docusaurus-plugin-typedoc): Tabulate call signatures

### ISSUE THREAD

**Issue by Nytelife26** [tgreyuk/typedoc-plugin-markdown#210]
[Docusaurus has the ability to tabulate markdown](https://docusaurus.io/docs/markdown-features/tabs). Given that TypeDoc's default is to tabulate call signatures, why not do the same for the plugin? Of course, the feature should be optional, in case some people prefer the current style - but it does raise the question, should we not support tabulation for more compact documentation?

**Comment by tgreyuk** [comment]
Looks interesting but I am trying to figure out in what scenario TypeDoc tabulates call signatures. Do you have a code sample?

**Comment by Nytelife26** [comment]
> Looks interesting but I am trying to figure out in what scenario TypeDoc tabulates call signatures. Do you have a code sample?

Sure! For example, in a package I have contributed to:

This table
![2021-04-07_22-37-03](https://user-images.githubusercontent.com/22531310/113937953-d2886a00-97f1-11eb-87b6-3bcc24ff6cda.gif)

is parsed from this set of call signatures
```typescript

	/**
	 * Similar to [[Args.peekResult]] but returns the value on success, throwing otherwise.
	 * @param type The function, custom argument, or argument name.
	 * @example
	 * ...
	 */
	public async peek<T>(type: () => ArgumentResult<T>): Promise<T>;
	/**
	 * Similar to [[Args.peekResult]] but returns the value on success, throwing otherwise.
	 * @param type The function, custom argument, or argument name.
	 * @example
	 * ...
	 */
	public async peek<T>(type: IArgument<T>, options?: ArgOptions): Promise<T>;
	/**
	 * Similar to [[Args.peekResult]] but returns the value on success, throwing otherwise.
	 * @param type The function, custom argument, or argument name.
	 * @example
	 * ...
	 */
	public async peek<K extends keyof ArgType>(type: (() => ArgumentResult<ArgType[K]>) | K, options?: ArgOptions): Promise<ArgType[K]>;
```

**Comment by tgreyuk** [comment]
Going to close this as it doesn't really work with horizontal tabs. On a general point it keeps it a bit cleaner keeping the output as Markdown rather than introducing mdx components.
