### ISSUE TITLE
docs(docusaurus) id is a required parameter?

### ISSUE THREAD

**Issue by thgh** [tgreyuk/typedoc-plugin-markdown#211]
Based on this line, I figured out that I should add an `id` option. This is not mentioned in the README...

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/c144a00cdfc7b037a51c0213487a167a225f95f9/packages/docusaurus-plugin-typedoc/src/plugin.ts#L19

**Comment by tgreyuk** [comment]
Hi... it is not a required parameter because a default id is internally set. It is only really relevant if using multi instances. Are you experiencing an error with something?

**Comment by tgreyuk** [comment]
Closing issue. Please re-open if there is an issue that can be re-produced.
