### ISSUE TITLE
docusaurus-plugin-typedoc: Extending a generic class and inheriting the constructor causes invalid MDX

### ISSUE THREAD

**Issue by yiliansource** [tgreyuk/typedoc-plugin-markdown#215]
When Docusaurus is rendering a class that inherits a generic constructor, the angle brackets in that constructor aren't escaped. I assume this wasn't adressed in #167 since it's relatively uncommon.

---

I have included snippets from my files below, for reference:

***spline.ts***
```ts
export abstract class Spline<T> {
    constructor(...keys: SplineKey<T>[]) {
        // ...
    }
}
```

***gradient.ts***
```ts
export class Gradient extends Spline<Colour> {
    // Note that we do not override the constructor here, so it's inherited.
    // ...
}
```

And the resulting Markdown file:

```md
[...]

#### Parameters:

| Name      | Type                                  |
| :-------- | :------------------------------------ |
| `...keys` | _SplineKey_<[_Colour_](colour.md)\>[] |

**Returns:** [_Gradient_](gradient.md)

Inherited from: Spline<Colour>.constructor

[...]
```

As you can see, the angle brackets are not escaped.

**Comment by tgreyuk** [comment]
Thanks... please try with typedoc-plugin-markdown@3.7.2

**Comment by yiliansource** [comment]
Thanks, that fixed it!
