### ISSUE TITLE
Set position of "Table of contents"

### ISSUE THREAD

**Issue by jsamr** [tgreyuk/typedoc-plugin-markdown#216]
It would be nice to benefit from `sidebar_position` frontmatter field to hoist the table of contents to the top!

See https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs#markdown-frontmatter

**Comment by tgreyuk** [comment]
Hi @jsamr..Yes with the introduction of autogenerated sidebars need to update the sidebars implementation. I will have a look.

**Comment by tgreyuk** [comment]
@jsamr this is the proposed approach to autogenerated sidebars https://github.com/tgreyuk/typedoc-plugin-markdown/pull/217.

The 'Table of Contents' will be hoisted to the top by default (still not entirely happy with how the the toc page is working but thats a different issue).

Let me know if you would require any further control over the sidebars.

Thanks...

**Comment by tgreyuk** [comment]
Auto-generated sidebars now default in docusaurus-plugin-typedoc@0.14.0

**Comment by jsamr** [comment]
@tgreyuk Thank you so much! I'll try it out when I get back to documentation on my project and give you feedback. Should happen soon

**Comment by jsamr** [comment]
@tgreyuk The issue is now fixed, thank you!
