### ISSUE TITLE
Missing space between `Const` and it's name

### ISSUE THREAD

**Issue by KillyMXI** [tgreyuk/typedoc-plugin-markdown#220]
I have a code that looks similar to this:

```ts
export type Bar<T, R> = (foos: Foo<T>[]) => R; // defined elsewhere

export const baz: Bar<string, string> = (foos) => '...';
```

Produced documentation looks like this:

```md

## Functions

### baz

▸ `Const`**baz**(`foos`: [*Foo*](types.md#foo)<string\>[]): *string*
```

The last line renders like this:

▸ `Const`**baz**(`foos`: [*Foo*](types.md#foo)<string\>[]): *string*

Note the absence of whitespace between `Const` and `baz`. (It might not be obvious depending on the styles but it copies as a single word.)

I did a quick look through the tests and it seems that the space is expected between `Const` and a variable name. Perhaps something wrong in this particular situation.

(Not sure what to think about the type `Bar` being expanded in the docs, but at least it's not wrong technically.)

**Comment by tgreyuk** [comment]
Thanks again.. fix in typedoc-plugin-markdown@3.8.0 ..

**Comment by KillyMXI** [comment]
Thank you!

**Comment by tgreyuk** [comment]
hi @KillyMXI 

> (Not sure what to think about the type Bar being expanded in the docs, but at least it's not wrong technically.)

I have actually been looking to reduce clutter with this kind of thing with the output below. Few more details here #229 .

### Bar before

> <img src="https://user-images.githubusercontent.com/11680870/119906503-3e5f9700-bf46-11eb-9d2c-d7eba019e9ad.png" width="370" >

### Bar after
> <img src="https://user-images.githubusercontent.com/11680870/119906379-03f5fa00-bf46-11eb-9143-c5b206338a1f.png" width="300" >

### baz before

> <img src="https://user-images.githubusercontent.com/11680870/119906781-c5147400-bf46-11eb-9f68-8778651fdcb8.png" width="330" >

### baz after

> <img src="https://user-images.githubusercontent.com/11680870/119906776-c0e85680-bf46-11eb-8532-45f4bd742cf0.png" width="220" >

**Comment by KillyMXI** [comment]
Hmm.
What I was referring to is the fact that type alias `Bar` is not present in the `baz` documentation, it is replaced by underlying type instead. But I guess it can't be helped.

Speaking of the proposed changes, they seem nice in general. Less duplication.
My initial reaction was that it might be harder to understand for type aliases specifically.
But I can feel like I'm gradually warming to the idea as I'm internalizing it.
Still, it is a bit marred by the fact there might be no way to describe parameters and return value for type aliases (`@param` and `@returns` don't work there as expected, iirc). One-liner type declaration might be a meaningful option to have.

Btw, here there are [type aliases](https://github.com/mxxii/selderee/blob/main/packages/selderee/src/Types.ts) and corresponding [markdown docs](https://github.com/mxxii/selderee/blob/main/docs/modules/selderee_src_selderee.types.md) from the project that motivated this issue.

**Comment by tgreyuk** [comment]
Yes maybe it would be better to keep the one-liner type declarations for your use cases. I think will go for more subtle changes at this stage. Thanks again - very useful to have some feedback.
