### ISSUE TITLE
typedoc-github-wiki-theme - "is not a recognised markdown theme."

### ISSUE THREAD

**Issue by Extend-Apps** [tgreyuk/typedoc-plugin-markdown#226]
Warning: [typedoc-plugin-markdown] './node_modules/typedoc-gitlab-wiki-theme/dist' is not a recognised markdown theme. If an html theme is required, please disable this plugin.

**Comment by tgreyuk** [comment]
closing this assuming that the theme hasn't been installed. Please re-open if issue persists.

**Comment by cyberwombat** [comment]
@tgreyuk I am experiencing same issue. I can see the theme in my node_modules.  I have:
```
 "typedoc-github-wiki-theme": "^1.0.0",
 "typedoc-plugin-markdown": "^3.11.9",
```
I am running in a Yarn monorepo so not sure if thats the issue. I have tired passing a variety of theme paths such as:
```
--theme ../node_modules/typedoc-github-wiki-theme/dist/"
--theme ./Users/Me/Sample/node_modules/typedoc-github-wiki-theme/dist/"
--theme .typedoc-github-wiki-theme"
--theme .typedoc-github-wiki"
and so on...
```

**Comment by cyberwombat** [comment]
@tgreyuk  so Ive added some debug lines and got the proper path. its finding the theme but throwing error in `getCustomTheme` with:
```
TypeError: Class extends value undefined is not a constructor or null
```

**Comment by costlydeveloper** [comment]
Same here, I can't make it work, I don't see why this wouldn't work. What am I doing wrong?

![image](https://user-images.githubusercontent.com/55545296/149666349-66e0f2c6-4782-447e-a307-b97e06229f5a.png)

installed:
![image](https://user-images.githubusercontent.com/55545296/149666371-1b846f3f-7065-4941-911d-7bcecbc4146f.png)

this is the command:

> npx typedoc --plugin typedoc-plugin-markdown --theme github-wiki
