### ISSUE TITLE
escapeString in typedoc-plugin-markdown doesn't escape leading quotes

### ISSUE THREAD

**Issue by noiach** [tgreyuk/typedoc-plugin-markdown#228]
https://github.com/tgreyuk/typedoc-plugin-markdown/blob/e6046b0aa1779fb316fa2448457aa468569c38e5/packages/typedoc-plugin-markdown/src/utils/front-matter.ts#L47

By checking that the quote doesn't already follow an escape, it misses double quotes at the start of the string.

In `docusaurus-plugin-typedoc`, this can cause issues with the sidebar label:

```yaml
sidebar_label: ""library-name\""
```

which causes the error

```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 5, column 16:
    custom_edit_url: null
```

**Comment by tgreyuk** [comment]
thanks - fix in 3.8.2
