### ISSUE TITLE
Remove README.md and further customization

### ISSUE THREAD

**Issue by fgatti675** [tgreyuk/typedoc-plugin-markdown#232]
So I have a few docs written already, plus a README.md that makes sense as an introduction to anyone reaching the repository.
I would like to have the API documentation in a second main navigation tab (not included under Docs, but under API in the top bar)
The problem is, the README.md file is set automatically and I would like to remove it. 
Also,  my library exports some functions and some React components. All the documentation gets bundled under Functions (I have found the `allReflectionsHaveOwnDocument` flag).
Would this be possible?
Reorganising this manually doesn't make sense to me since I have hundreds of components.
Thanks!

**Comment by tgreyuk** [comment]
Hello,

- If you don't want to include your project readme then `readme=none` will omit generation.
- I am not 100% sure what you are trying to do with the function organisation. If you don't want everything bundled in the same place then you can put them into separate entrypoints/modules?

Apologies if I have misunderstood what you are trying to do. Any  examples would be useful.

**Comment by yiliansource** [comment]
> If you don't want to include your project readme then readme=none will omit generation.

Out of curiosity, where is this documented?

**Comment by tgreyuk** [comment]
It is a standard TypeDoc option https://typedoc.org/guides/options/#readme. Could probably make reference to the TypeDoc options more explicit in the readme. Most TypeDoc options will work apart from those linked with the html theme.

**Comment by tgreyuk** [comment]
closing issue - please do re-open if there is a specific problem.
