### ISSUE TITLE
Definition of union types breaks markdown table

### ISSUE THREAD

**Issue by java-james** [tgreyuk/typedoc-plugin-markdown#233]
## Description

When documentation is generated for a union type eg. `type stringOrNumberUnionType = string | number;`
The markdown reads the "|" as an edge of a table. Breaking the display and cutting the table short.

I can see an escape attempt is added but it appears to not work in this case.

## Expected
Character is escaped and markdown table is rendered with all columns =

## Actual
Missing column due to union creating a new column
```
| `someObject.someFn` | () => `Promise`<string \| number\> | Does something cool |
```
renders:
<img width="992" alt="Screen Shot 2021-06-10 at 4 55 08 PM" src="https://user-images.githubusercontent.com/22756998/121467096-9f8a6e80-ca0c-11eb-82df-7ec59f86c828.png">

**Comment by tgreyuk** [comment]
Interesting - the markdown looks correct but the escape is being ignored. Can I ask what markdown platform this is being rendered on?

**Comment by java-james** [comment]
This is rendered in intelliJ markdown preview plane. Hah yep looks like an issue with intelliJ. Will raise this with them. Happy to close.

Thanks !
