### ISSUE TITLE
Compatibility with typedoc@0.21.0

### ISSUE THREAD

**Issue by ilyub** [tgreyuk/typedoc-plugin-markdown#235]
After upgrading typedoc to 0.21.0, typedoc-plugin-markdown stopped to generate any documentation.
With 0.21.0-beta.2 version plugin works well.
However, with 0.21.0-beta.3 and later it does not generate anything.
If I uninstall plugin, typedoc generates html documentation.
Let me know if this typedoc issue rather than plugin issue.

Also, I am getting the following warnings:
"... uses deprecated structure. Plugins should export a "load" function to be called with the Application"
"Logger.write is deprecated, prefer Logger.info"

**Comment by tgreyuk** [comment]
Hello. Thanks.. I will release a 0.21.0 compatible version shortly.

**Comment by tgreyuk** [comment]
Please try with:
- docusaurus-plugin-typedoc@0.15.0
- typedoc-plugin-markdown@3.10.0

**Comment by ilyub** [comment]
Hi,

Thx for the fixes.

Warnings disappeared.

As for missing output the reason was that I have typedoc config A that extends config B, and config B contains:
"out": "docs"
So, now docs folder is written next to config B.
I fixed this by moving "out": "docs" to config A.

Installing or uninstalling docusaurus-plugin-typedoc does not effect anything.

**Comment by tgreyuk** [comment]
Is your config on a public repo by any chance?

**Comment by ilyub** [comment]
https://github.com/ilyub/typescript-functions/blob/master/typedoc.json
https://github.com/ilyub/shared-config/blob/master/src/base.typedoc.json

Fixed by moving "out" to main config:
https://github.com/ilyub/typescript-functions/blob/develop/typedoc.json
https://github.com/ilyub/shared-config/blob/develop/src/base.typedoc.json

**Comment by tgreyuk** [comment]
I see - actually this is not something the plugin controls.. However if you omitted the `out` option from the configs then I think it will default to `docs` folder relative to each main config.

I am going to close this one. Please raise anything else you find.

Many thanks...
