### ISSUE TITLE
some files are empty with typedoc-github-wiki-theme

### ISSUE THREAD

**Issue by lublak** [tgreyuk/typedoc-plugin-markdown#237]
Currently:

```
_Sidebar.md
Exports.md
```

are filled but (without md)

```
Class
Enumeration
Interface
```

are complete empty

**Comment by tgreyuk** [comment]
That is strange - trying to replicate. Is your project on a public repo by any chance? If not, I assume you are using latest version of typedoc / typedoc-plugin-markdown?

**Comment by lublak** [comment]
@tgreyuk yes my repo is public: https://github.com/lublak/pdfdataextract
btw ignore the current wiki. It was without the wiki theme.

**Comment by tgreyuk** [comment]
Assuming that you are using windows, please try with typedoc-github-wiki-theme@0.4.2. There were colons in the filenames that is invalid pattern for windows.

**Comment by lublak** [comment]
@tgreyuk yes i'm using windows. And now it works all fine :) thank you!
