### ISSUE TITLE
typedoc-plugin-markdown: Tried to modify an option value after options have been sealed

### ISSUE THREAD

**Issue by prasadrajandran** [tgreyuk/typedoc-plugin-markdown#241]
**Version information:**
typedoc: 0.21.3
typedoc-plugin-markdown: 3.10.2
node: 14.16.1
typescript: 4.3.5

**Issue:**
I ran `typedoc somefile.ts` and it failed with the following error message:
```
TypeDoc exiting with unexpected error:
Error: Tried to modify an option value after options have been sealed.
```

**Potential cause:**
TypeDoc has introduced a breaking change in their latest release:
https://github.com/TypeStrong/typedoc/releases/tag/v0.21.3

**Temporary fix:**
Downgrading `typedoc` to version `0.21.2` fixed the issue for me.

**Comment by tgreyuk** [comment]
thanks @prasadrajandran  - apologies for delay - fixed in typedoc-plugin-markdown@3.10.3

**Comment by prasadrajandran** [comment]
@tgreyuk thank you! Just updated typedoc-plugin-markdown to 3.10.3 and it's working for me. Closing this.

**Comment by Vinnl** [comment]
Apologies for the delay?! This was fixed in no time, thanks!
