### ISSUE TITLE
Github markdown broken links and duplicated files

### ISSUE THREAD

**Issue by lorenzopicoli** [tgreyuk/typedoc-plugin-markdown#242]
Version information:
typedoc: 0.21.3
typedoc-plugin-markdown: 3.10.2
typedoc-github-wiki-theme: 0.4.3
typescript: 4.1.5

I'd like to know basically what are the limitations of using the github markdown plugin and what is supposed to work and not supposed to work.

I'm having three problems that I can identify:

1- Some links are broken, I believe the broken links are the links that point to files inside a folder. For example, after generating my documentation in the sidebar I see a link like this: `<project-url>/wiki/Module-controllers/OneController`, but when I click it, Github redirects me to `https://raw.githubusercontent.com/wiki/<project>/Module-controllers?token=<some-token>` which returns a 404. I don't know if it's a limitation of Github wikis or a problem with the links generated by this lib. The link in markdown looks like this `../wiki/Module-controllers/OneController`

2- I have a service folder with service files. Each file exports one default class that is that service's class. When I generate the documentation, the file under `Modules-services/OneService` looks like this:
```
### Classes

- [default](../wiki/Class-default)
```

but that link is incorrect because `Class-default` is overwritten by another random service that also exports a default class. I feel like the plugin is taking every default class and overwriting `Class-default`

3- I have models and services that have the same name ie. `services/Account` and `models/Account`. The plugin outputs `Module-models/Account.md` and `Module-services/Account.md`. I think that github wiki doesn't like that I have two files with the same name and even though it shows two pages in the search (see picture) both of them redirect to the same page and I can't see the documentation for the service class

![image](https://user-images.githubusercontent.com/2422968/125520099-22be1931-37a5-4dda-b973-43f36c3f1027.png)

Let me know and I can try to expand on any of these points with screenshots and a more detailed explanation, my project is not open source so I can't share a link

**Comment by tgreyuk** [comment]
@lorenzopicoli Thanks for the detailed description. This github theme is experimental so user feedback is super helpful.

I have made a few tweaks - please try with typedoc-github-wiki-theme@0.5.0 and typedoc-plugin-markdown@3.10.3

**Issue 1**

I can't yet replicate this issue specifically, but I have simplified the sidebar. If you are still experiencing issues then I will investigate further.

**Issue 2/3**

Yes this is a bug whereby symbols with same name are overwriting each other and the wiki requires a flat folder structure.

To fix have refactored to give each page unique name using the full reflection name and introduced the inline page title:

<img width="400" alt="Screenshot 2021-07-13 at 23 09 45" src="https://user-images.githubusercontent.com/11680870/125531765-dcab4d09-bd37-40a6-862d-3bc0b2a16b43.png">

Let us know if this makes sense and if you find anything else.

thanks

**Comment by lorenzopicoli** [comment]
Thank you very much for the quick reply and fix @tgreyuk!

Issue 2 seems to be fixed and now if I check the services folder I see `ServiceName.default` 🎉 . Now for issue number 3 it still happens because github wiki doesn't understand that `/services/Account.md` and `/models/Account.md` are different so I still see two "Account" pages that point to the same place (which I think github just chooses randomly). I think we'd need every file to have a unique name somehow.

I also think I made some progress on issue 1. It looks like all the files are flattened and you can't replicate the folder structure in the URL. What I mean by that is that I found out that if I go to `<project-url>/wiki/controllers/OneController.default` I get redirected to a weird page OR I get a message `Could not find OneController.default` (depends on the link I click), but if I go to `<project-url>/wiki/OneController.default` then I get the correct page. So I think it goes with the previous point that every filename should be unique and then links need to point to `/wiki/<unique-file-name>`. Let me know if this makes sense

PS: Let me know if you want me to open separated issues for each of the above, but I think they're all somewhat linked. I can also try to get a PR for the fixes, but it would take me a while until I have time to sit down and understand the code.

Thank you again for the quick reply

**Comment by tgreyuk** [comment]
Ah! of course some modules will have forward slash in the full name and fs is creating folders. Have replaced the forward slashes with a period which will at least flatten all the files. Trying to generate with forward slash in the actual filename is not going to work in windows. We can refine the filename pattern if need be. I think that will fix point 3 and potentially point 1. Update in github-theme 0.5.1

> PS: Let me know if you want me to open separated issues for each of the above, but I think they're all somewhat linked.

I think it is fine to use this ticket for general tracking these file issues - once we have a good base then can start to refine the issues a bit more.

>  I can also try to get a PR for the fixes, but it would take me a while until I have time to sit down and understand the code.

Yes apologies I need to get round to writing a contributing page and will get onto it at some stage.

**Comment by lorenzopicoli** [comment]
I can confirm that version 0.5.1 fixes all three of the issues I was having. The documentation looks a thousand times better now on github. Thank you for the quick support and fix, this plugin is very helpful!
I'm closing the issue

**Comment by tgreyuk** [comment]
Great - feel free to raise further issues / suggestions!! All the best...
