### ISSUE TITLE
Non-tip LTS support

### ISSUE THREAD

**Issue by betaorbust** [tgreyuk/typedoc-plugin-markdown#243]
Currently, in Node 12<12.20, yarn will throw an error and fail to install because the `engines` section in package.json limits it to >= 12.20. 

Is there a hard requirement for 12.20, or could typedoc-plugin-markdown be relaxed down to 12?

Repro case
```sh
mkdir test && cd test && yarn init -y.  # Set up test package
nvm use 12.19                           # Use < 12.20
yarn add typedoc-plugin-markdown --dev  # install
```
![image](https://user-images.githubusercontent.com/921683/125698494-ff964f0c-25ee-45b1-ab51-5e3771bd1a4d.png)

Thanks!

**Comment by tgreyuk** [comment]
It's not a hard requirement for this plugin and can be relaxed to 12. However it mirrors TypeDoc itself (required peer dependancy) which is set at `>= 12.20` so you will run into the same issue unfortunately.

<img width="853" alt="Screenshot 2021-07-14 at 23 30 15" src="https://user-images.githubusercontent.com/11680870/125701589-ec6db68c-eafb-457f-a396-6315503992ff.png">

You could try the `--ignore-engines` flag maybe.

**Comment by betaorbust** [comment]
Yeah, I opened a [request against typedoc](https://github.com/TypeStrong/typedoc/issues/1628) as well 😆

I can put in a PR to relax it here if that's ok with you. Would you prefer to relax it back to 12, or just remove the engines section in favor of relying on typedoc's enforcement (basically float with whatever they have)?

**Comment by tgreyuk** [comment]
Sure would be happy to accept that pr. I was thinking we could just remove the engines field altogether and just go with typedoc's enforcement.
