### ISSUE TITLE
 Unknown option: --mdEngine

### ISSUE THREAD

**Issue by LoganDark** [tgreyuk/typedoc-plugin-markdown#246]
I am invoking typedoc from the cli like so:

```
npx typedoc --exclude dist --out ./docs --readme none --mode file --theme markdown --mdEngine github
```

I am trying to migrate from typedoc 0.11 and typedoc-plugin-markdown 1.1.23, to typedoc 0.21 and typedoc-plugin-markdown 3.10.4. 

In output I get these errors:

```
Info: Loaded plugin ./node_modules/typedoc-plugin-markdown
Error: Unknown option: --mode
Error: Unknown option: --mdEngine
Error: Unknown option: --mode
Error: Unknown option: --mdEngine
```

and my build does not succeed. How do I fix this?

**Comment by tgreyuk** [comment]
You should be able to run successfully by simply omitting the offending options:

```
npx typedoc --exclude dist --out ./docs --readme none
```

**Comment by LoganDark** [comment]
Huh. So the options that I used to use are now the defaults, or...?

**Comment by tgreyuk** [comment]
- `mode` options was removed in Typedoc 0.20.0 https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0
- `mdEngine` hasn't been supported for a long time - if standard markdown is required no additional options are required
