### ISSUE TITLE
Can't auto-generate a sidebar

### ISSUE THREAD

**Issue by oceanroleplay** [tgreyuk/typedoc-plugin-markdown#251]
### Before recent update

![image](https://user-images.githubusercontent.com/43092101/133652786-96194422-3cdf-41e8-ae0a-786c69631693.png)

### After recent update

![image](https://user-images.githubusercontent.com/43092101/133652913-ff3584da-4158-4d14-a79d-1ecee70c66db.png)

### Config
```ts
plugins: [
    [
      "docusaurus-plugin-typedoc",
      // Plugin / TypeDoc options
      {
        entryPoints: ["../src/index.ts"],
        tsconfig: "../tsconfig.json",
        excludePrivate: true,
        excludeExternals: true,
        excludeProtected: true,
        readme: "none",
      },
    ],
  ],
```

Not sure about the actual issue, please provide a solution. 

Thank you

**Comment by tgreyuk** [comment]
In your `sidebars.js` please replace:

```
API: require('./typedoc-sidebar.js'),
```

with:

```
'API': [
      {
        type: 'autogenerated',
        dirName: 'api', // 'api' is the 'out' directory
      },
    ],
```

I will update the README.

**Comment by oceanroleplay** [comment]
> In your `sidebars.js` please replace:
> 
> ```
> API: require('./typedoc-sidebar.js'),
> ```
> 
> with:
> 
> ```
> 'API': [
>       {
>         type: 'autogenerated',
>         dirName: 'api', // 'api' is the 'out' directory
>       },
>     ],
> ```
> 
> I will update the README.

![image](https://user-images.githubusercontent.com/43092101/133883614-f4cc8734-c70e-4c32-8dc2-eca1d43df347.png)


Sidebar.js
```ts
...
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "api", // 'api' is the 'out' directory
        },
      ],
    },
...
```
## Issue not resolved
It's important to delete old **API** folder before running ``npm run build`` to reproduce this issue.

## Question
is there way to disable ``typedoc-sidebar.js`` file generation?, because that is not required.

**Comment by oceanroleplay** [comment]
## Steps to reproduce issue

1. Execute `git clone https://github.com/oceanroleplay/discord.ts.git`
2. cd docs
3. update all dependencies to latest (`ncu -u`)
4. make necessary changes as per new update in  `docusaurus-plugin-typedoc`
5. Execute `npm run build`
6. Execute `npm run serve`
7. Navigate to ``http://localhost:3001/discord.ts/docs/installation``

## Issue

Sidebar API category is missing (Below is example output of sidebar if correctly build)
![image](https://user-images.githubusercontent.com/43092101/133884192-d91804dd-2487-4ba6-9817-fecefb517da5.png)

**Comment by tgreyuk** [comment]
Thanks i found out what the problem was. fix in `0.16.2`. Have tested on your repo and appears to build fine now. Have also removed sidebar generation but actually that was as a bit of a red herring.

**Comment by tgreyuk** [comment]
Please close if you are happy or let me know if still an issue..

**Comment by oceanroleplay** [comment]
I am testing now, will update in few mins.

**Comment by oceanroleplay** [comment]
@tgreyuk it appear that, docs are building correctly, but sidebar is still not generated.

![image](https://user-images.githubusercontent.com/43092101/133886459-564ea9a7-68e6-40b6-b716-f937a8e9eed6.png)

With sidebar config

```ts
...
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "api", // 'api' is the 'out' directory
        },
      ],
    },
...
```

**Comment by tgreyuk** [comment]
ok thanks - strange - if docs are generated then assume it is some kind of docusaurus config issue. will have a proper look later.

**Comment by oceanroleplay** [comment]
@tgreyuk any ETA for fix? This is holding up the upgrade of dependencies in our project.

**Comment by tgreyuk** [comment]
@oceanroleplay have made a few amends in 0.16.3. Have followed the steps  above and all looks good to me - sidebar is displayed as expected:

<img width="493" alt="Screenshot 2021-09-21 at 22 26 29" src="https://user-images.githubusercontent.com/11680870/134250151-4fbf905b-510a-4ee3-875d-ce2da47dfffd.png">

**Comment by oceanroleplay** [comment]
> @oceanroleplay have made a few amends in 0.16.3. Have followed the steps above and all looks good to me - sidebar is displayed as expected:
> 
> <img alt="Screenshot 2021-09-21 at 22 26 29" width="493" src="https://user-images.githubusercontent.com/11680870/134250151-4fbf905b-510a-4ee3-875d-ce2da47dfffd.png">

Wow, that's wonderful. Maybe I had got something wrong. Now it's working alright.

Thank you for your help and support, closing issue now.
