### ISSUE TITLE
Left angle bracket not escaped, causes parsing error with mdx

### ISSUE THREAD

**Issue by cabljac** [tgreyuk/typedoc-plugin-markdown#252]
Hi!

I am trying to generate docs using an mdx compiler/bundler and `typedoc-plugin-markdown`

I noticed that when a return value is, for example `Promise<void>`, the left angled bracket is not escaped. Related to [this issue](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/141 ) ?

Here's a snippet of what is generated:

```
| Name | Type |
| :------ | :------ |
| `notificationIds?` | `string`[] |

#### Returns

`Promise`<`void`\>
```

**Comment by tgreyuk** [comment]
Hello.. yeah i can't quite remember why it was done like that but most engines don't complain, however I can't think of a reason not to escape the left angle bracket. out of interest what mdx compiler are you using?

**Comment by cabljac** [comment]
I'm using mdx-bundler, which uses xdm (and esbuild) :)

at the moment im doing a replaceAll with some regex as a workaround

**Comment by tgreyuk** [comment]
I did implement but docusaurus then double escapes the character. going to need to think about the best way handle this.

<img width="376" alt="Screenshot 2021-09-23 at 22 25 05" src="https://user-images.githubusercontent.com/11680870/134586281-7ce5d8da-99a9-44ec-9d93-7183f889ad16.png">

**Comment by cabljac** [comment]
The escape i'm currently doing in my code to work around this issue uses a negative lookbehind:

`.replaceAll(/(?<!\\)</g, '\\<');`

so if it has been escaped already, it doesn't try and escape it. I don't know if this helps or is relevant at all

**Comment by tgreyuk** [comment]
Thanks - yeah a negative lookbehind would be the nicest solution here, but as you say would require a fix on docusaurus. still not entirely sure what the 'correct' thing to do here is. Reluctant to complicate things by introducing escaping options.

**Comment by asturur** [comment]
I have the same issue and i m trying to use this with the mdx plugin for gatsby

**Comment by birkskyum** [comment]
@asturur does it help to use v3.17.1 of typedoc-plugin-markdown?

**Comment by tgreyuk** [comment]
> 3.17 didn't, but i m happy to try 3.17.1

@asturur Please do confirm if 3.17.1 fixes or not. If not I will try it with Gatsby to see if I can replicate.

**Comment by asturur** [comment]
My error with 3.17 was some issue with the '#' not sure why.
I ll replicate 3.17 error, post it here, and then inform about 3.17.1
