### ISSUE TITLE
Function and type pages broken when using `allReflectionsHaveOwnDocument`

### ISSUE THREAD

**Issue by ekoleda-codaio** [tgreyuk/typedoc-plugin-markdown#253]
As of the latest release, using the option `allReflectionsHaveOwnDocument: true` results in broken pages for types and functions. They contain only this content:

```
REFLECTION_MEMBER
```

Prior to the last release they were generated correctly.

**Comment by ekoleda-codaio** [comment]
This could also be related to the new typedoc version as well.

**Comment by tgreyuk** [comment]
thanks - fixed in typedoc-plugin-markdown@3.11.1
