### ISSUE TITLE
Insufficient information about references

### ISSUE THREAD

**Issue by KillyMXI** [tgreyuk/typedoc-plugin-markdown#254]
Let's say I have following exports:

```ts
/** ... */
export function foo () {};

export { foo as bar };
```

----

`typedoc` generates html with following contents in the References section:

> **bar**
> Renames and re-exports [foo](#foo)

I wish it just shown that `foo` has an alias `bar`, but it is still usable as is.

----

`typedoc-plugin-markdown` generates following contents in the References section:

```md
### bar

• **bar**: `Object`
```

>### bar
>
> • **bar**: `Object`

This is unusable - reference target is lost.
Is it possible to make it on par with `typedoc` itself?
Or is there a way to remove the References section from the output at least?
It really makes no sense to put it into documentation like this.

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@3.11.3 contains a fix that should make references behave in the same way as the typedoc html theme. To hide completely I think would be responsibility of a custom plugin. Similar request here https://github.com/TypeStrong/typedoc/issues/1271

**Comment by KillyMXI** [comment]
Awesome! It works fine now.
Thank you for a quick fix!
