### ISSUE TITLE
Watch option in Docusaurus plugin crashes (monorepo)

### ISSUE THREAD

**Issue by gpbl** [tgreyuk/typedoc-plugin-markdown#258]
In my monorepo setup I configured the docusaurus plugin with the watch option.  The docusaurus app runs in the `packages/rdp-website` while the library is in `packags/rdp`:

```ts
  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: ['../rdp/src/main.ts'],
        tsconfig: '../rdp/tsconfig.json',
        out: './api',
        watch: true,
      },
    ],
  ],
```

When triggering the first re-render (by changing and saving a file in the `rdp`), it crashes:

```
Info: File change detected. Starting incremental compilation...
Info: Found 0 errors. Watching for file changes.
TypeError: Cannot read property 'getUrls' of undefined
    at Renderer.render (./node_modules/docusaurus-plugin-typedoc/dist/render.js:36:30)
    at Application.generateDocs (./node_modules/typedoc/dist/lib/application.js:259:29)
    at ./node_modules/docusaurus-plugin-typedoc/dist/plugin.js:45:27
    at runSuccess (./node_modules/typedoc/dist/lib/application.js:220:22)
```

The reason is that `this.theme` is `undefined` after a file change:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/9566a9c136fbd8aaa0974219a09076b636bf1cb5/packages/docusaurus-plugin-typedoc/src/render.ts#L28

Note the first run goes smoothly, so something should break while calling `app.convertAndWatch`. Running `typedoc --watch` works. Not sure if the monorepo (or the pnpm) is behind the bug.

Some hint for helping with further investigation?

(PS. Thanks for maintaining this library is really awesome).

**Comment by tgreyuk** [comment]
Thanks. Apologies for delayed response been busy on other stuff. Have fixed the crash in 0.16.4. The sidebar can behave a bit strangely if renaming symbols (which I will look at) but seems ok otherwise.

**Comment by gpbl** [comment]
No need to apologise. That's fantastic - thanks!

**Comment by Ezall2001** [comment]
I am facing a similar problem on:
docusaurus: 3.7.0
typedoc-plugin-markdown: 4.6.0
docusaurus-plugin-typedoc: 1.3.0
I have a somewhat identical monorepo setup as @gpbl
the first run works although, I noted that docusaurs rebuild the entire site ( without this plugin watch mode It only rebuilds the changed file )
on the following runs, the logs stop at 
```
[info] File change detected. Starting incremental compilation...
[info] Found 0 errors. Watching for file changes.
[info] markdown generated at ./src/docs/api 
```
docusaurus-plugin-typedoc still works fine and generates the files in the out dir but docusaurus stops triggering
