### ISSUE TITLE
Accessors comment will merge

### ISSUE THREAD

**Issue by cary-hu** [tgreyuk/typedoc-plugin-markdown#259]
I have getter and setter in my class:
![image](https://user-images.githubusercontent.com/41052104/140291810-3dd10fe1-648e-4bee-a564-b4de3ff075e3.png)
and it render like this :
![image](https://user-images.githubusercontent.com/41052104/140291869-6eaf0802-b1d8-4103-8acb-506593c3cca2.png)

It by design or a bug?

**Comment by tgreyuk** [comment]
Thats an interesting question. I think the modal is returned like this because the html theme displays accessors in a toggle. So it is not really by design. Will need to look at it.

**Comment by cary-hu** [comment]
Getter and setter is the same property, so I think the design for now is right
