### ISSUE TITLE
TypeAlias Property render not correctly 

### ISSUE THREAD

**Issue by cary-hu** [tgreyuk/typedoc-plugin-markdown#260]
I have a typealias like this:
![image](https://user-images.githubusercontent.com/41052104/140292432-c0a5f034-c100-48c3-a5b4-26ade200955f.png)

and the comment of propC is missing:
![image](https://user-images.githubusercontent.com/41052104/140292835-8bd9dd51-aa6d-489d-8001-ed6e7f1fd7c2.png)

but if propC in a class:
![image](https://user-images.githubusercontent.com/41052104/140292710-b1b6ab88-5abd-4d06-ac35-fb7ce8c2cedf.png)

it will render correctly :
![image](https://user-images.githubusercontent.com/41052104/140292746-1d18bf0a-56a1-497a-9403-215ee709ea3f.png)

any idea about this?

**Comment by tgreyuk** [comment]
Thanks - yeah this is a known issue, but actually one for TypeDoc. Please refer to https://github.com/tgreyuk/typedoc-plugin-markdown/issues/207 for background and linked items. Closing this one.
