### ISSUE TITLE
Includes are not being included

### ISSUE THREAD

**Issue by niieani** [tgreyuk/typedoc-plugin-markdown#264]
I've try to debug why this is happening, but it seems this feature was removed during one of the refactors. The tests pass only because the snapshots were updated to pass on incorrect output:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/daa6572f1934c070502d8d3e93aa94631f83c058/packages/typedoc-plugin-markdown/test/specs/__snapshots__/comments.spec.ts.snap#L35-L44

Not adding a reproduction since there's already a test for it in the repo.

My understanding is that [this function](https://github.com/TypeStrong/typedoc/blob/595767567ffc1e06fb3c04db12d645b3e330abdf/src/lib/output/themes/MarkedPlugin.ts#L103) from typedoc's MarkedPlugin ends up not being called.

**Comment by tgreyuk** [comment]
thanks - fix in 3.11.5
