### ISSUE TITLE
Error: The option  hidePageTitle has already been registered 

### ISSUE THREAD

**Issue by leetcoder-hero** [tgreyuk/typedoc-plugin-markdown#266]
Error: The option hidePageTitle has already been registered
Error: The option hideBreadcrumbs has already been registered
Error: The option publicPath has already been registered
Error: The option namedAnchors has already been registered
Error: The option allReflectionsHaveOwnDocument has already been registered
Error: The option filenameSeparator has already been registered
Error: The option entryDocument has already been registered
Error: The option hideInPageTOC has already been registered
Error: The option indexTitle has already been registered

"typedoc": "0.22.9",
 "typedoc-plugin-markdown": "3.11.5",

**Comment by tgreyuk** [comment]
It seems the plugin in trying to load again, but I am not sure of the context from this. Do you have any more info about your config?
