### ISSUE TITLE
Promises that return an object

### ISSUE THREAD

**Issue by roaringUnicorn** [tgreyuk/typedoc-plugin-markdown#268]
In case a promise resolves in an object, the plugin will not render a full object description, but will only show `Object`
Repro case: https://github.com/roaringUnicorn/typedoc-plugin-markdown-repro

## Without the plugin
```
Returns Promise<{ data: string; id: string }>
```

## With typedoc-plugin-markdown plugin
```
`Promise`<`Object`\>
```

**Comment by arantes555** [comment]
I am also seeing the same behavior. Also, when a function returns an Object, there is a weird `>}` after the return type:

<img width="173" alt="image" src="https://user-images.githubusercontent.com/99662/142666145-3f2fea35-ef2b-4829-a84e-abb6ff92524c.png">

**Comment by tgreyuk** [comment]
@roaringUnicorn thanks for test repo. please try typedoc-plugin-markdown@3.11.7

<img width="523" alt="Screenshot 2021-11-20 at 10 08 45" src="https://user-images.githubusercontent.com/11680870/142722565-48ef3963-3a61-4392-95a3-f1c97e2a1c49.png">

**Comment by roaringUnicorn** [comment]
Works fine, thanks for the quick fix !
