### ISSUE TITLE
typedoc-gitlab-wiki-theme `getRelativeUrl` returns broken relative URLs

### ISSUE THREAD

**Issue by bever1337** [tgreyuk/typedoc-plugin-markdown#269]
Great plugin, this is a huge time-saver for generating docs for a gitlab project wiki. I'm new to typedoc, so this is guaranteed to be a clumsy ticket. I appreciate any clarification that folks can add.

When generating a gitlab-wiki compliant docs, I found that relative linking between resources -- example from a module to an interface -- was broken. In my experience, the sidebar and table of contents functioned as expected. The result is that users will navigate via a ToC or `_sidebar.md` to a relevant doc page, and then the links from that page will be broken. In gitlab wiki, a broken URL prompts the user to create a new page. For this use-case, that is undesirable because the docs do exist and they are auto-generated.

`getRelativeUrl` prepends `./` to every absolute URL provided. This is only appropriate from the wiki "root", likely `home.md` or `_sidebar.md`. My fix in the PR calls `getRelativeUrl` on super before prepending `./`.

Example config:
```
{
  "entryPoints": [
    "./lib/foo/bar.ts",
    "./lib/foo/baz.ts",
    "./lib/foo/types"
  ],
  "entryPointStrategy": "expand",
  "excludeInternal": true,
  "out": "docs",
  "theme": "./node_modules/typedoc-gitlab-wiki-theme/dist"
}
```

Dependencies installed:
```
    "typedoc": "^0.22.9",
    "typedoc-gitlab-wiki-theme": "^0.2.0",
    "typedoc-plugin-markdown": "^3.11.6"
```

Edit: I re-wrote this ticket because the first draft was hard to understand

**Comment by tgreyuk** [comment]
thanks @bever1337 ... fix in typedoc-wiki-theme@0.2.1
