### ISSUE TITLE
[docusaurus-plugin-typedoc] Incorrect plugin definition

### ISSUE THREAD

**Issue by timocov** [tgreyuk/typedoc-plugin-markdown#271]
According to [docusaurus types](https://github.com/facebook/docusaurus/blob/40e4ce0e68223346abe3b1be2f4ed0efe24f3846/packages/docusaurus-types/src/index.d.ts#L312) a plugin's module should be a function (with optional properties), but a function which returns a result _synchronously_. But in [`docusaurus-plugin-typedoc` plugin's code](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/eb289daac347deea984351f04ec7d5f82896d281/packages/docusaurus-plugin-typedoc/src/plugin.ts#L12-L15
) this function is asynchronous, what could cause some interesting issues like when a plugin couldn't generate all files in time and docusaurus will ignore them.

For now it seems that it works fine in trivial cases, but I believe it might break anytime and most likely you won't be noticed about that.

It seems that the simplest solution could be moving [at least this code](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/eb289daac347deea984351f04ec7d5f82896d281/packages/docusaurus-plugin-typedoc/src/plugin.ts#L42-L48) inside `loadContent` function of returned plugin so docusaurus will wait until all work is done and only after that will continue.

**Comment by slorber** [comment]
Hey, good catch

We don't support async plugin inits but we definitively want to in the future (even our core plugins need this in a few places)

Surprised that current code works though 🤷‍♂️

**Comment by tgreyuk** [comment]
thanks @timocov .. I can't quite remember why it was implemented that way originally but i think it was to do with some odd race conditions .However everything seems to work using the 'correct' implementation as per your suggestion.

**Comment by timocov** [comment]
@tgreyuk It seems that it should be fixed in the latest version according to the changelog so we can close the issue now?
