### ISSUE TITLE
[typedoc-plugin-markdown] Inconsistent URLs cause 404 on Github

### ISSUE THREAD

**Issue by daidodo** [tgreyuk/typedoc-plugin-markdown#278]
Hi, thanks very much for your great work!
But I'm having a problem. I'm using `typedoc-plugin-markdown` to generate API docs for my project [format-imports](https://github.com/daidodo/format-imports):

_package.json_:

```
    "typedoc": "^0.22.10",
    "typedoc-plugin-markdown": "^3.11.7"
```

_tsconfig.json_:

```
  "typedocOptions": {
    "entryPoints": ["src/lib/index.ts"],
    "hideInPageTOC": true,
    "hideBreadcrumbs": true,
    "readme": "none",
    "name": "APIs Documentation",
    "excludeInternal": true
  }
```

Recently, I found that some URLs generated don't work. For example, the `Configuration` link in [docs/README.md](https://github.com/daidodo/format-imports/blob/main/docs/README.md#interfaces) is broken because of the capital C:

[https://github.com/daidodo/format-imports/blob/main/docs/interfaces/<ins>C</ins>onfiguration.md](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/Configuration.md)

Interestingly, in [another part of the same file](https://github.com/daidodo/format-imports/blob/main/docs/README.md#default_merger), the `exclude` link is fine with lower-case c:

[https://github.com/daidodo/format-imports/blob/main/docs/interfaces/<ins>c</ins>onfiguration.md#exclude](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#exclude)

Could you help me fix it?
Thanks again!

**Comment by tgreyuk** [comment]
hi @daidodo .. for some reason your build is exporting with lowercase filenames but the expectation is the filenames are titlecase. I am not sure why in your use-case -  I assume you are running on a standard OS? I guess we could force all filenames to lowercase which will internally fix the links.

**Comment by daidodo** [comment]
Thanks for the response!
I'm on Mac OS with a case-insensitive file system. I didn't do extra config except the ones posted. I think the inconsistency of links as well as filename might be a general problem.

**Comment by KillyMXI** [comment]
I had a similar issue recently.
It is partly an upstream issue, partly a git/GitHub quirk.

typedoc changed the way it names the documentation files, but GitHub sticks to the original case.

I think typedoc should have provided a way to specify the file naming rules (mapping to kebab or snake case to make safer URIs for example) but that's not what matters for this issue.

**The solution is to delete your generated docs in one commit and add them back in another one.** This way GitHub will see the new correct filenames.

The same issue can happen any time you change case for file names in your repositories. typedoc just made the change without a warning.

I don't believe there is anything to do in `typedoc-plugin-markdown`.

**Comment by daidodo** [comment]
@KillyMXI 
I tried your way but still got problem. Now the file names are in Camel case so [C</ins>onfiguration.md](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/Configuration.md) works but not [<ins>c</ins>onfiguration.md#exclude](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#exclude).

@tgreyuk: Still I think it's an issue for either this plugin or typedoc.

**Comment by KillyMXI** [comment]
@daidodo You have your links written manually in tsdoc comment https://github.com/daidodo/format-imports/blob/e4d76c8/src/lib/config/merge.ts#L12-L24
These are no longer valid and you'd have to update them manually as well.

But you should not use markdown links to cross-link between parts of your code.
There is https://tsdoc.org/pages/tags/link/ for that.

**Comment by daidodo** [comment]
Thanks @KillyMXI for pointing out the issue!

Resolving this as my issue has been solved.
