### ISSUE TITLE
[typedoc-plugin-markdown] Doesn't work with TypeDoc watch mode

### ISSUE THREAD

**Issue by wilcoxmd** [tgreyuk/typedoc-plugin-markdown#279]
## Problem

When using TypeDoc's watch mode with `typedoc-plugin-markdown`, markdown files are correctly created on the first generation, but subsequent file saves overwrite the markdown with HTML files. 

## Steps to reproduce

See https://github.com/wilcoxmd/typedoc-watch-plugin-repro

## Environment

Typedoc version: 0.22.10
typedoc-plugin-markdown version: 3.11.8
TypeScript version: 4.5.2
Node.js version: 16.13.0
OS: macOS Monterey (12.0.1)

## Related

I originally opened this as [an issue in TypeDoc](https://github.com/TypeStrong/typedoc/issues/1827), where the problem [was traced](https://github.com/TypeStrong/typedoc/issues/1827#issuecomment-1003837425) to this plugin.

**Comment by tgreyuk** [comment]
thanks - have put in a fix for this in typedoc-plugin-markdown@3.11.9, but need to revisit the theme implementation in general at some stage.

**Comment by wilcoxmd** [comment]
Thank you! It looks like this fixes things for us!
