### ISSUE TITLE
Missing description for function-type properties

### ISSUE THREAD

**Issue by KillyMXI** [tgreyuk/typedoc-plugin-markdown#281]
Minimal type declaration:

```typescript
export type Foo = {
  /**
   * Bar1
   */
  bar1: () => string,
  /**
   * Bar2
   */
  bar2: (() => string),
  /**
   * Baz
   */
  baz: true | (() => string)
}
```

Expected markdown:

```markdown
| Name | Type | Description |
| :------ | :------ | :------ |
| `bar1` | () => `string` | Bar1 |
| `bar2` | () => `string` | Bar2 |
| `baz` | ``true`` \| () => `string` | Baz |
```

Actual markdown:

```markdown
| Name | Type | Description |
| :------ | :------ | :------ |
| `bar2` | () => `string` | - |
| `baz` | ``true`` \| () => `string` | Baz |
| `bar1` | () => `string` | - |
```

- ~~bar1 moved to the last row. Typedoc considers only this type declaration as a function;~~
- bar1 and bar2 both missing their descriptions. This is specific to `typedoc-plugin-markdown` and is a serious issue.

Typedoc HTML text:

```
* bar2: () => string
(): string
Bar2

Returns string

* baz: true | (() => string)
Baz

* bar1:function
bar1(): string
Bar1

Returns string
```
- not ideal but at least no description is missing.

**Comment by KillyMXI** [comment]
Version 3.11.10 half-fixed it:

```
| Name | Type | Description |
| :------ | :------ | :------ |
| `bar2` | () => `string` | - |
| `baz` | ``true`` \| () => `string` | Baz |
| `bar1` | () => `string` | Bar1 |
```

**Comment by tgreyuk** [comment]
@KillyMXI thanks for feedback. strange because i am seeing the following:

```
| Name | Type | Description |
| :------ | :------ | :------ |
| `baz` | ``true`` \| () => `string` | Baz |
| `bar1` | () => `string` | Bar1 |
| `bar2` | () => `string` | Bar2 |
```

Is your code on a public repo by any chance?

**Comment by KillyMXI** [comment]
Not public yet. I would've stumbled over this issue before publishing either way.

Typedoc version is 0.22.10. I've also tried 0.22.7 (just chosen randomly), with no observed difference.
Node version is 12.22.6.

**Comment by tgreyuk** [comment]
Ok i worked out why there was a discrepancy - prettier removed surrounding parenthesis. Please try typedoc-plugin-markdown@3.11.11

**Comment by KillyMXI** [comment]
Haha. I don't like prettier for different reasons, but here is an example when something is not an equivalent transformation from different systems point of view.

It should probably be a concern for typedoc. But I think I'm going to make use of it (to have all keys alphabetically sorted) rather than report it :)

I confirm version 3.11.11 is working, produces following result:

```
| Name | Type | Description |
| :------ | :------ | :------ |
| `bar2` | () => `string` | Bar2 |
| `baz` | ``true`` \| () => `string` | Baz |
| `bar1` | () => `string` | Bar1 |
```

Thank you!
