### ISSUE TITLE
GitHub wiki generates <internal> blank sidebar menu entries

### ISSUE THREAD

**Issue by cyberwombat** [tgreyuk/typedoc-plugin-markdown#282]
I am using the GH wiki theme and the sidebar generates things like:
```
### Namespaces

- [<internal>](../wiki/@foo.core.%3Cinternal%3E)
- [<internal>](../wiki/@foo.core.%3Cinternal%3E)
- [<internal>](../wiki/@foo.core.%3Cinternal%3E)
- [<internal>](../wiki/@foo.core.%3Cinternal%3E)
- [<internal>](../wiki/@foo.core.%3Cinternal%3E)
```

I even have `excludeInternals: true` as an option but it still happens. The links work but there is no menu entry since its a blank html tag. Am not sure if this is a bug or something I made a mistake on but my searches came up empty.

Config:
```
{
  "name": "SDK Documentation",
  "excludeInternal": true,
  "out": "docs",
  "plugin": [
    "typedoc-plugin-markdown",
    "typedoc-github-wiki-theme",
    "typedoc-plugin-missing-exports"
  ],
  "theme": "github-wiki"
}
```

Packages:
```
 "typedoc": "^0.22.10",
 "typedoc-github-wiki-theme": "^1.0.0",
 "typedoc-plugin-markdown": "^3.11.11",
 "typedoc-plugin-missing-exports": "^0.22.6",
 "typescript": "^4.4.2"
```

**Comment by tgreyuk** [comment]
The plugin `typedoc-plugin-missing-exports` is putting types that are referenced (but not exported),  into an internal namespace called `<internal>`. The angle brackets in the name is an issue for this theme. I notice the plugin usefully exposes an additional option `internalNamespace` which I think might fix your issue?

```
internalNamespace: 'ApiInternals'
```

**Comment by tgreyuk** [comment]
Workaround provided - closing..
