### ISSUE TITLE
Build broken after typedoc upgrade

### ISSUE THREAD

**Issue by B4nan** [tgreyuk/typedoc-plugin-markdown#284]
Seems like the build is broken again after yesterdays typedoc upgrade. It was upgrade from 0.22.10 to 0.22.11. There is a note about `qualifiedName` in the [release notes](https://github.com/TypeStrong/typedoc/releases/tag/v0.22.11).

```
[INFO] Deploy command invoked...
[INFO] organizationName: mikro-orm
[INFO] projectName: mikro-orm
[INFO] deploymentBranch: gh-pages
[INFO] Remote repo URL: ***github.com/mikro-orm/mikro-orm.git
7bd70784dc298b6f24b55d704f97d3eafc838a0c
[INFO] `git rev-parse HEAD` code: 0
[INFO] [en] Creating an optimized production build...
Error:  Unable to build website for locale en.
Error:  Cannot read properties of undefined (reading 'qualifiedName')
error Command failed with exit code 1.
```

https://github.com/mikro-orm/mikro-orm/runs/4850848937?check_suite_focus=true

Let me know if you need additional debugging from my end.

**Comment by tgreyuk** [comment]
Can you upgrade to typedoc-plugin-markdown@3.11.12 (if you haven't already)? thanks.

**Comment by B4nan** [comment]
Will do in a sec, indeed I am on the previous version.

(sorry that I haven't checked this, weird that renovate didnt upgrade this - I do have auto branch merge configured, so I should be up to date or get a PR, but non happened 🤷 )

**Comment by B4nan** [comment]
Yeah, works. Thanks and sorry for the noise! (now I even see the previous issue about the same error 🤦 )
