### ISSUE TITLE
Module not found and Typescript error raised.

### ISSUE THREAD

**Issue by janaSunrise** [tgreyuk/typedoc-plugin-markdown#285]
I'm trying to build a docusaurus project with autogenerated API documentation, but weirdly it's not working.

This is the error I'm getting,
![Screenshot from 2022-01-19 23-10-28](https://user-images.githubusercontent.com/56873669/150185091-50ebcf1d-fac8-42ce-a1cd-b321c3a56fc6.png)

The reproducible code can be found [here](https://github.com/PrasoonPratham/nftlabs-sdk-ts).

We build the project as so,
```sh
cd docs
yarn
yarn start
```
And, this doesn't build the auto-documentation and throws the error.

I'm confused why this is happening, Mind helping us out with this?

Regards.

**Comment by tgreyuk** [comment]
these are typescript compilation errors unrelated to the plugin. by the looks of things there are quite a few missing dependencies that are not getting resolved,

**Comment by janaSunrise** [comment]
I have 2 different `node_modules`, one in the `docs/` subdirectory, another in the root. When I first setup the project, it worked fine, but when I pushed and cloned with a clean install, it ceased to work. I'm not sure how/what this is happening weirdly. Although the library compiles fine too, these errors are a first-timer.

**Comment by tgreyuk** [comment]
Closing as not related to plugin.
