### ISSUE TITLE
Pipe character is not escaped in type description

### ISSUE THREAD

**Issue by roaringUnicorn** [tgreyuk/typedoc-plugin-markdown#286]
Repro case https://github.com/roaringUnicorn/typedoc-plugin-markdown-repro

# Type definition
```
export type ApiResponse = {
    /**
     This pipe will not be escaped: { 'dataIDs': 'ok'|'ko' }
     */
    dataIDs: { [dataId: string]: 'ok' | 'ko' }
    /**
     * This will be fine: { 'itemIDs': 'ok'\| 'ko' }
     */
    itemIDs: { [itemId: string]: 'ok' | 'ko' }
    /**
     * An ugly solution:  { 'userIDs': 'ok' &#124; 'ko' }
     */
    userIDs: { [userId: string]: 'ok' | 'ko' }
}
```

# Generated markdown
The generated markdown:

```
| Name | Type | Description |
| :------ | :------ | :------ |
| `dataIDs` | `Object` | This pipe will not be escaped: { 'dataIDs': 'ok'|'ko' } |
| `itemIDs` | `Object` | This will be fine: { 'itemIDs': 'ok'\| 'ko' } |
| `userIDs` | `Object` | An ugly solution:  { 'userIDs': 'ok' &#124; 'ko' } |
```

# Problem
The `|` char in `dataIDs` description is not escaped. The two next rows are shown correctly.
The `|` character is interpreted as the end of the row in the table
![image](https://user-images.githubusercontent.com/27486082/150365434-1dd660bd-38f5-433e-97ae-736bbe0ad285.png)

**Comment by tgreyuk** [comment]
Sure will have a look at escaping pipes inside comments here. Actually you have highlighted the fact the the there is no object detail - should be something like this i think...

<img width="568" alt="Screenshot 2022-01-20 at 22 34 14" src="https://user-images.githubusercontent.com/11680870/150433317-94fefa3b-bb50-4012-939e-14d504d98f49.png">

**Comment by arantes555** [comment]
Hello @tgreyuk ! Is there any progress on this ?

**Comment by tgreyuk** [comment]
Pipes will now be escaped in typedoc-plugin-markdown@3.11.13 . Note that `'ok'\| 'ko'` will now get double escaped so will be broken).

@arantes555 have also expanded objects as per example.
