### ISSUE TITLE
Fails to create dist/api in github workflow, but not locally

### ISSUE THREAD

**Issue by Lusito** [tgreyuk/typedoc-plugin-markdown#290]
I've recently updated and since then github workflows don't create the folder `./docs/.vuepress/dist/api` anymore.

Not sure why, since it works fine when I do it locally with exactly the same versions.

I've narrowed it down to two packages and versions
Last working versions:
```json
    "typedoc-plugin-markdown": "3.11.9",
    "vuepress-plugin-typedoc": "0.10.1"
```

These versions have the issue:
```
    "typedoc-plugin-markdown": "3.11.10",
    "vuepress-plugin-typedoc": "0.10.2"
```

I can't update one without the other. Either npm complains about versions not matching or it tries to access getUrls on undefined.

Any idea what might be happening here?

Github Workflow is using 'ubuntu-latest', while I'm on a manjaro system.

**Comment by tgreyuk** [comment]
please try with vuepress-plugin-typedoc@0.10.3 - this should behave same way as before. It seems moving logic into lifecyle method caused issue (but not too sure why)..

**Comment by Lusito** [comment]
Thanks, that was quick. It works!
