### ISSUE TITLE
Bug: Docs markdown link couldn't be resolved

### ISSUE THREAD

**Issue by oceanroleplay** [tgreyuk/typedoc-plugin-markdown#291]
Since last two updates, docs are failing. Below is screenshot of error and reference to view full logs.

![image](https://user-images.githubusercontent.com/43092101/152634704-d9f0fdab-4df0-4ed5-921c-7d09cfb71281.png)

[Full logs](https://github.com/oceanroleplay/discord.ts/runs/5076692565?check_suite_focus=true)

**Comment by tgreyuk** [comment]
Can you please try with docusaurus-plugin-typedoc@0.16.9 . There was a recent change to paths that I think must have caused this. Can you please confirm if the rollback fixes your issue?

**Comment by oceanroleplay** [comment]
> Can you please try with docusaurus-plugin-typedoc@0.16.9 . There was a recent change to paths that I think must have caused this. Can you please confirm if the rollback fixes your issue?

yes. Thank you ❤️

**Comment by oceanroleplay** [comment]
> @oceanroleplay just a heads up if you update to 0.17 at some stage you will need to set `includeExtension:false` as we now include extension as default - #293 . sorry about inconvenience but it seems that either switching on or off is breaking change depending on setup. it seems the recommendation is to preserve the extension though which is why that has been adopted as the default.

I have updated the dependencies, no configuration was needed. Thanks though, I will keep this in mind for the future.
