### ISSUE TITLE
Object details in type description is not escaped

### ISSUE THREAD

**Issue by arantes555** [tgreyuk/typedoc-plugin-markdown#292]
Introduced in https://github.com/tgreyuk/typedoc-plugin-markdown/issues/286#issuecomment-1017989092

typedoc-plugin-markdown now puts object details in type description tables. The problem is with objects of the form : 

> { [id: string]: ``"ok"`` \| ``"ko"``;  }

The `[id: string]` part is interpreted as a link by some markdown parsers (examples : WebStorm, and check-md : https://github.com/whxaxes/check-md).

Solution: wrap it in backquotes:

> { `[id: string]`: ``"ok"`` \| ``"ko"``;  }

(plus, it seems more coherent to me, as most other types and variable names are in backquotes)

**Comment by tgreyuk** [comment]
fix in typedoc-plugin-markdown@3.11.14

**Comment by arantes555** [comment]
@tgreyuk as always, thank you for your amazing reactivity! Hat's off to you 🎩
