### ISSUE TITLE
[docusaurus-plugin-typedoc] Provide a way to disable pagination on generated pages

### ISSUE THREAD

**Issue by timocov** [tgreyuk/typedoc-plugin-markdown#294]
It seems that [there is no way disable a pagination](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/a83de1b4c69a8a8f02dc8fde20156cd0f96f6468/packages/docusaurus-plugin-typedoc/src/theme.ts#L90-L115) on generated pages. Sometimes it makes no sense to have a pagination buttons on generated pages because they aren't directly related to each other.

![image](https://user-images.githubusercontent.com/3112183/154678438-ef216c99-0f29-4535-8493-a6aa43fda9ba.png)

The pagination could be disabled by proving 2 options with `null` values:
- [pagination_next](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#pagination_next)
- [pagination_prev](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#pagination_prev)

**Comment by tgreyuk** [comment]
Yeah good point - i guess we could just provide an option to pass any additional global frontmatter options as required.

**Comment by tgreyuk** [comment]
docusaurus-plugin-typedoc@0.17.0

You can now pass whatever frontmatter config you want into `frontmatter` option:

https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc#frontmatter

**Comment by timocov** [comment]
Many thanks @tgreyuk!
