### ISSUE TITLE
Feature: Add command to generate markdown files for docusaurus

### ISSUE THREAD

**Issue by edgardmessias** [tgreyuk/typedoc-plugin-markdown#298]
Hi, I would like to create a docusaurus command to generate the markdown files only.
Internally I did that, but the objective of this issue is to improve the options before making a PR.

I have a scenario that I put the markdown files on GitHub and I create a workflow to publish after pushes to main.
There are some externals repositories that I would like to generate new markdown files when I release a new version, and using a special command, I can geneate the new markdown files and send to docusaurus site.

Command suggestion: `npx docusaurus typedoc [args] <options>`
Suggested options:
* `[args]` optional, but I can pass the IDs that I would like to run
* `--watch`: Set watch mode
* `<some typedoc options>`

Last but not least, I recomend to create a plugin option to "disable" while I am using `docusaurus start/build`, but still avaiable to run from command

**Comment by tgreyuk** [comment]
Sorry - this is old but it is possible to do this with cli command `docusaurus generate-typedoc` which will run whatever is in docusaurus.config but will only pusblish typedoc pages.
