### ISSUE TITLE
issue: JavaScript heap out of memory

### ISSUE THREAD

**Issue by oceanroleplay** [tgreyuk/typedoc-plugin-markdown#299]
Hi @tgreyuk 

![image](https://user-images.githubusercontent.com/43092101/157297876-f0c3cc97-5f78-42df-98d3-c3e8066ddb6a.png)

note: tried increasing heap to 4gb, before it was working normally with 2gb also.

Logs and repo: https://github.com/oceanroleplay/discord.ts/runs/5468351342?check_suite_focus=true

Thank you ❤️

**Comment by oceanroleplay** [comment]
Downgrading to typescript 4.5.5, resolve this issue. But I am not sure it's related to docusaurus/typedoc/typedoc-plugin-markdown.

**Comment by tgreyuk** [comment]
@oceanroleplay thanks for update - did initially investigate but was a bit stumped as to how the plugin itself would cause the issue, especially as the last update was quite innocuous. I was going to try and find some time to look at in more detail.

**Comment by oceanroleplay** [comment]
@tgreyuk any updates? I have tried all package updates today and it is still not working. Could you please debug the core issue?

**Comment by oceanroleplay** [comment]
Today I tested different use cases. I have like 11 projects to build so I removed half of them and it's working. Later, tried other half. I assume it's some kind of parallel task from docusaurus. so as per your knowledge, is there any workaround? or can you support multiple projects within this project?

**Comment by tgreyuk** [comment]
Not had time to look into this yet, but i don’t think the solution will be found at plug-in level. This typedoc issue and related threads look like very similar https://github.com/TypeStrong/typedoc/issues/835

**Comment by oceanroleplay** [comment]
that indeed a issue with typedoc, I tried building project with one simple command `typedoc --entryPointStrategy packages .` and it's failing with same error.

**Comment by oceanroleplay** [comment]
![image](https://user-images.githubusercontent.com/43092101/162656812-7f85b086-1eed-4d16-a79f-26d9c15cf1ea.png)
![image](https://user-images.githubusercontent.com/43092101/162656839-e34b9748-cfd7-4ec7-972e-f827e8eabfb1.png)
![image](https://user-images.githubusercontent.com/43092101/162656860-42b81011-4458-40d7-9b06-c156132c9daa.png)

that make sense.
