### ISSUE TITLE
TypeError: Cannot read property 'extendedTypes' of undefined

### ISSUE THREAD

**Issue by faddee** [tgreyuk/typedoc-plugin-markdown#3]
Thanks for a great plugin!
However, I get `TypeError: Cannot read property 'extendedTypes' of undefined` in `dist/theme/helpers/hierachySymbol.js:5:29` with `0.0.12-2`. Works fine with `0.0.11-0`.

**Comment by tgreyuk** [comment]
Thanks will have a look.

**Comment by tgreyuk** [comment]
This error should now be be handled with latest version  (0.0.12). I have been throwing code at this so there maybe a few more glitches.
