### ISSUE TITLE
Add option to preserve casing when generating links

### ISSUE THREAD

**Issue by thorsent** [tgreyuk/typedoc-plugin-markdown#301]
**Request**:
Add a new option `preseveDeclarationCasing` that, if set to true, will not convert declarations to lowercase.

**Rationale**:
typedoc-plugin-markdown automatically sets all id's and links to lowercase. This is in accordance with the spec for id tags, and in general how markdown works, but in so doing the original capitalization of declarations are lost. This is often undesirable when the markdown conversion is an _interim_ step to converting to html (for instance, site generators such as Docusaurus and JSDocs are oriented around markdown as input but ultimately render their output as HTML where originally cased anchors are desirable).

Example, `ListenerParam` as output by Typedoc into html:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/1657084/158213072-f91e91cd-8959-4829-bb2c-92cbb7e6bf8f.png">

Output as `listenerparam`  by markdown plugin:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1657084/158214465-78ae7ba0-4818-40ef-ab3f-03415b92aa70.png">

**Notes**:
This appears to be a trivial change to this one line:
https://github.com/tgreyuk/typedoc-plugin-markdown/blob/master/packages/typedoc-plugin-markdown/src/theme.ts#L162

I did attempt a PR but I found that in order to create a new option for the plugin it was also necessary to make that same change in Typedoc itself because it validates and strongly types all options. That increased the burden of effort for someone who isn't in the groove of working with this project.

This seems problematic if one desires a healthy plugin ecosystem. Perhaps I'm missing a nuance, but if not then I would like to suggest that providing an explicit `any` namespace in config for plugins would lower barriers to plugin development and prevent possible collisions, e.g.

```
   "plugins": {
       "typedoc-plugin-markdown" : {
            "hideBreadcrumbs": false
      }
   }
```

**Comment by tgreyuk** [comment]
Apologies for delay on this been busy on other stuff. Have implemented, just tweaked the option name slightly to `preserveAnchorCasing` to make it a bit more explicit. Available in typedoc-plugin-markdown@3.12.0.

Point noted about the options - what is  missing a contributing guide that will get around to at some point.

**Comment by thorsent** [comment]
Thanks @tgreyuk !!!

**Comment by thorsent** [comment]
As a cookie crumb trail for anyone trying to use `preserveAnchorCasing` with docusaurus, after running typedoc (with this option enabled in your config) you then need to run a process that adds "explicit-id" tags to the markdown that typedoc generated. Docusaurus provides a utility to do this: [`write-heading-ids`](https://docusaurus.io/docs/next/cli#docusaurus-write-heading-ids-sitedir).

Here's the syntax:
`docusaurus write-heading-ids ./your-typedoc-output/* --maintain-case true`

So your package.json might look something like this:

```json
"docs" : "typedoc --options typedoc-markdown.js && docusaurus write-heading-ids ./typedocs/* --maintain-case true && docusaurus start" 
```
