### ISSUE TITLE
Invalid slug generated for Docusaurus when using alternative doc folder

### ISSUE THREAD

**Issue by cyberwombat** [tgreyuk/typedoc-plugin-markdown#302]
I keep Docusarus in one folder (ex: /Stuff/Code/Docusaurus) and markdown docs in an other (ex: /Stuff/Code/Documentation). My config preset looks like:
```js
presets: [
    [
      'classic',
      ({
        docs: {
          path: '../Documentation/pages',
        },
```

Then a typedoc config:
```js
plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: ['...'],
        tsconfig: '...',
        out: 'sdkdocs',
      },
    ],
```

What happens is the generated `index.md` frontmatter looks like:

```markdown
---
id: "index"
title: "sdk"
slug: "/../Documentation/pages/sdkdocs/"   
sidebar_label: "Readme"
sidebar_position: 0
custom_edit_url: null
---
```

As you can see the slug is incorrect and D breaks.  I think it's [here](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/master/packages/docusaurus-plugin-typedoc/src/theme.ts#L175) but not sure what best course of action is.

I am using:
```
"docusaurus-plugin-typedoc": "^0.17.2",
```

**Comment by ToxesFoxes** [comment]
Same issue

**Comment by tgreyuk** [comment]
Actually slug is not required anymore - have removed by default. Can still be manually configured with `indexSlug` option.
