### ISSUE TITLE
Table of contents URL does not work

### ISSUE THREAD

**Issue by S222em** [tgreyuk/typedoc-plugin-markdown#311]
This bug report is for `typedoc-github-wiki-theme`

The table of contents URLs generate with an additional `-1` at the end, causing the link to not work.

- Example: https://github.com/S222em/hue.ts/wiki/Bridge#actions-1
- Should be: https://github.com/S222em/hue.ts/wiki/Bridge#actions

Full example is here https://github.com/S222em/hue.ts/wiki

**Comment by tgreyuk** [comment]
Thanks - try typedoc-github-wiki-theme@1.0.1
