### ISSUE TITLE
VuePress v2 config not working (no output)

### ISSUE THREAD

**Issue by tohagan** [tgreyuk/typedoc-plugin-markdown#313]
I'm attempting to get this nice plugin to work for VuePress v2.  

When I use the config you've documented, VuePress v2 emits a warning on startup that its ignored an "anonymous" plugin.  
The actual message was:  "an anonymous plugin or theme was detected and ignored"

```js
plugins: [
  [
    'vuepress-plugin-typedoc',
    {
      entryPoints: ['../src/index.ts'],
      tsconfig: '../tsconfig.json'
    },
  ],
]
```

I noticed that many of the other v2 plugins use a "name" property on an object .. so I tried using

```js
plugins: [
  {
    name: 'vuepress-plugin-typedoc',

    // Plugin / TypeDoc options
    {
      entryPoints: ['../src/index.ts'],
      tsconfig: '../tsconfig.json'
    },
  }
]
```

... and also ...

```js
plugins: [
  {
    name: 'vuepress-plugin-typedoc',
    entryPoints: ['../src/index.ts'],
    tsconfig: '../tsconfig.json'
  }
]
```

Both of these removed the warning ... but alas still nothing was generated !

So I wondered if perhaps you could update your documentation to show the correct config for both VuePress v1 and **v2**. 
Any other clues about how I could debug / diagnose the fault if one of these configs are correct.

My package.json contains ... 

```json
  "devDependencies": {
    "vuepress": "^2.0.0-beta.43"
  },
  "dependencies": {
    "markdown-it-plantuml": "^1.4.1",
    "typedoc": "^0.22.15",
    "typedoc-plugin-markdown": "^3.12.1",
    "vuepress-plugin-typedoc": "^0.10.3"
  }

```

**Comment by tgreyuk** [comment]
thanks for this - having looked into it seems a new plugin definition is going to be required for v2.

**Comment by tohagan** [comment]
ok cool !  I'll be looking forward to this very much.

**Comment by sleiphur** [comment]
after upgrade vuepress to version 2.0.0-beta.46，
plugin configuration now gave me some errors:

**Comment by lslzl3000** [comment]
looking forward this plugin for VuePress v2

**Comment by tgreyuk** [comment]
VuePress v2 support added in vuepress-plugin-typedoc@0.11.0

```ts
import { defaultTheme } from 'vuepress';
import { typedocPlugin } from 'vuepress-plugin-typedoc/next';

module.exports = {
  theme: defaultTheme({}),
  plugins: [
    typedocPlugin({
      // plugin options
      entryPoints: ['../src/index.ts'],
      tsconfig: '../tsconfig.json',
    }),
  ],
};
```
