### ISSUE TITLE
include additional markdown files

### ISSUE THREAD

**Issue by morriswinkler** [tgreyuk/typedoc-plugin-markdown#314]
iI tried to use 

https://github.com/KnodesCommunity/typedoc-plugins/tree/main/packages/plugin-pages

The theme is not compatible with that plugin, would it be possible to have a similar functionality, 
To include a markdown folder that is copied into the out folder and where links show up in the sidebar?

**Comment by tgreyuk** [comment]
hello -its possible i guess - although its probably more useful for the html themes as similar functionality could be achieved by integrating the output markdown with other static site documentation generators.
