### ISSUE TITLE
docusaurus-plugin-typedoc with javascript and JS Doc

### ISSUE THREAD

**Issue by 201flaviosilva** [tgreyuk/typedoc-plugin-markdown#319]
Hey there,

I'm developing a [simple canvas rendering library](https://github.com/201flaviosilva/Impacto), currently I've documented practically all the code, based on [JS Doc](https://jsdoc.app/) and I want the JS Doc documentation to be with the docusaurus doc :)

There is any way to use the docusaurus-plugin-typedoc with the JavaScript files? (and if it’s possible, how to do that magic?) 😅

**Comment by tgreyuk** [comment]
`--allowJs` in tsconfig
