### ISSUE TITLE
[typedoc-plugin-markdown] Getter produces invalid markdown

### ISSUE THREAD

**Issue by fasttime** [tgreyuk/typedoc-plugin-markdown#320]
Observed this while generating the docs for a declaration with a property getter:

```ts
declare const commands:
{
    get node(): Promise<string>;
};
```

The generated markdown looks like:

```md
## Variables

### commands

• `Const` **commands**: `Object`

#### Type declaration

| Name | Type |
| :------ | :------ |
| ``get` **node**(): `Promise`<`string`\>` | {} |
```

Note the double backtick <code>``</code> before `get`, and I'm not sure about the <code>` | {}</code> part at the end.

What I was expecting here:

```md
| `get` **node**(): `Promise`<`string`\> | `Promise`<`string`\> |
```

or maybe just

```md
| **node** | `Promise`<`string`\> |
```

**Comment by tgreyuk** [comment]
Apologies for delay in response to this. Thanks - Fix in typedoc-plugin-markdown@3.13.2 ..
