### ISSUE TITLE
[typedoc-bitbucket-theme] Theme bitbucket not defined

### ISSUE THREAD

**Issue by ebosveld** [tgreyuk/typedoc-plugin-markdown#321]
I've added TypeDoc, Markdown plugin and Bitbucket theme to my package.json, but when generating the docs I get an error that the theme Bitbucket is not defined. I can't seem to find why this is happening.

Error:
```
> typedoc "--theme" "bitbucket"

Info: Loaded plugin typedoc-plugin-markdown
Error: The theme 'bitbucket' is not defined. The available themes are: default, markdown
Error: Documentation could not be generated due to the errors above.
```

Package.json:
```
"typedoc": "^0.22.17",
"typedoc-bitbucket-theme": "^1.0.0",
"typedoc-plugin-markdown": "^3.12.1",
```

**Comment by Gerrit0** [comment]
It sounds like you have a set of plugins to load specified in one of your config files, but don't have `typedoc-bitbucket-theme` in that list.

**Comment by tgreyuk** [comment]
Thanks Gerrit - yes have just tested and the theme will load if configured directly. I'd be happy to review your config if you could share your repo.
