### ISSUE TITLE
@example with immediate code block needs newline

### ISSUE THREAD

**Issue by lorenzolewis** [tgreyuk/typedoc-plugin-markdown#324]
We have a TS document in the following format:
~~~typescript
/**
 * Gets the application version.
 * @example
 * ```typescript
 * import { getVersion } from '@tauri-apps/api/app';
 * const appVersion = await getVersion();
 * ```
 *
 * @returns A promise resolving to the application version.
 */
async function getVersion(): Promise<string> {
  return invokeTauriCommand<string>({
    __tauriModule: 'App',
    message: {
      cmd: 'getAppVersion'
    }
  })
}
~~~

With the above, the plugin is not adding the appropriate newline between `@example` and the beginning of the code block which is causing the output code to render like this:

```markdown
**`example`** ```typescript
import { getName } from '@tauri-apps/api/app';
const appName = await getName();
```

**Comment by tgreyuk** [comment]
Thanks - Fix in typedoc-plugin-markdown@3.13.2

**Comment by lucasfernog** [comment]
Works like a charm, thanks!

**Comment by ekoleda-codaio** [comment]
The fix seems to add an extra space before the starting triple-backtick though, as see [in your own test case](https://github.com/tgreyuk/typedoc-plugin-markdown/commit/396121e63db25b028b91fb935c7b1fbe8b25d9c4#diff-f319886e1e8343a24fe0d17371a02626f4c96118ea68f73cb9f36d473f2c93d1):

```
**\`Example\`**

 \`\`\`typescript
import { getVersion } from '@tauri-apps/api/app';
const appVersion = await getVersion();
\`\`\`
```

This is breaking rendering in my case (mkdocs), although perhaps other markdown renders allow some starting whitespace?

**Comment by tgreyuk** [comment]
You are right :) - have updated in (typedoc-plugin-markdown@3.13.3)
