### ISSUE TITLE
3.13.0 removes support for @typeParam docstrings

### ISSUE THREAD

**Issue by thomasballinger** [tgreyuk/typedoc-plugin-markdown#326]
It looks like typedoc-plugin-markdown 3.13.0 removes support for type parameter comments:
https://github.com/tgreyuk/typedoc-plugin-markdown/commit/f39318e1a58943170282b45a6d6cd0545a80cd4a#diff-7f67abb76184a8f36fc1d88d18a6dbd4f9f6c0a4c6ed5826a473da8556990a40R47-R51

Know what's up with this, is this intended?

**Comment by thomasballinger** [comment]
The comments seem to get lost somewhere in
https://github.com/tgreyuk/typedoc-plugin-markdown/blob/0615f05f02b5f6100c2a1959f6cae346086d70f7/packages/typedoc-plugin-markdown/src/resources/helpers/type-parameter-table.ts#L59-L63

**Comment by thomasballinger** [comment]
Upgrading typedoc from `0.23.2` to `0.23.8` restores the comments at `project.getChildByName('functionWithTypeParams').signatures[0].typeParameters[0].comment`,
at which point the issue becomes the `Handlebars.helpers.returns(parameter.comment)` referenced earlier.

**Comment by thomasballinger** [comment]
I'm missing some context on the changes that happened in https://github.com/tgreyuk/typedoc-plugin-markdown/commit/f39318e1a58943170282b45a6d6cd0545a80cd4a, but if this can keep being `comments` instead of `returns` then this seems to work.

**Comment by tgreyuk** [comment]
Thanks - not too sure what happened there. Will update when fix is released.

**Comment by tgreyuk** [comment]
Fix in typdoc-plugin-markdown@3.13.4

**Comment by thomasballinger** [comment]
Thanks a lot, really appreciate the quick fix!
