### ISSUE TITLE
does not respect disableSources

### ISSUE THREAD

**Issue by boneskull** [tgreyuk/typedoc-plugin-markdown#330]
It's unclear if this is in scope, since it may be a HTML-specific option, but I'd like to omit the "defined in..." sections from the markdown output.

If this _is_ an HTML-specific flag (can't tell from the docs), it does seem like a useful flag either way.

If such a PR to enable this flag would be considered, I may be able to send one.

Thanks for this project!

**Comment by tgreyuk** [comment]
That option is theme agnostic so is supported. I have just tested it - not sure why it doesn't for your use-case. If you are still experiencing issue will create a small demo repo.

**Comment by boneskull** [comment]
I think I was probably looking at an old file; I can confirm this works!  Sorry to bother.
