### ISSUE TITLE
Comments missing from .md

### ISSUE THREAD

**Issue by omfgnuts** [tgreyuk/typedoc-plugin-markdown#332]
Heyo!

I'm using your plugin to generate .md files, so I can later convert them to asciidoc files, everything works except for getting code comments into .md.

HTML with default theme gets comments with no issues, but it looks like something strips them when using typedoc-plugin-markdown.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/845482/182900076-928c2b12-c88d-4343-8fb4-46d5d9d030f5.png">

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/845482/182900520-8fcc75c9-9043-43ac-8bee-9e4fb7eb2f28.png">

What am I missing?

**Comment by tgreyuk** [comment]
not sure - i couldn't replicate on initial test - will dig into to it to see why this might happen in your use-case.

**Comment by omfgnuts** [comment]
> not sure - i couldn't replicate on initial test - will dig into to it to see why this might happen in your use-case.

If you'll have some time to spare on this issue:

If it helps, I'm trying to markdownify nativescript's docs here: https://github.com/NativeScript/NativeScript

command to build docs is `nx run core-api-docs:build`

What i should note, you'll need to remove "../../packages/core/**/*.ts" from excludes in /NativeScript/tools/scripts/tsconfig.typedoc.json and it should build just fine

**Comment by KillyMXI** [comment]
Which versions of `typedoc` and `typedoc-plugin-markdown` are used?
Not all versions are compatible with each other due to changes in minor versions of `typedoc`.
I observed some data missing when trying mutually incompatible versions.
This might also mean some breaking change was not caught up if both versions are most recent.

**Comment by omfgnuts** [comment]
> Which versions of `typedoc` and `typedoc-plugin-markdown` are used? Not all versions are compatible with each other due to changes in minor versions of `typedoc`. I observed some data missing when trying mutually incompatible versions. This might also mean some breaking change was not caught up if both versions are most recent.

Damn. You're right, I even forced new typedoc version in package.json but forgot to re-run npm -i, sorry to waste your time, but it helped a lot!

Now it gathers those comments no problemo :3

While you're here, (sorry!) what's the optimal way to fix following markup (or at least avoid writing regex or a script that removes extra free line and move link to the "Defined in" header:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/845482/183073241-2173fad7-a700-48fc-8aa6-4e002abf3655.png">

**Comment by omfgnuts** [comment]
> Which versions of `typedoc` and `typedoc-plugin-markdown` are used? Not all versions are compatible with each other due to changes in minor versions of `typedoc`. I observed some data missing when trying mutually incompatible versions. This might also mean some breaking change was not caught up if both versions are most recent.

Damn. You're right, I even forced new typedoc version in package.json but forgot to re-run npm -i, sorry to waste your time, but it helped a lot!

Now it gathers those comments no problemo :3

While you're here, (sorry!) what's the optimal way to fix following markup (or at least avoid writing regex or a script that removes extra free line and move link to the "Defined in" header:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/845482/183073241-2173fad7-a700-48fc-8aa6-4e002abf3655.png">

**Comment by tgreyuk** [comment]
> While you're here, (sorry!) what's the optimal way to fix following markup (or at least avoid writing regex or a script that removes extra free line and move link to the "Defined in" header:

Currently working on making the templates easily customisable - not too far off.

**Comment by chrisui** [comment]
@omfgnuts could you please share which versions worked for you?

**Comment by chrisui** [comment]
Updating solved for us too.

**Comment by eswarclynn** [comment]
> Updating solved for us too.

Facing the same issue. Could you share the specific versions of the two packages that worked for you please?
