### ISSUE TITLE
Slugification of hashes in links incompatible with vuepress

### ISSUE THREAD

**Issue by arantes555** [tgreyuk/typedoc-plugin-markdown#333]
When generating links for an element which contains a `_` in its name, for example `_propertyWithUnderscore`, typedoc-plugin-markdown generates it as `#_propertywithunderscore`. This is incompatible with the anchors generated by vuepress for the markdown title `## _propertyWithUnderscore`, as vuepress slugifies the anchor as `#propertywithunderscore`.

Example TS Code:
```typescript
export interface CustomTypeWithUnderscore {
  _propertyWithUnderscore: number
}
```

Generated TSDoc:
```markdown
# Interface: CustomTypeWithUnderscore

## Table of contents

### Properties

- [\_propertyWithUnderscore](CustomTypeWithUnderscore.md#_propertywithunderscore)

## Properties

### \_propertyWithUnderscore

• **\_propertyWithUnderscore**: `number`
```

Expected TSDoc:
```markdown
# Interface: CustomTypeWithUnderscore

## Table of contents

### Properties

- [\_propertyWithUnderscore](CustomTypeWithUnderscore.md#propertywithunderscore)

## Properties

### \_propertyWithUnderscore

• **\_propertyWithUnderscore**: `number`
```

A repo with a repro case is available at : https://github.com/arantes555/typedoc-testcases

**Comment by tgreyuk** [comment]
thanks - fix in vuepress-plugin-typedoc@0.11.1

**Comment by arantes555** [comment]
@tgreyuk I am sorry, I believe the commit in question got lost somehow. It is not present in the v0.11.1 code, and a click on the commit above shows the message `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`.

**Comment by arantes555** [comment]
@tgreyuk any update on this ?
