### ISSUE TITLE
Unclear "Type declaration" section, option to hide it

### ISSUE THREAD

**Issue by ilyub** [tgreyuk/typedoc-plugin-markdown#345]
Thx again for the plugin.

I see unclear "Type declaration" section inside markdown documentation:
![image](https://user-images.githubusercontent.com/70687432/188361298-c9d1e241-f01b-4719-a79c-4755c5905909.png)
that contains this:
```
(trueWeight?, falseWeight?): boolean
```

This code duplicates what is seen above:
```
Readonly boolean: (trueWeight?: number, falseWeight?: number) => boolean
```
while losing parameter types.

I am not sure why it is needed.

If there reasons for it, is it possible at least to add an option to hide "Type declaration" section?

**Comment by tgreyuk** [comment]
It follows the pattern of default theme as a heading for anonymous types, but agree its not really needed.  Would need to retain the correct heading hierarchy if removed - will look at it.

**Comment by tgreyuk** [comment]
Next version has a slightly different layout so this will no longer be relevant. For this reason closing this with no action.

**Comment by aosnow** [comment]
May I ask when this issue can be resolved!
