### ISSUE TITLE
Add a Docusaurus cli command to generate documentation without requiring a full build

### ISSUE THREAD

**Issue by CobyPear** [tgreyuk/typedoc-plugin-markdown#356]
Hello! Thanks for maintaining the `docusaurus-plugin-typedoc`. It has suited my needs well. Recently I've wanted to generate the docs through this plugin without running a full `docusaurus build`, because all I want is the markdown content.

I have opened a draft PR that does this but it needs some work, details here: #355 
I am open to continue working on this with some guidance. Thanks!

**Comment by tgreyuk** [comment]
As discussed - available in docusaurus-plugin-typedoc@0.18.0

**Comment by CobyPear** [comment]
Thanks so much!
