### ISSUE TITLE
Missing description for functions inside Object parameters

### ISSUE THREAD

**Issue by amandaghassaei** [tgreyuk/typedoc-plugin-markdown#357]
Thanks so much for the plugin!  Found an issue, thanks in advance for the help!

Related to: https://github.com/tgreyuk/typedoc-plugin-markdown/issues/281

Minimal example: https://github.com/amandaghassaei/typedoc-plugin-markdown-bug
typedoc: 0.23.16
typedoc-plugin-markdown: 3.13.6

For the function:
```ts
/**
 * My Function.
 * @param topLevelCallback A top-level callback.
 * @param params Params object.
 * @param params.callback1 A callback inside an object.
 * @param params.testParam Some number.
 * @param params.callback2 A callback inside an object.
 */
export function myFunction(
  topLevelCallback: () => void,
  params: {
    callback1: () => void,
    testParam: number,
    callback2: () => void,
  },
) {
  ....
}
```

markdown generated:

### myFunction

▸ **myFunction**(`topLevelCallback`, `params`): `void`

My Function.

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `topLevelCallback` | () => `void` | A top-level callback. |
| `params` | `Object` | Params object. |
| `params.callback1` | () => `void` | - |
| `params.testParam` | `number` | Some number. |
| `params.callback2` | () => `void` | - |

#### Returns

`void`

Seems to be specific to typedoc-plugin-markdown, I've attached an image of the typedoc html results:
<img width="928" alt="Screen Shot 2022-10-12 at 3 32 53 PM" src="https://user-images.githubusercontent.com/3218981/195460221-b35402b9-005f-4904-80aa-4eeab1bdb74e.png">

**Comment by tgreyuk** [comment]
Fix in typedoc-plugin-markdown@3.14.0

**Comment by amandaghassaei** [comment]
Looks great, thanks for your help!

**Comment by tgreyuk** [comment]
No problem - apologies it took so long :)
