### ISSUE TITLE
Provide a Configuration to Generate Object Type Declaration Members in List Mode

### ISSUE THREAD

**Issue by capraynor** [tgreyuk/typedoc-plugin-markdown#362]
Hi, I'm about to create a configuration: 
```
objectTypeDeclarationStyle: "table" | "list". 
```
This configuration behaviors like the following: 

When `objectTypeDeclarationStyle == "table"`:  (default value)
The "Object Type Declaration" (the type declaration that have children) will be rendered as table. 
 The "Call Signature Type Declaration" will works as before. 
 The "Union Type Declaration" will works as before. 

When `objectTypeDeclarationStyle == "list"`: 
The "Object Type Declaration" (the type declaration that have children) will be rendered as list, just like current behavior of class properties. 
 The "Call Signature Type Declaration" will works as before. 
 The "Union Type Declaration" will works as before. 

Will submit my PR with test spec later.

**Comment by capraynor** [comment]
If use `objectTypeDeclarationStyle == "list"`: 

The rendered result will be: 
![image](https://user-images.githubusercontent.com/3467515/198925740-405531b6-48de-4703-a7e6-053decaab0e0.png)

And the multi line comment will shows like: 

![image](https://user-images.githubusercontent.com/3467515/198925812-8e2e995a-415d-4912-96f7-7efd879abeca.png)

**Comment by tgreyuk** [comment]
Thanks. PR merged available in typedoc-plugin-markdown@3.14.0.
