### ISSUE TITLE
Slugification of hashes in links still incompatible with vuepress

### ISSUE THREAD

**Issue by arantes555** [tgreyuk/typedoc-plugin-markdown#369]
Issue https://github.com/tgreyuk/typedoc-plugin-markdown/issues/333 was not fixed correctly : I am not sure how, but the commit fixing it got lost somehow ( https://github.com/tgreyuk/typedoc-plugin-markdown/commit/ea110e450c50eff47514fa6bae19215bc56a52ad ).

**Comment by tgreyuk** [comment]
Very odd. I have pushed the commit and repubished package (0.11.2). https://github.com/tgreyuk/typedoc-plugin-markdown/commit/78cd78fa5d0ddf0f328459e715099085c45b3b23 ..

Please try again. Apologies for lack of previous response.
