### ISSUE TITLE
[next] Index signature in member declaration bug

### ISSUE THREAD

**Issue by lorenzolewis** [tgreyuk/typedoc-plugin-markdown#381]
This is currently a string where I believe it should be code or removed:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/e86bda396e03731d95956865fc4c9a83967e01ae/packages/typedoc-plugin-markdown/src/partials/member.declaration.ts#L29

**Comment by lorenzolewis** [comment]
There's also the same here that I just noticed:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/e86bda396e03731d95956865fc4c9a83967e01ae/packages/typedoc-plugin-markdown/src/partials/reflection.ts#L48-L51

**Comment by tgreyuk** [comment]
Fixed in `next` branch.
