### ISSUE TITLE
Duplicating content

### ISSUE THREAD

**Issue by benmccann** [tgreyuk/typedoc-plugin-markdown#385]
To reproduce (requires [pnpm to be installed](https://pnpm.io/installation)):
```
git clone git@github.com:JonasKruckenberg/imagetools.git
cd imagetools
pnpm install
pnpm doc
```

See that `docs/README.md` now contains `imagetools / [Modules](modules.md)` multiple times. Each time you run it, it will be added an additional time

**Comment by tgreyuk** [comment]
Its because the readme file is inside the output directory. It is basically creating a copy of it each time and adding the header. Really the README should be located outside of the generated docs folder.

**Comment by tgreyuk** [comment]
Closing this as no fix. But this issue won't actually happen in the next version (typedoc-plugin-markdown@next).

**Comment by benmccann** [comment]
thanks!
