### ISSUE TITLE
Decorator support

### ISSUE THREAD

**Issue by xaviermonin** [tgreyuk/typedoc-plugin-markdown#391]
Hi,
I used `docusaurus-plugin-typedoc`.
Is there a way to display decorators as decorators in the documentation and not as functions?
I tried to tag with `@decorator` and exported the decorator as `ClassDecorator` / `PropertyDecorator` / etc, but it does not work.

Thanks for your help.

**Comment by tgreyuk** [comment]
This is more of a question for Typedoc itself, but I don't think there is support for this currently. There does seem some interest on it though.

**Comment by tgreyuk** [comment]
I am actually going to close this as its not something to be fixed at plugin level. Please see some previous discussions for context:

https://github.com/TypeStrong/typedoc/issues/97
https://github.com/TypeStrong/typedoc/issues/181
