### ISSUE TITLE
Relative markdown links are not rewritten

### ISSUE THREAD

**Issue by pokey** [tgreyuk/typedoc-plugin-markdown#394]
## Expected Behavior

In the following declaration:

```ts
/**
 * Some [link](../../../docs/foo.md).
 */
export function bar() {}
```

The output file `modules/bar.md` includes the same link, which is correct when relative to the original file, but it should be relative to the output file.

## Actual Behavior

The link is relative to the original file

Not sure if I should file this one against https://github.com/TypeStrong/typedoc instead, but I'm not sure these relative links make sense there

Note that I'm using `docusaurus-plugin-typedoc`

**Comment by tgreyuk** [comment]
The plugin simply prints the raw markdown form comment blocks.  I think this is more of a docusaurus config issue.

**Comment by pokey** [comment]
I'm not sure how I'd solve this with docusaurus config, because typedoc is flattening a hierarchy of files, so by the time docusaurus sees the output, it's not possible to know where the source file was, so I'm not sure how it would know how to resolve the relative link

But I acknowledge that there are a lot of moving pieces here (a plugin inside type doc, running inside docusaurus, if I've understood correctly 😅)

Is there some way for docusaurus to resolve the link that I'm missing?

**Comment by tgreyuk** [comment]
This is the link that is causing the CI failure. It is referring to a markdown page outside of the generated documentation - https://github.com/cursorless-dev/cursorless/blob/pokey/reintroduce-stable-hats/src/util/allocateHats/allocateHats.ts#L35

**Comment by tgreyuk** [comment]
It seems dropping the .md from the link resolves the error on my local testing?

```
See [hat assignment](../../../docs/user/hatAssignment) for more info.
```

**Comment by pokey** [comment]
Wow thanks for looking into that and debugging it for me 😅.  Your solution doesn't quite work for me, though. I get the following error:

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/contributing/api/modules/util_allocateHats_allocateHats/:
   -> linking to ../../../docs/user/hatAssignment/ (resolved as: /docs/contributing/docs/user/hatAssignment/)

- On source page path = /docs/contributing/api/modules/util_allocateHats_chooseTokenHat/:
   -> linking to ../../../docs/user/hatAssignment/ (resolved as: /docs/contributing/docs/user/hatAssignment/)

    at throwError (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at handleBrokenLinks (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
    at async buildLocale (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/core/lib/commands/build.js:177:5)
    at async tryToBuildLocale (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
    at async mapAsyncSequential (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/Users/pokey/src/cursorless/docs-site/node_modules/@docusaurus/core/lib/commands/build.js:73:21)
[INFO] Docusaurus version: 2.0.1
Node version: v16.17.0
error Command failed with exit code 1.
```

However, I now realise that the relative links I had weren't actually working in VSCode hover due to https://github.com/microsoft/TypeScript/issues/47718, so I can just use whatever link location works for Typedoc without worrying about what works for VSCode hover.  Turns out that the VSCode hover appeared to be working because I was hovering in the file itself, but if you hover over a reference from a different file, VSCode isn't smart and treats the link relative to where you're hovering, so it will break.

I'm just going to use absolute links for now, which work fine: `[hat assignment](/docs/user/hatAssignment)`

Once https://github.com/microsoft/TypeScript/issues/47718 is supported, I'd argue that this issue should be supported, but until then, I'm not sure there's much benefit 🤷

**Comment by tgreyuk** [comment]
going to close this as there is a workaround and not sure there is anything that can be done at plugin level anyway. thanks for flagging this was useful info.
