### ISSUE TITLE
Option to suppress "Defined in" fields

### ISSUE THREAD

**Issue by jpeterstewart** [tgreyuk/typedoc-plugin-markdown#400]
When a Docusaurus site holds documentation for multiple software components -- and the TypeScript files are imported from another project into a subfolder -- the "Defined in" field is not very useful. For one thing, the reader may not have access to the repository.

But the more serious problem is that the link goes to the Docusaurus project as a whole, not the project that the TypeScript files belong to! And since nearly every object on the website ends up with the same class, it's not easily fixed in CSS.

It would be really great if there was an option to suppress the "Defined in" fields!

**Comment by tgreyuk** [comment]
hello - you can use `disableSources: true` . Its a TypeDoc core option https://typedoc.org/guides/options/#disablesources

**Comment by jpeterstewart** [comment]
Great, thanks!
