### ISSUE TITLE
Group by file

### ISSUE THREAD

**Issue by christopher-buss** [tgreyuk/typedoc-plugin-markdown#404]
Currently I have a class `A` that has three utility functions `U1`, `U2`, and `U3`. These are located in a file `A.ts`, and then re-exported in a file `index.ts` - which is the root of the project.

The format of the A.ts file is as follows:

```typescript
// some types here

export function U1 {}
export function U2 {}
export function U3 {}

export class A {}
``` 

The three utility functions are only related to A, but currently I can either seem to get them to appear in their own md file seperately, or to include everything in a huge monolithic modules file. The only other solution I have found is to declare each file individually in the typedoc `entryPoints`, but this has its own complications. Is there any way I could achieve what I am looking for?

**Comment by tgreyuk** [comment]
Could you not declare export A.ts as an entrypoint? There have been some improvements made to file output in "next" version https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/typedoc-plugin-markdown/docs/file-output-options.md

**Comment by tgreyuk** [comment]
I am actually going to close this. Typedoc works off things exported from modules (not files).
