### ISSUE TITLE
includeVersion option ignored now - version is missing

### ISSUE THREAD

**Issue by KillyMXI** [tgreyuk/typedoc-plugin-markdown#415]
In tsconfig.json:

```
...
"typedocOptions": {
    ...
    "includeVersion": true,
    ...
  },
...
```

Updating from

```
    "typedoc": "~0.23.28",
    "typedoc-plugin-markdown": "~3.14.0",
```

to

```
    "typedoc": "~0.24.4",
    "typedoc-plugin-markdown": "~3.15.1",
```

HTML output without the plugin contains version number.
Markdown output with the plugin now has the version missing (had it previously).

**Comment by tgreyuk** [comment]
Thanks - please try with typedoc-plugin-markdown@3.15.2 .

**Comment by KillyMXI** [comment]
Thank you. Seems fixed - no diffs after updating.
