### ISSUE TITLE
Getting error: "TypeError: template is not a function" when running typedoc generateDocs() function

### ISSUE THREAD

**Issue by axli20** [tgreyuk/typedoc-plugin-markdown#424]
I wrote a script that uses typedoc (v^0.23.27) and typedoc-plugin-markdown (v3.15.2, latest) to generate markdown documentation files for my project. I'm running into the following error when I run the script:

```
Loaded plugin typedoc-plugin-markdown
TypeError: template is not a function
```

The script is super simple:

``` js
const app = new TypeDoc.Application();
app.options.addReader(new TypeDoc.TypeDocReader());
app.options.addReader(new TypeDoc.TSConfigReader());

const options = {
...
plugin: 'typedoc-plugin-markdown'
...
}

app.bootstrap(bootstrapOptions);
const project = app.convert();

if (project) {
  await app.generateDocs(project, outputDir);
}
```

After debugging, I've narrowed it down to the `app.generateDocs(project, outputDir)` call that's throwing the error. Would love to see this fixed, as the only solution I've found is to use version 3.14.0 of the typedoc-plugin-markdown package for now.

**Comment by tgreyuk** [comment]
Are you able to upgrade TypeDoc to `^0.24`? There were some breaking API changes between `0.23` and `0.24`.

**Comment by axli20** [comment]
Just tried updating the typedoc version to 0.24.6 with plugin version 3.15.2, and this time it looks like typedoc didn't pick up on the plugin? When I ran the script it generated html files even though I specify the typedoc-plugin-markdown plugin in the bootStrap options.

**Comment by tgreyuk** [comment]
You now need to use app.bootstrapWithPlugins()

_Application.bootstrap will no longer load plugins. If you want to load plugins, use Application.bootstrapWithPlugins instead, #1635._

https://github.com/TypeStrong/typedoc/blob/master/CHANGELOG.md#v0240-2023-04-08

**Comment by axli20** [comment]
Ahh I see, thank you!

**Comment by axli20** [comment]
Tried using app.bootstrapWithPlugins() with typedoc version 0.24.6, plugin version 3.15.2, and generateDocs call just hangs...

**Comment by axli20** [comment]
Any updates here?

**Comment by tgreyuk** [comment]
Those methods return promises - are you using async/await ?
