### ISSUE TITLE
Properties with multiple allowable types render incorrectly

### ISSUE THREAD

**Issue by theholla** [tgreyuk/typedoc-plugin-markdown#43]
**Issue:**

When a property has multiple allowable types, the asterisks that are supposed to italicize the property types have a space between the type and the asterisk. For example: `* string | boolean *`. When the markdown file is generated, this results in a stray asterisk before the types, and a stray bullet below.

**Proposed solution:**

When a property can have multiple types, the asterisks should be located immediately next to the types, with no space, like this: `*string | boolean*`.

The following sample interface would exhibit this behavior:

```javascript
export interface ISettings {
  aSetting: string | boolean;
}
```

Which renders the following (broken) markdown:

```markdown
## Properties

<a id="asetting"></a>

###  aSetting

**● aSetting**: * `boolean` &#124; `string`
*

*Defined in [path/to/file](https://path/to/github/file)*
```

See the following screenshot:

<img width="326" alt="markdown" src="https://user-images.githubusercontent.com/10987970/50313949-eca3b000-0461-11e9-9ac9-20bb3f1fee3b.png">

**Comment by tgreyuk** [comment]
thanks.. should be fixed in 1.1.20
