### ISSUE TITLE
Rendering of interface properties that are objects

### ISSUE THREAD

**Issue by balazsorban44** [tgreyuk/typedoc-plugin-markdown#437]
If an interface property is an object, is there a way to render its properties as well?

Code:
https://github.com/nextauthjs/next-auth/blob/de81bb7124449b7576863a3c684f554c55ce2b8b/packages/frameworks-nextjs/src/lib/index.ts#L14-L58

Generated documentation:
https://auth-docs-git-feat-nextjs-auth-authjs.vercel.app/reference/nextjs#callbacks

![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/18369201/90d5f650-e783-4028-b6b4-10fa7e69bad3)

I would like if `callbacks.authorized`'s documentation was rendered as well. Any suggestions?

**Comment by tgreyuk** [comment]
@balazsorban44 Ok this was a little interesting and something that is not exposed in the HTML theme either.

I have initially come up with this kind of thing - essentially just nesting the intersection types that are literals.

<img width="814" alt="Screenshot 2023-05-23 at 22 16 47" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/f36c8d97-9c40-459a-911b-fedfe58fbccb">

What do you think?

The other thing I noticed when browsing your docs is that the 'index' is coming in the middle of the sidebar - do you agree that this should at the top? I could look for modules named  'index', but this could be renamed using the `@module` tag, so it might be better to introduce a modifier tag to flag it as the main entrypoint - not sure.

<img width="540" alt="Screenshot 2023-05-23 at 22 24 41" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/4b493a0c-1a21-4246-8444-8454aba66acf">


Once we agree on this i'd be happy to PR onto your repo the package version updates as a couple of the config options have changed slightly too in the last couple of versions?

**Comment by balazsorban44** [comment]
yeah I agree, both sounds good, thanks!
