### ISSUE TITLE
Can we get rid of a class that inherits Array and documents all Array properties and methods?

### ISSUE THREAD

**Issue by xuxchao** [tgreyuk/typedoc-plugin-markdown#442]
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/28293069/3283cb8b-42b5-4db9-80f6-d007ce3ca62a)

**Comment by tgreyuk** [comment]
you need `excludeExternals: true`

https://typedoc.org/options/input/#excludeexternals
