### ISSUE TITLE
API.md missing functions

### ISSUE THREAD

**Issue by RichiCoder1** [tgreyuk/typedoc-plugin-markdown#444]
Howdy! I'm using `typedoc-plugin-markdown@next`, and running into an issue where `API.md` only seems to contain exported interfaces and not functions. If I switch to `outputFileStrategy: "modules"` they show up, and the member MDs show up on disk with `"members"`, but they don't show up in the `API.md` doc.

Is there a setting I need to flip to get exported function members into the API.md?

**Comment by tgreyuk** [comment]
Hello - I am trying to replicate this - is your code on a public repo? If not could you let me know what other options you are using? Many thanks.

**Comment by RichiCoder1** [comment]
@tgreyuk private, but I'll see if I can put together a code sandbox with examples.

If it helps in the meantime:

`.config/typedoc.cjs`:
```
/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  name: "JS Libs",
  entryPointStrategy: "packages",
  out: "../docs",
  githubPages: false,
  gitRevision: "main",
  plugin: ["typedoc-plugin-markdown"],
  entryPoints: [
    "../packages/package-a"
  ],
  readme: "none"
};
```

`.config/typedoc.base.json`
```
{
  "$schema": "https://typedoc.org/schema.json",
  "includeVersion": true
}
```

`packages/package-a/typedoc.config.json`
```
{
  "$schema": "https://typedoc.org/schema.json",
  "extends": ["../../.config/typedoc.base.json"],
  "entryPoints": ["src/index.ts"]
}
```

`packages/package-a/src/index.ts`
```
export interface MyArgs {
  readonly someArg: boolean;
}

export function someExampleFunction(args: MyArgs) {
	return args;
}
```

Above is a adapted minisample. I think it's because in `page.toc.ts` it's only printing out modules:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/typedoc-plugin-markdown/src/theme/resources/partials/page.toc.ts#L40-L41

But modules on includes (or seems to include exported interfaces in this case. So functions aren't present.

Is it intentional that the toc includes modules?
