### ISSUE TITLE
typedoc-plugin-markdown - 4.0.0-next.17: `docusarus run` fails if there's a sidebar config for generated docs in sidebars.js

### ISSUE THREAD

**Issue by aamir1995** [tgreyuk/typedoc-plugin-markdown#457]
Hello, thanks for this awesome project :)

I'd like to report a possible bug that's only happening when you use `4.0.0-next.17`, I tried downgrading to `4.0.0-next.16` and it worked like a charm!

It seems that when you're on `4.0.0-next.17`, command `docusaurus run` results in an error if there's a sidebar config in sidebars.js. 

in my case, I have defined some config for generated docs in the sidebars.js as follows:
```
const sidebars = {
  mainSidebar: [
    {
      type: "category",
      label: "Documentation",
      link: {
        type: "generated-index",
        title: "Docs",
        description: "Learn more about the APIs",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "web_app",
          link: {
            type: "doc",
            id: "web_app/index",
          },
          items: [{ type: "autogenerated", dirName: "web_app" }],
           },
      ]
    }
  ]
}
```

but if you remove this config and run `docusaurus run` command, it will work fine but if the sidebar config exists it results in an error that looks like this:
<img width="520" alt="Screenshot 2023-08-07 at 3 47 36 PM" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/10736453/6d8980c2-c1df-40d0-9c49-3eee89b1cbf0">

**Comment by tgreyuk** [comment]
Thanks - fixed in `4.0.0-next.18`
