### ISSUE TITLE
Custom i18n texts

### ISSUE THREAD

**Issue by kaikaibenkai** [tgreyuk/typedoc-plugin-markdown#458]
This may be difficult, but it is really important :heart:

**Comment by tgreyuk** [comment]
Do you want the ability to have a dictionary of static labels for things like group headings (Variables, Functions etc) or something else?

**Comment by kaikaibenkai** [comment]
> Do you want the ability to have a dictionary of static labels for things like group headings (Variables, Functions etc) or something else?

Yes

**Comment by tgreyuk** [comment]
This is now possible in the `next` version. See https://www.typedoc-plugin-markdown.org/options#textcontentmappings .
