### ISSUE TITLE
[docusaurus-plugin-typedoc] Options in `typedoc.json` are no longer applied

### ISSUE THREAD

**Issue by haakonflatval-cognite** [tgreyuk/typedoc-plugin-markdown#468]
The plugin now only seems to care for options that are supplied directly to the plugin in `docusaurus.config.js`. 

As a sidenote, I believe the `ArgumentsReader` objects used in the application construction https://github.com/tgreyuk/typedoc-plugin-markdown/blob/2f50b8d7f54bbba2dc95d22299ed9e32c99ad8c4/packages/docusaurus-plugin-typedoc/src/plugin.ts#L66 should be removed, as they are reading the arguments sent to `docusaurus`.

**Comment by tgreyuk** [comment]
Thanks - should be fixed in docusaurus-plugin-typedoc@0.20.1
