### ISSUE TITLE
[next] Some type outputs are broken

### ISSUE THREAD

**Issue by ziad-saab** [tgreyuk/typedoc-plugin-markdown#473]
Some type outputs contain HTML tags that break the rendering. An example can be seen here:

https://docs.metamask.io/zs/keyring-doc/snaps/reference/keyring-api/Classes/class.KeyringClient/#parameters-1

Capture of the output:

<img width="943" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3943143/aa1234cc-522a-423f-abec-f3ce0887d75e">

**Comment by tgreyuk** [comment]
## Fix versions

typedoc-plugin-markdown@4.0.0-next.21
docusaurus-plugin-typedoc@1.0.0-next.16

## Changes

<img width="960" alt="Screenshot 2023-09-25 at 23 08 12" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/6c1e2b04-bec7-4d80-b168-ba7fd1064217">
