### ISSUE TITLE
[next] `sidebar_position` not being taken into account

### ISSUE THREAD

**Issue by ziad-saab** [tgreyuk/typedoc-plugin-markdown#475]
in the `next` version, the `sidebar_position` of the main markdown file is always set to `0`. there doesn't seem to be any way to change that.

**Comment by tgreyuk** [comment]
## Fix versions

docusaurus-plugin-typedoc@1.0.0-next.16

## Changes

The auto-generated sidebar config was proving to be a bit of a headache, so the latest version exports an actual sidebar config file iso the sidebar can be manually configured as required. See https://github.com/tgreyuk/typedoc-plugin-markdown/tree/next/packages/docusaurus-plugin-typedoc#sidebar

I'd be happy to create a PR on your repo with the fix if you could point me to a suitable branch to use?

**Comment by Montoya** [comment]
Sure thing! Here's a branch where I attempted to fix it (linked in PR): https://github.com/MetaMask/metamask-docs/pull/929

**Comment by tgreyuk** [comment]
@Montoya thanks - I have added suggested updates here https://github.com/MetaMask/metamask-docs/pull/940.

As mentioned the sidebar now is now manually generated. This means we can get rid of the number prefixing for filenames (used for ordering) that would have been a nightmare to maintain link references (have also updated such links in the PR).
