### ISSUE TITLE
[typedoc-plugin-markdown@next] Bug (Lint MD011): Using indexed access types (may) trigger reversed link syntax rule.

### ISSUE THREAD

**Issue by sharky98** [tgreyuk/typedoc-plugin-markdown#484]
Hello,

This is probably an edge case. I am using [indexed access types](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html) to obtain the type of an array's element.

> Another example of indexing with an arbitrary type is using number to get the type of an array’s elements.

This look like this.

```ts
type ArrayOfStuff = {name: string, age: number}[];
 
type Stuff = ArrayOfStuff[number];
```

`ArrayOfStuff` and `Stuff` have both their own page. As such, a link is made in the resulting markdown. It looks like this.

```md
[`ArrayOfStuff`](ArrayOfStuff.md)[`number`]
```

However, this syntax triggers the markdownlint rule [MD011](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md011---reversed-link-syntax) about reversed link syntax.

**Suggestion**

To avoid this, the square brackets coming from the source code could be escaped.

```md
[`ArrayOfStuff`](ArrayOfStuff.md)\[`number`\]
```

Note: The rule is not triggered when the square brackets are empty, but I see not adverse effect of escaping them also.

**Comment by tgreyuk** [comment]
Thank you. Fix in typedoc-plugin-markdown@4.0.0-next.24
