### ISSUE TITLE
(regression) @return being ignored after next-21

### ISSUE THREAD

**Issue by signorecello** [tgreyuk/typedoc-plugin-markdown#487]
[Here's a quick repro example](https://github.com/signorecello/breaking-typedoc-markdown)

Running typedoc on this won't render the return type `boolean`. But if we downgrade to next-20, it will

**Comment by tgreyuk** [comment]
Thanks for producing the example repo. Fixed in typedoc-plugin-markdown@4.0.0-next.25.
