### ISSUE TITLE
Pipe character not escaped

### ISSUE THREAD

**Issue by jerylvaz** [tgreyuk/typedoc-plugin-markdown#49]
```
/**
 * Foo method
 * @param bar Some argument with | in description
 */
public foo (bar: number | string): void {
}
```
Parameter table generated as 
```
| bar | `number` | `string` |  Some argument with | in description |
```
instead of
```
| bar | `number` \| `string` |  Some argument with \| in description |
```

Escape sequence missing for **union types** and **pipe chars** in method description.

Version:
typedoc-plugin-markdown@1.1.22
typedoc@0.14.2

**Comment by tgreyuk** [comment]
Thanks - fixed in 1.1.23..

**Comment by tgreyuk** [comment]
Actually I have realised that pipes are still not being escaped in comments. Have re-opened issue.

**Comment by tgreyuk** [comment]
Comments fixed in 1.1.24

**Comment by mhofman** [comment]
> Actually I have realised that pipes are still not being escaped in comments. Have re-opened issue.

Pipe characters are now escaped too aggressively: pipe characters in code blocks should not be escaped.

```typescript
/**
 * Foo function
 *
 * @example
 * ```javascript
 * const bar = foo() || true;
 * ```
 */
function foo(): boolean {
    return false
}
```

Results in:
`````markdown
## Functions

<a id="foo"></a>

###  foo

▸ **foo**(): `boolean`

Foo function

*__example__*:
 ```javascript
const bar = foo() \|\| true;
```

**Returns:** `boolean`
`````

**Comment by halkar** [comment]
Same issue. Pipe characters in code blocks are escaped.
