### ISSUE TITLE
Docusaurus V3 Support

### ISSUE THREAD

**Issue by strmer15** [tgreyuk/typedoc-plugin-markdown#491]
Looks like Docusaurus V3 is now out - https://docusaurus.io/blog/releases/3.0

However, when I use this plugin, it's producing output that fails MDX compilation - for example, things like `<` and `>` now have to be strictly for JSX tags or escaped (https://docusaurus.io/docs/migration/v3#bad-usage-of--1). Can this plugin be updated to support Docusaurus v3?

Thanks for all your time and attention to maintaining this work!

**Comment by xixixao** [comment]
In case it's helpful to anyone, this is the commit in our private fork for supporting MDXv2:

https://github.com/get-convex/typedoc-plugin-markdown/commit/795e7a7b83b56cc3cbc659c0672a7d5d5aa62164

**Comment by tgreyuk** [comment]
@strmer15 thanks for raising this. 

As you have just noted MDX2 support is already supported in next version, but if you are not ready to upgrade yet have also added support to main versions now:

- typedoc-plugin-markdown@3.17.0
- docusaurus-plugin-typedoc@0.21.0

**Comment by strmer15** [comment]
Thanks @tgreyuk ! I updated to the latest an I've got it building again with Docusaurus v3 :tada:
