### ISSUE TITLE
References containing angle brackets improperly escape the angle bracket with a backslash `\` before escaping them with the HTML escape character `&gt;` 

### ISSUE THREAD

**Issue by loucadufault** [tgreyuk/typedoc-plugin-markdown#495]
This came up when using this plugin alongside the plugin: https://github.com/Gerrit0/typedoc-plugin-missing-exports, which by default creates a module named `<internal>`. This module seems to be improperly escaped when referenced elsewhere in the typedoc, as: 

```md
### Modules

- [&lt;internal\&gt;](index._internal_.md)
```

which renders as:

- [&lt;internal\&gt;](index._internal_.md)

Note that the escaping is somehow only incorrect for the closing angle bracket.

I am not sure whether this is an issue with this plugin, but I confirmed that when not using the plugin, the reference to the module is properly escaped (using the native HTML renderer).

I tried looking through the source, as far as I can tell there is the [`escapeChars()`](https://github.com/tgreyuk/typedoc-plugin-markdown/blob/bb7717a9cd28958802810c0f3041bd1a9672c160/packages/typedoc-plugin-markdown/src/utils.ts#L19) function that probably runs on the module name to create the reference name, but I am not sure what is then converting that to the HTML escape characters `&lt;` and `&gt;`.

**Comment by tgreyuk** [comment]
OK thanks - this was actually being escaped by Handlebars. Please try with typedoc-plugin-markdown@3.17.1 which contains a fix.

**Comment by loucadufault** [comment]
Thanks for the quick fix! Can confirm this is resolved in 3.17.0.
