### ISSUE TITLE
typedoc-plugin-markdown@4.0.0-next.26 replaces the `/` in module names to `_` 

### ISSUE THREAD

**Issue by ocavue** [tgreyuk/typedoc-plugin-markdown#497]
Commit 4d8a5bd1e022103ca624c4c6d95cd85955a7b9cb replaces all the `/` in module name to `_` in [this line](https://github.com/tgreyuk/typedoc-plugin-markdown/commit/4d8a5bd1e022103ca624c4c6d95cd85955a7b9cb#diff-29865936a442fb34c651856ac87093617b6ca589747afcaa579118df2178c725R136). I know this is by design, however I quite like the previous behavior. 

I have an NPM package called `prosekit`. This package includes multiple modules like `prosekit/extensions/code`. Previously typedoc-plugin-markdown generated a `prosekit/extensions/code.md` file, so the rendered HTML page would be `prosekit/extensions/code`, which is exactly the import path when people use this package in JS code. Currently typedoc-plugin-markdown generates `prosekit_extensions/code.md`, and it doesn't match the JS import path anymore. 

I'd love to have an option to bring the previous behavior back.

**Comment by ocavue** [comment]
By the way (not related this issue directly), if we want to normalize some characters in the output file name, I would prefer `-` over `_`. Because one big usage of Markdown files is to generate HTML files, and `-` is often seen then `_` in the URL.

**Comment by tgreyuk** [comment]
Apologies this was not the intended behaviour. Initial behaviour restored in 4.0.0-next.27. Agreed on the point about the slugs also - thanks for highlighting that also.

**Comment by ocavue** [comment]
4.0.0-next.27 works for me. Thanks for your quick fix!
