### ISSUE TITLE
Code block must begin with new line

### ISSUE THREAD

**Issue by jerylvaz** [tgreyuk/typedoc-plugin-markdown#50]
```
/**
 * Some deprecation
 * @deprecated
 * ```typescript
 * somethingElse();
 * ```
 */
export function foo () : void {
}
```
is generated as
````
Some deprecation
*__deprecated__*: ```typescript
somethingElse();
```

**Returns:** `void`
````

and rendered as

---
Some deprecation
*__deprecated__*: ```typescript
somethingElse();

```
**Returns:** `void`
```

---

Instead a line break must be inserted before code block:
````
Some deprecation
*__deprecated__*: 
```typescript
somethingElse();
```

**Returns:** `void`
````

to render correctly as

---
Some deprecation
*__deprecated__*: 
```typescript
somethingElse();
```
**Returns:** `void`
---

**Comment by tgreyuk** [comment]
This scenario will be fixed in 1.1.25. Thanks.

**Comment by jerylvaz** [comment]
The solution does not work for example with @throws tag.
A new line must be added **before each code block** and not after a tag as is done with this patch.

**Comment by tgreyuk** [comment]
@jerylvaz sorry try 1.1.26.... thanks.
