### ISSUE TITLE
`[Symbol.dispose](): void;` is incorrectly being assumed as Markdown Link while using Docusarus 3 and MDX 3

### ISSUE THREAD

**Issue by aamir1995** [tgreyuk/typedoc-plugin-markdown#503]
This line from our API documentation (Typedoc document) `[Symbol.dispose](): void;` is incorrectly being assumed as Markdown Link `### [dispose]()` while using Docusarus 3 and MDX 3, and results in failed compilation:
```
Error: MDX compilation failed for file "/docs/web_api/classes/View.md"
Cause: Markdown link URL is mandatory in "docs/web_api/classes/View.md" file (title: dispose, line: 283).
Details:
Error: Markdown link URL is mandatory in "docs/web_api/classes/View.md" file (title: dispose, line: 283).
```

This used to work fine in previous versions of Docusaurus but it is the MDX V3 which is stricter.

Environment Info:
Docusarus version: `3.0.0`
@mdx-js/react: `3.0.0`
docusaurus-plugin-typedoc: `1.0.0-next.21`
typedoc-plugin-frontmatter: `0.0.2`
typedoc-plugin-markdown: `4.0.0-next.27`

**Comment by tgreyuk** [comment]
thanks - fixes in typedoc-plugin-markdown: 4.0.0-next.29
