### ISSUE TITLE
[typedoc-plugin-markdown@next] Hide source in table

### ISSUE THREAD

**Issue by CoderIllusionist** [tgreyuk/typedoc-plugin-markdown#510]
Hello,

Currently checking out the table view on the next version of typedoc-plugin-markdown and docusaurus-plugin-typedoc and it looks awesome :) 

However, how can I hide/remove the generated source in the table view? It's not needed for me to reference the source file for every single property in the table, is there something like `--hideSource` ? Im willing to create a PR for this.

Thanks,
Patrick

**Comment by tgreyuk** [comment]
Hello. yes this should be removed by using the TypeDoc option `disableSources` https://typedoc.org/options/input/#disablesources
