### ISSUE TITLE
[typedoc-plugin-markdown@next] Gap between description and @deprecated comment

### ISSUE THREAD

**Issue by CoderIllusionist** [tgreyuk/typedoc-plugin-markdown#511]
I noticed that there is a unusually large gap when the `@deprecated` is used: 
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/75251048/3e36265c-4e7b-4d42-bc17-9fd0b1567bd2)
Is it maybe an option to not render it like this, but more like this when something is deprecated;
![Scherm_afbeelding 2023-11-23 om 17 35 06 (1)](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/75251048/914fb78a-f995-403b-9f16-6b06e23f2260)

**Comment by tgreyuk** [comment]
Thank you - have updated with a fix in typedoc-plugin-markdown@4.0.0-next.31

**Comment by CoderIllusionist** [comment]
No problem, glad to help! Closing.
