### ISSUE TITLE
[typedoc-plugin-markdown@next] Unnecessary newlines  @see @link

### ISSUE THREAD

**Issue by CoderIllusionist** [tgreyuk/typedoc-plugin-markdown#513]
Hi,

We define a property for our component like so;

```
    /**
     * The message to display when the input does not have an entered `value`, but is required.
     * @see {@link PwcInputHintMessage}
     * @deprecated Will be removed in version 7.x.
     * User `message.required` instead.
     */
    @Prop() requiredMessage?: string;
```

This is rendered like so:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/75251048/12e804ea-8912-46a5-afd9-561eacbb9bd5)

Maybe make it like so (remove the unnecessary newline for `@see`);
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/75251048/12225698-78c2-4d0b-9040-257dee2fcb27)

Edit this also happens with for example `@defaultValue`

**Comment by tgreyuk** [comment]
Thanks - I think this is quite subjective. The html theme also places all tags as headings on own line. Could perhaps reduce the space, but again the spacing could be a preference for some. Will have to think about this one.
