### ISSUE TITLE
What is `--mergeReadme` option alternative in latest next?

### ISSUE THREAD

**Issue by SkReD** [tgreyuk/typedoc-plugin-markdown#518]
How to generate single file entrypoint with all exported members?

**Comment by tgreyuk** [comment]
> Now it merges into file exports.md

No thats not the intention and its not happening in my tests - i'll take a look to see if I can replicate. Do you also have an index.md page?

> Also there is duplicate of package name in result md

So the 2nd heading is the title of the index page. This can be configured by `indexPageTitle`, for example:

```
indexPageTitle: 'API Index'
```

Is this  an acceptable compromise?

**Comment by tgreyuk** [comment]
Thanks for the repo that was very useful. Please try typedoc-plugin-markdown@4.0.0-next.35 .  Have actually removed the additional title now so it behaves the same way as previously.
