### ISSUE TITLE
Is there a config option to exclude inherited members?

### ISSUE THREAD

**Issue by xiaofeiyun123** [tgreyuk/typedoc-plugin-markdown#524]
1. "visibilityfilters" does not work when using the plugin "typedoc-plugin-markdown".
https://typedoc.org/options/output/#visibilityfilters

2. The plugin "typedoc-plugin-no-inherit" has the following errors when using typedoc": "^0.25.4
[error] The plugin typedoc-plugin-no-inherit could not be loaded.
[error] Error: Cannot find module 'typedoc-plugin-no-inherit'

**Comment by tgreyuk** [comment]
> 1. "visibilityfilters" does not work when using the plugin "typedoc-plugin-markdown".
https://typedoc.org/options/output/#visibilityfilters

The TypeDoc `visibilityfilters` option is used to toggle items on and off in-page for the html theme - behaviour not achievable in pure markdown. You can use `excludePrivate` and `excludeProtected` to remove these members from the docs.

> 2. The plugin "typedoc-plugin-no-inherit" has the following errors when using typedoc": "^0.25.4
[error] The plugin typedoc-plugin-no-inherit could not be loaded.

This error suggests that TypeDoc can not locate the plugin. Has it definitely been installed?

**Comment by xiaofeiyun123** [comment]
> Do you have an example repo? Again the issue is that TypeDoc can not resolve this plugin and I am not sure how this could be anything to do with the markdown plugin.

After deleting node_modules, and reinstalling ‘typedoc-plugin-no-inherit’,    it works well.
Thanks a lot!

**Comment by xiaofeiyun123** [comment]
After deleting node_modules, and reinstalling ‘typedoc-plugin-no-inherit’, it works well.
