### ISSUE TITLE
[typedoc-plugin-markdown@next] Packages mode replaces module.index.md in the root output for each package

### ISSUE THREAD

**Issue by adambergman** [tgreyuk/typedoc-plugin-markdown#528]
When using the [`packages` entry point strategy in typedoc](https://typedoc.org/options/input/#packages) and with the `outputFileStrategy` option set to `modules` it appears that the plugin is writing the `module.index.md` file for each package in the root output directory instead of in each package's subdirectory.

In the example repo below (taken from the typedoc documentation), run `npm run docs`. The packages "bar" and "baz" should generate their own `module.index.md` file in their respective directories, but it appears they are each generating their file in the parent folder (root output directory), overwriting the previous one if it exists. After the generation is complete, the `module.index.md` file will contain the content of whichever package was parsed last.

Expected Result:
`docs/@typedoc/bar/module.index.md` - generated doc for /packages/bar/index.ts
`docs/@typedoc/baz/module.index.md` - generated doc for /packages/baz/index.ts
`docs/@typedoc/module.index.md` - no file should exist

Actual Result:
`docs/@typedoc/bar/module.index.md` - does not exist
`docs/@typedoc/baz/module.index.md` - does not exist
`docs/@typedoc/module.index.md` – exists and will be the content of the last package parsed (`packages/baz/index.ts`).

https://github.com/adambergman/typedoc-plugin-markdown-packages-module-index

**Comment by tgreyuk** [comment]
Thanks again for detailed description. Fix in typedoc-plugin-markdown@4.0.0-next.38.

**Comment by adambergman** [comment]
Works perfectly, thanks @tgreyuk
