### ISSUE TITLE
Possible dangerous situation

### ISSUE THREAD

**Issue by cmdcolin** [tgreyuk/typedoc-plugin-markdown#53]
Hi there,
I wanted to use this to generate a documented README in my repo

I ran

    typedoc --theme markdown --out .

This actually blew away the whole directory which was kind of surprising

**Comment by tgreyuk** [comment]
typedoc does replace output folder, however there should be a warning if it is not recognized a typedoc generated folder. The method currently only runs a basic check so will have a look at making this more robust. thanks.

**Comment by tgreyuk** [comment]
output directory checking is now more robust for this plugin. In addition--disableOutputCheck can be used to skip cleaning of the output directory.
