### ISSUE TITLE
Breaks `typedoc-plugin-rename-defaults` (and possibly other ESM plugins)

### ISSUE THREAD

**Issue by NanderTGA** [tgreyuk/typedoc-plugin-markdown#530]
From `typedoc-plugin-rename-defaults` version 0.6.7, the API docs still get generated but don't get detected by Docusaurus (both on v2 and v3) until a rebuild is triggered.
After some research on [this issue (more information here)](https://github.com/felipecrs/typedoc-plugin-rename-defaults/issues/17), it seems that the plugin stopped working properly after they migrated to ESM.
[Reproduction](https://github.com/NanderTGA/typedoc-plugin-rename-default-repro)

**Comment by felipecrs** [comment]
To provide a little more context, @Gerrit0 from TypeDoc suggests that `typedoc-plugin-markdown` may not be handling all promises correctly.

Personally I don't understand how that relates to CommonJS vs ESM, but any help in troubleshooting this issue would be welcome.

A blind idea I had was to migrate `typedoc-plugin-markdown` to ESM as well (which I suppose would happen someday anyway), hoping it may help with the issue.

**Comment by Gerrit0** [comment]
Not the markdown plugin! The docusuaurus plugin.

**Comment by tgreyuk** [comment]
Thanks guys for all of the information. This should be fixed docusaurus-plugin-typedoc@0.22.0. As @Gerrit0 suggested ithe issue appears to be with the way the plugin was handling async stuff. Interestingly the TypeDoc async app methods was being processed correctly but not the dyamic imports of the esm plugins.
