### ISSUE TITLE
Dead links when `useCodeBlocks: true`

### ISSUE THREAD

**Issue by elringus** [tgreyuk/typedoc-plugin-markdown#536]
## Description
When `useCodeBlocks` is enabled, some pages are not generated causing dead links. When `typedoc-plugin-markdown` is not used, the pages are generated, so it doesn't seem to be a typedoc issue.

Tested `typedoc-plugin-markdown` version: `4.0.0-next.39`.

## Repro
1. Clone https://github.com/elringus/imgit/tree/157689cbc3c8914dff9d32c96bb91d3c126c44a7
2. Run following:
 - `cd docs`
 - `npm i`
 - `npm run docs:api`
3. Notice `docs/api/plugin/astro/type-aliases/AstroIntegration.md` file is generated
4. Change `useCodeBlocks` to `true` in `docs/scripts/api.sh`
5. Run `npm run docs:api`
6. Notice  `docs/api/plugin/astro/type-aliases/AstroIntegration.md` is missing

## Expected 
`docs/api/plugin/astro/type-aliases/AstroIntegration.md` is generated when `useCodeBlocks` is enabled

## Note
`AstroIntegration` is not the only file that is missing, run `npm run docs:build` for the full list.

**Comment by tgreyuk** [comment]
Hello and thank you for such a clear description and associated repo.

If you update to `1.0.0-next.6` these issues should be fixed.

I also noticed that you were attempting to tweak a few bits to the output that can actually be accomplished with existing TypeDoc options.

- [githubPages](https://typedoc.org/options/output/#githubpages) removes the `.nojekyll` file.
- Setting [readme](https://typedoc.org/options/input/#readme)  to `none` makes the `index.md` page the docs index page.
- [hideGenerator](https://typedoc.org/options/output/#hidegenerator) does not print the links in the footer.

In addition I have added an additional `collapsed` option to the VitePress [sidebar](https://www.typedoc-plugin-markdown.org/themes/vitepress/options#sidebar) object.

This is what my new `api.sh` looks like with `v1.0.0-next.6`:

```
echo '{
    "entryPoints": [
        "../src/server/index.ts",
        "../src/plugin/youtube/index.ts",
        "../src/plugin/svg.ts",
        "../src/plugin/astro.ts",
        "../src/plugin/vite.ts"
    ],
    "tsconfig": "../src/tsconfig.json",
    "hideBreadcrumbs": true,
    "useCodeBlocks": true,
    "out": "api",
    "textContentMappings": {
        "title.indexPage": "API Reference",
        "title.memberPage": "{name}",
    },
    "plugin": ["typedoc-plugin-markdown", "typedoc-vitepress-theme"],

    "githubPages": false,
    "readme": "none",
    "hideGenerator": true,
    "sidebar": {
        "collapsed": false
    }

}' > typedoc.json

typedoc
```

**Comment by elringus** [comment]
Thank you so much for the fast fix and the example! It's now all working perfectly. I've actually hacked the sidebar collapse because it used to show expand icons next to items that couldn't be expanded, but it seems to be fixed now as well. The plugin is brilliant, thanks again!
