### ISSUE TITLE
Vitepress: Use `textContentMappings` for sidebar?

### ISSUE THREAD

**Issue by gossi** [tgreyuk/typedoc-plugin-markdown#546]
I make use of [`textContentMappings`](https://www.typedoc-plugin-markdown.org/options#textcontentmappings) for some selected strings:

```json
{
  "textContentMappings": {
    "kind.typeAlias.singular": "Type",
    "kind.typeAlias.plural": "Types",
  }
}
```

That is of course for the `typedoc-plugin-markdown` plugin. The `typedoc-vitepress-theme` yet relies on that one and fills the sidebar, that is the labels are different right now for me.

Wanted to raise the question if it would make sense to also use the `textContentMappings` from the vitepress plugin, too?

**Comment by tgreyuk** [comment]
yes agreed it should - i'll fix it.

**Comment by tgreyuk** [comment]
Fixed in:

```
"typedoc-plugin-markdown": "^4.0.0-next.45",
"typedoc-vitepress-theme": "^1.0.0-next.8",
```
