### ISSUE TITLE
repeated sections when i tagged my functions with @group 

### ISSUE THREAD

**Issue by marcog83** [tgreyuk/typedoc-plugin-markdown#547]
Hi, thanks for the great job.
i'm using this plugin to create md files, and when i add @group tag to my functions it doesn't group by the tag. instead it repeats the name of the group, as if it creates different groups for each tag

<img width="598" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/4071265/becdc0c9-6a81-4576-8b36-af372ce959d4">

**Comment by tgreyuk** [comment]
This output doesn't look familiar. For context would you mind copying and pasting in the source code that produces the example please?

**Comment by marcog83** [comment]
Hi sure

```ts
// from useCreateOrUpdateByApplication.ts

/**
 * @group Hooks
 * A hook to create or update all the user preferences for an `application`
 */

export const useCreateOrUpdateByApplication = …


// from useCreateOrUpdateByPreferenceName.ts

/**
 * @group Hooks
 * A hook to create or update a user preferences
 *
 * */
export const useCreateOrUpdateByPreferenceName = …

// from UserPreferencesProvider.ts

/**
 * @category Providers
 *
 * @typeParam ApiConfig
 */
export const UserPreferencesProvider:FC<ApiConfig> =


// index.ts

export { useCreateOrUpdateByApplication } from './hooks/use-create-update-by-application';
export { useCreateOrUpdateByPreferenceName } from './hooks/use-create-update-by-preference-name';

export { useUserPreferences, UserPreferencesProvider } from '@contexts/user-preferences';

// from typedoc.json

{
  // Comments are supported, like tsconfig.json
    "entryPoints": ["src/index.ts"],
    "out": "dist/md",
    "plugin": ["typedoc-plugin-markdown"],
    "categorizeByGroup":true,
  "hideBreadcrumbs":true,
  "hidePageTitle":true,
  "hideMembersSymbol":true
}

```

**Comment by marcog83** [comment]
Hi @tgreyuk , i played a bit with the configuration and it was my configuration's fault. the plugin works great :). I think you can close this "no-issue". sorry for bother you

At the end I switched from `@group` to `@category`.

this is my new configuration

```json
{
  // Comments are supported, like tsconfig.json
    "entryPoints": ["src/index.ts"],
    "out": "dist/md",
    "categorizeByGroup":false,
    "plugin": ["typedoc-plugin-markdown"],
   
   "hideBreadcrumbs":true,
  "hidePageTitle":true,
  "categoryOrder": [
    "Providers",
    "Hooks",
    "Options Type",
    "*"
  ]
}
```
One thing to highlight is that the tag @category must be the last one in the comment, otherwise typedoc seems to consider also the lines below as part of the category.

```ts

 // DOESN'T WORK
/**
@category Hooks
this is my hook description
*/

 // IT WORKS
/**

this is my hook description 
@category Hooks
*/
```

**Comment by tgreyuk** [comment]
ok thanks for clarification. i have checked the @group tags behaviour and I 'think' it is doing what it's supposed to do. Please do re-open though if you come across anything else.
