### ISSUE TITLE
Missing comments in interface in table mode

### ISSUE THREAD

**Issue by aosnow** [tgreyuk/typedoc-plugin-markdown#551]
Missing comments in interface in table mode(`"propertiesFormat": "table"`), the source code is as follows, 
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3865017/33c2dd64-e84e-4102-89af-51dc3125c45a)

but the comments were lost after construction
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3865017/f68fc0d2-e2cf-43e9-8470-13e3e34f8250)

**Comment by tgreyuk** [comment]
I am not seeing quite the same results. Is your repo public? If not could you please past the full source of `IExpandForm` and `FormInstance` please?
