### ISSUE TITLE
Handling case sensitive files is broken

### ISSUE THREAD

**Issue by gossi** [tgreyuk/typedoc-plugin-markdown#555]
Here is my situation

- I have a [`LinkHelper`](https://github.com/buschtoens/ember-link/blob/486caf355b26c699f597b88629aa94431577324c/ember-link/src/helpers/link.ts#L37) class, that is exported as [`link`](https://github.com/buschtoens/ember-link/blob/486caf355b26c699f597b88629aa94431577324c/ember-link/src/index.ts#L13)
- I have a [`Link`](https://github.com/buschtoens/ember-link/blob/486caf355b26c699f597b88629aa94431577324c/ember-link/src/link.ts#L16) class, that is exported as [`Link`](https://github.com/buschtoens/ember-link/blob/486caf355b26c699f597b88629aa94431577324c/ember-link/src/index.ts#L14)

There is

- `link` vs
- `Link`

That's a case the markdown plugin cannot handle very well, here is my PR in which I tried to update the existing vitepress docs with the new plugin: buschtoens/ember-link#793 (repro manual at the end of this post)

## Markdown

- there is `ember-link/classes/Link.md` (which is the `LinkHelper`)
- that's the only of the two files created

## Vitepress Integration

That's the error in the console, when I open `Link`:

<img width="836" alt="Bildschirmfoto 2024-01-28 um 10 52 37" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/283700/824cce11-6ec5-4fbe-aed0-fd11aacb7c84">

Interesting to see, it comes to `set` -> `Ember` (or is it `Ember.set` ?) at the end. Even though that is quite old code (before there were classes in JS), that shouldn't break, no?

What works though, is the sidebar is correct:

<img width="227" alt="Bildschirmfoto 2024-01-28 um 10 55 04" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/283700/5469f6d5-59bd-463b-8954-4ef13cfa4c31">

## Reproduction

Here is the reproduction with a manual:

1. Check out buschtoens/ember-link#793
2. Install `pnpm install`
3. Into ember-link folder: `cd ember-link/` and generate API with: `pnpm api`
4. Go back into repo root: `cd ../` and start vitepress: `pnpm docs:dev`
5. Open the link and navigate to the API (top right navigation)

**Comment by tgreyuk** [comment]
Thanks.

So the plugin now produces the following files in this scenario.

- Link.md
- link-1.md

**Fix versions:**

```
"typedoc-plugin-markdown": "^4.0.0-next.45",
"typedoc-vitepress-theme": "^1.0.0-next.8",
```

**Result**

![2024-01-30 22 05 57](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/5638a956-adcb-49cc-869e-530ab8d442ea)
