### ISSUE TITLE
`<` and `>` character are prefixed with `\` in breadcrumb and sidebar title

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#557]
<img width="517" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/42176370/61400c1b-0038-43e9-a91f-1d46b5fb6f0e">

I am using the following dependencies

- "typedoc-plugin-markdown": "4.0.0-next.43"
- "typedoc": "0.25.7"
- "docusaurus-plugin-typedoc": "1.0.0-next.25"

Here is the `EventEmitter` code in typescript, it is a generic type.

```ts
  /**
   * A class to create and manage an {@link Event} for clients to subscribe to.
   * The emitter can only send one kind of event.
   *
   * Use this class to send events inside extension or provide API to the other
   * extensions.
   */
  export class EventEmitter<T> {
    /**
     * For the public to allow to subscribe to events from this Emitter
     */
    event: Event<T>;
    /**
     * To fire an event to the subscribers
     * @param event The event to send to the registered listeners
     */
    fire(data: T): void;
    /**
     * Dispose by removing registered listeners
     */
    dispose(): void;
  }
```

**Comment by nicfv** [comment]
I've experienced this in other areas as well:

![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/24358775/0dff8143-f8da-4a19-a8ce-10841631b93b)

**Comment by tgreyuk** [comment]
So the plugin isn't designed to be used with an auto sidebar configuration. If you follow the instructions here https://www.typedoc-plugin-markdown.org/integrations/docusaurus/guides/sidebar , then you won't experience these issues. You can use a mixture of autogenerated and manual config by using sidebar slices (if required).
