### ISSUE TITLE
Error: Invalid sidebar file

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#558]
Using the following dependencies
- typedoc-plugin-markdown [4.0.0-next.44](https://www.npmjs.com/package/typedoc-plugin-markdown/v/4.0.0-next.44)
- docusaurus-plugin-typedoc [1.0.0-next.26](https://www.npmjs.com/package/docusaurus-plugin-typedoc/v/1.0.0-next.26)

I am using [integrations/docusaurus/sidebar](https://www.typedoc-plugin-markdown.org/integrations/docusaurus/guides/sidebar) as recommended by @tgreyuk in https://github.com/tgreyuk/typedoc-plugin-markdown/issues/557#issuecomment-1917384674

However, I am getting a small issue about the document ids:

```trace
[info] Documentation generated at ./api
[ERROR] Loading of version failed for version current
Error: Invalid sidebar file at "sidebars-api.js".
These sidebar document ids do not exist:
- /classes/Disposable
- /classes/EventEmitter
....
Available document ids are:
- classes/Disposable
- classes/EventEmitter
....
```

It seems that a `/` is prefixed and not expected. Leading to an error.

## Current configuration

I am generating the documentation in its own documentation (`./api`).

Here is the interesting part of `docusaurus.config.js`
```ts
...
[
  '@docusaurus/plugin-content-docs',
  {
    id: 'api',
    path: 'api',
    routeBasePath: 'api',
    sidebarPath: resolve('./sidebars-api.js'),
  },
],
[
  'docusaurus-plugin-typedoc',
  {
    id: 'api',
    plugin: ['typedoc-plugin-markdown'],
    entryPoints: [resolve('../packages/extension-api.d.ts')],
    out: 'api',
    hideBreadcrumbs: true,
    readme: 'none',
    tsconfig: resolve('../packages/extension-api/tsconfig.json'),
  },
],
...
```

The `sidebars-api.json`
```
const sidebars = {
  typedocSidebar: [
    {
      type: 'category',
      label: 'Typedoc API',
      link: {
        type: 'doc',
        id: 'api',
      },
      items: require('./api/typedoc-sidebar.cjs'),
    },
  ],
};
module.exports = sidebars;
```

**Comment by tgreyuk** [comment]
Thanks. Yeah the plugin wasn't handling an alternative `routeBasePath`.

Should be working correctly in following versions:

docusaurus-plugin-typedoc@1.0.0-next.27
typedoc-plugin-markdown@4.0.0-next.45

**Comment by axel7083** [comment]
Perfect, @tgreyuk thanks you very much for your great work ! 

To make it work with the new version I just had to change the link property in the sidebars-api.js 

```
link: {
        type: 'doc',
        id: 'index,
      },
```
