### ISSUE TITLE
`footer.generator` value not used in textContentMappings

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#561]
Using the following dependencies

- docusaurus-plugin-typedoc `1.0.0-next.27`
- typedoc-plugin-markdown `4.0.0-next.45`

The following config in docusaurus.config.js is used

```ts
...
[
      'docusaurus-plugin-typedoc',
      {
        id: 'api',
        plugin: ['typedoc-plugin-markdown'],
        entryPoints: [resolve('../packages/extension-api/src/extension-api.d.ts')],
        out: 'api',
        hideBreadcrumbs: true,
        readme: 'none',
        tsconfig: resolve('../packages/extension-api/tsconfig.json'),
        textContentMappings: {
          'footer.generator': '?',
        },
      },
    ],
...
```

However, I am getting the following in all markdown generated

```
***

Generated using [TypeDoc](https://typedoc.org) and [typedoc-plugin-markdown](https://typedoc-plugin-markdown.org).
```

**Comment by tgreyuk** [comment]
Thanks. Out of interest are you going to replace the text with something else or trying to get rid of the generator with an empty string. I ask because it can be removed from the output completely with `hideGenerator: true`.

**Comment by axel7083** [comment]
> Thanks. Out of interest are you going to replace the text with something else or trying to get rid of the generator with an empty string. I ask because it can be removed from the output completely with `hideGenerator: true`.

I will remove it completely

**Comment by tgreyuk** [comment]
> I will remove it completely

ok cool - use `hideGenerator` for now. I'm actually thinking about just getting rid of it completely.

**Comment by tgreyuk** [comment]
Closing as generator text is now omitted as default.
