### ISSUE TITLE
typedoc-plugin-markdown group headings all labelled "undefined"

### ISSUE THREAD

**Issue by paularmstrong** [tgreyuk/typedoc-plugin-markdown#568]
When using `@group` or `@category` tags in the tsdoc comments, the resulting headings appear as `undefined`. The first breaking version is 4.0.0-next.44 and is still present in .49

## Input:

```ts
/**
 * @group Tacos
 */
export …
```

## Output:

```md
## undefined
```

**Comment by tgreyuk** [comment]
thanks - fixed in `typedoc-plugin-markdown@4.0.0-next.50`

**Comment by paularmstrong** [comment]
Awesome thank you!
