### ISSUE TITLE
mdPagesSourcePath cannot accessed from typedoc-webpack-plugin

### ISSUE THREAD

**Issue by gdbd** [tgreyuk/typedoc-plugin-markdown#57]
i am use typedoc-webpack-plugin like this:

```
  var typeDocPlugin = new TypedocWebpackPlugin(
            {
               mdPagesSourcePath: './backend/test-page',
              /// other settings            
            }
        );
```

and get this error: 
```Error: Failed to get page collection. Error: Failed to get pages source path from options. Error: Pages source path must be specified.```

It is possible to fix and use plugins together?

**Comment by tgreyuk** [comment]
Hi @gdbd . Apologies but not sure what mdPagesSourcePath refers to it is not an option from the plugin. The plugin will work happily with the webpack-plugin.

**Comment by tgreyuk** [comment]
@gdbd wrong package - see https://github.com/mipatterson/typedoc-plugin-markdown-pages
