### ISSUE TITLE
markdown generated using triple quote making it icompatible with current docusaurus system

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#578]
In our system we have a broken link detected by docusaurus __when it is not a broken link__ after long investigation it comes from a bug in the docusaurus codebase.

See https://github.com/facebook/docusaurus/issues/9876 for full discussion and the following comment on explanation https://github.com/facebook/docusaurus/issues/9876#issuecomment-1959197272

**Comment by slorber** [comment]
Hey

I wouldn't say it is "improper Markdown", after all this form of Markdown inline code blocks with triple backticks cause issues in Docusaurus, but apparently it's perfectly fine for MDX:

````md
```something```

[test](test.md)
````

However, if you can migrate this kind of code to simple backticks, that would solve the problem on the Docusaurus side:

````md
```something```

[test](test.md)
````

**Comment by axel7083** [comment]
@slorber sorry for the wrong terminology!

**Comment by axel7083** [comment]
Closing, as after investigation, we were the one, using triple quotes in our code comments. Which where just copy past by the plugin here.
