### ISSUE TITLE
exclude

### ISSUE THREAD

**Issue by ozum** [tgreyuk/typedoc-plugin-markdown#58]
Using `--excludePrivate`, if none of the private properties have description they are included in generated doc:

## OK

`--excludePrivate`

```ts
/**
 * Logger  of data file
 */
private readonly _logger: Logger;
private readonly _option: Logger;
```

## Shows private properties

`--excludePrivate`

```ts
private readonly _logger: Logger;
private readonly _option: Logger;
```

**Comment by tgreyuk** [comment]
These properties would be excluded at the converter stage before the plugin has loaded. Even so I was not actually able to reproduce this behaviour.

**Comment by ozum** [comment]
@tgreyuk, I don't have the example at hand currently, because I added lots of docs. Thanks anyway.
