### ISSUE TITLE
Getting extra spaces before a function parameter

### ISSUE THREAD

**Issue by ocavue** [tgreyuk/typedoc-plugin-markdown#580]
Giving the following source code,

```ts
export function fn(
  a: () => number,
  b: number,
  c: GetNum,
): void {
  console.log(a() + b + c())
}

export type GetNum = () => number
```

And the following typedoc config,

```json
{
    "plugin": [
        "typedoc-plugin-markdown",
    ],
    "useCodeBlocks": true,
    "expandParameters": true,
}
```

I get the result below:

``````markdown
# Function: fn()

```ts
fn(
   a:     () => number, 
   b: number, 
   c: GetNum): void
```
``````

Notice that there are some extra spaces after `a`. 

Minimal reproduction:

https://githubbox.com/issueset/typedoc-plugin-markdown-function-param

**Comment by tgreyuk** [comment]
Thank you - will fix this. 

On a related note, you can actually format the output with Prettier using typedoc-plugin-remark. Example output here - https://github.com/tgreyuk/typedoc-plugin-markdown-examples/tree/main/examples/03-typedoc-plugin-remark#prettier.

**Comment by ocavue** [comment]
Oh thanks. I didn't know about `typedoc-plugin-remark` before. 

For this particular code block, Prettier cannot format it. I found that I need to add a `function` keyword at the beginning to make Prettier work. I can achieve this by overriding [`helpers.getKeyword`](https://github.com/ocavue/aria-ui/blob/a67b4241777f7580cb4797bc888e5ae64844f247/packages/typedoc-plugin/src/index.ts#L105-L111). `typedoc-plugin-markdown`'s API is very flexible and I love it. 


```ts
// Prettier cannot format this
fn(
   a:     () => number, 
   b: number, 
   c: GetNum): void
```


```ts
// Prettier can format this
function fn(
   a:     () => number, 
   b: number, 
   c: GetNum): void
```

**Comment by tgreyuk** [comment]
Thanks - thats a good spot actually. The function keyword should be present when `useCodeBlocks` are enabled.
