### ISSUE TITLE
`TypeDoc exited with an error` but got exit code 0

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#583]
In our CI pipeline we were not able to caught an error in the building process

Here are the final logs. We got the logs stating there are an error, but still got an exit code 0, allowing the pipeline to continue its job.

```
[docusaurus-plugin-typedoc] TypeDoc exited with an error. Use the "skipErrorChecking" option to disable TypeDoc error checking.
Done in 16.47s.
```

**Comment by tgreyuk** [comment]
Released in docusaurus-plugin-typedoc@1.0.0-next.28
