### ISSUE TITLE
Cannot read property 'shortText' of undefined

### ISSUE THREAD

**Issue by ozum** [tgreyuk/typedoc-plugin-markdown#60]
I got following error using 2.0.0.

Since error messages does not indicate where the problem is in my source files, I uploaded my project which produces error (it's open source) here: https://we.tl/t-SmU4D0u44Y

```
.../markdown/dist/theme/helpers/parameter-table.js:26
      if (parameter.comment.shortText) {
                            ^

TypeError: Cannot read property 'shortText' of undefined
    at .../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:26:29
    at Array.map (<anonymous>)
    at Array.parameterTable (.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:18:21)
...
```

After I changed `if(parameter.comment.shortText)` and `if (parameter.comment.text)` in `dist/theme/helpers/parameter-table.js` to `if(parameter && parameter.comment.shortText)` and `if (parameter && parameter.comment.text)`, I got

```
.../markdown/dist/theme/helpers/parameter-table.js:26
      if (parameter && parameter.comment.shortText) {
                                         ^

TypeError: Cannot read property 'shortText' of undefined
    at .../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:26:42
    at Array.map (<anonymous>)
    at Array.parameterTable (.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:18:21)
    at eval (eval at createFunctionContext (.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:197)
```

**Comment by tgreyuk** [comment]
@ozum Thanks will look at this asap.

**Comment by tgreyuk** [comment]
@ozum Could you please try with new version (2.0.1) when you get a chance. thanks...

**Comment by ozum** [comment]
@tgreyuk exact same error still exists.

**Comment by ozum** [comment]
@tgreyuk is it possible to npm package not updated?

I still see `if (parameter.comment.shortText)` from npm isntall (2.0.1) but see ` if (parameter.comment && parameter.comment.text)` in github?

**Comment by tgreyuk** [comment]
i think prob still error - sorry.. Do you have the actual source that is causing the issue (i couldnt seem to ascertain by following the above link)

**Comment by ozum** [comment]
Is there any way to get what part of the source code causes problem from typedoc?

**Comment by ozum** [comment]
@tgreyuk please download https://we.tl/t-ynPsdkB6SP

Problem part is `parseEnv` method `src/main.module/intermodular.ts` at line 152.

If I comment out that part, it completes after I changed `if(parameter.comment.shortText)` parts into `if(parameter && parameter.comment && parameter.comment.shortText)`.

Problems I see:
* npm package 2.0.1 does not have `if(parameter && parameter.comment && parameter.comment.shortText)`whereas github code has.
* named parameters still not shown (see src/main.module/intermodular.ts constructor)
* Not sure if this is a bug or expected: All files are shown as global even using --mode file (version 1 did not show them as globals)

Hope helps,

**Comment by tgreyuk** [comment]
Thanks @ozum thanks no this all looks very strange i will try and work out whats going on. I have the source now - thanks.

**Comment by jacogr** [comment]
Same error for us. (I bumped straight from 1.x to 2.0.1) Cannot quite see which part makes it really unhappy.

**Comment by jacogr** [comment]
Same error for us. (I bumped straight from 1.x to 2.0.1) Cannot quite see which part makes it really unhappy.

**Comment by tgreyuk** [comment]
@ozum thanks for your patience :) . 2.0.4 should have the required fixes 

* I had screwed up the publish script previously so version was not getting updated.

* Named params is looking better as per image.

<img width="908" alt="named params" src="https://user-images.githubusercontent.com/11680870/59644956-377b5780-9167-11e9-9ee7-8c7b62634422.png">

* The file mode is now being treated correctly (i think!!)

**Comment by jacogr** [comment]
Brilliant, thank you, `2.0.4` solves it for our use.

**Comment by ozum** [comment]
@tgreyuk thanks, throw problem seems solved.

I still cannot get named parameters using 2.0.4. Did I miss some step? Below is steps I followed:

![image](https://user-images.githubusercontent.com/1497060/59665659-02e5bb00-91bc-11e9-897e-f74154bbc647.png)

1. I downloaded https://we.tl/t-ynPsdkB6SP
1. Changed `typedoc-plugin-markdown` to 2.0.4 in `package.json`
1. `$ npm install`
1. `$ npm run doc:md`
1. `$ pico doc/md/classes/intermodular.md`

**Comment by tgreyuk** [comment]
@ozum I think I have got to the bottom of the missing named parameters. You are seeing a difference between the default theme and the md theme because you have `--excludeNotExported` set on the markdown build. If I add this argument to default theme the same behaviour is noted as below:

![image](https://user-images.githubusercontent.com/11680870/59720541-0c504100-9217-11e9-831c-d48ad0704d2b.png)

Likewise if you remove `--excludeNotExported` from the md build then you will get the required behaviour.

**Comment by tgreyuk** [comment]
@ozum closing this ticket as can't fix the namedParameters issue at plugin level. FYI these tickets look related:

https://github.com/TypeStrong/typedoc/issues/987
https://github.com/TypeStrong/typedoc/issues/1000
