### ISSUE TITLE
strips whitespace in fenced examples

### ISSUE THREAD

**Issue by Zemnmez** [tgreyuk/typedoc-plugin-markdown#63]
I'm generating my readme files using `typedoc-plugin-markdown`, but it always strips whitespace from my example annotations making them look bad. Is there a way to fix this?

See: https://github.com/Zemnmez/react-storage-hook/blob/885449502f7d13428e73013822e41b747fd4ddd1/README.md

**Comment by tgreyuk** [comment]
Fixed in 2.0.7

**Comment by Zemnmez** [comment]
thank you!!
