### ISSUE TITLE
typedoc-plugin-markdown@2.07 strips @example tags from module members

### ISSUE THREAD

**Issue by Zemnmez** [tgreyuk/typedoc-plugin-markdown#66]
I have some scripts that inject `@example` tags into my jsdoc with files. Was surprised to find that they get stripped by this plugin:

| | |
|--|--|
| generated markdown | https://github.com/Zemnmez/react-dom-observer/blob/weird-example-stripping/README.md#const-useintersectionobserver | 
| original code | https://github.com/Zemnmez/react-dom-observer/blob/weird-example-stripping/src/index.tsx#L254 |

This seems to be different from a module annotation, where it's instead presented as
```markdown
**example**
```

**Comment by tgreyuk** [comment]
Thanks @Zemnmez. I am observing the same behaviour with the default theme so I am not sure if it an issue with the plugin per se. However will try and figure out what the issue is.

**Comment by Zemnmez** [comment]
super appreciate all your work on this! please let me know how / if I can help!

**Comment by tgreyuk** [comment]
Reviewing old ticket and i notice this is fixed in latest versions. Not sure if issue was with TypeDoc or this plugin.
