### ISSUE TITLE
Invalid Meta Data

### ISSUE THREAD

**Issue by ozum** [tgreyuk/typedoc-plugin-markdown#68]
Hi,

After I updated to latest version

`/src/lib/theme/helpers/metadata.ts` line 13

```ts
const md = `---
id: ${getId(this)}
title: ${getReflectionTitle(this)}
sidebar_label: ${getLabel(this)}
---\n`;
```

produces below meta data part, which is invalid because of `title: Class: DataFile`

```
---
id: datafile
title: Class: DataFile
sidebar_label: DataFile
---
```

Kind regards,

**Comment by tgreyuk** [comment]
Apologies have fixed this in 2.0.9.
