### ISSUE TITLE
cannot ignore destructured assignment

### ISSUE THREAD

**Issue by ozum** [tgreyuk/typedoc-plugin-markdown#69]
Hi,

I'm not sure if this is related to `typedoc-plugin-markdown` or `typedoc`. I can't compare output with bare `typedoc`, because I cannot see those variables in bare `typedoc`.

```ts
/** @ignore */
const em = chalk.yellow;
/** @ignore */
const { red, green } = chalk;
```

did not ignore `red` and `green`:

###  green

• **green**: *`Chalk` & object*

*Defined in [messages.ts:20](https://github.com/ozum/intermodular/blob/4dd044c/src/messages.ts#L20)*

___

###  red

• **red**: *`Chalk` & object*

*Defined in [messages.ts:20](https://github.com/ozum/intermodular/blob/4dd044c/src/messages.ts#L20)*

**Comment by tgreyuk** [comment]
@ozum yes i am observing the same behaviour on typedoc default theme. will have a proper look when i have some time but I think this will be one for typedoc as this is the model provided.

**Comment by tgreyuk** [comment]
Just reviewing old tickets. Have retested this and this syntax works:
```
const {
  /** @ignore */
  red,
  /** @ignore */
  green,
} = chalk;
```
