### ISSUE TITLE
Not generating anchors for Bitbucket

### ISSUE THREAD

**Issue by ncipollina** [tgreyuk/typedoc-plugin-markdown#74]
When using this documentation generator for Bitbucket, it is generating the links, but not the anchor tags for an item that it links to.  For example in one of my classes, it's generating the following for the constructor at the top of the file:

```
* [constructor](handler.md#markdown-header-constructor)
```

But there is no anchor tag on the actual constructor. The constructor documentation looks like this:

```
###  constructor

\+ **new Handler**(`controller`: `TController`, `event`: `APIGatewayEvent`): *[Handler](handler.md)*

Defined in handlers/base.handler.ts:14

**Parameters:**

Name | Type |
------ | ------ |
`controller` | `TController` |
`event` | `APIGatewayEvent` |

**Returns:** *[Handler](handler.md)*

```

In order for the link to work in bitbucket, it should look like this:

```
### <a name="markdown-header-constructor"></a> constructor
```

**Comment by tgreyuk** [comment]
Interesting the example looks ok to me and this is an accepted implementation as per https://community.atlassian.com/t5/Bitbucket-questions/Markdown-internal-links-support-in-Bitbucket-Server/qaq-p/595033 .

Also the anchor tags are excaped on bitbucket cloud:
![image](https://user-images.githubusercontent.com/11680870/61910836-9b92f780-af2d-11e9-8b72-153f5e03884c.png)

Are you running on Bitbucket server or cloud?

**Comment by ncipollina** [comment]
In our instance, it's Bitbucket server.

**Comment by tgreyuk** [comment]
@nilennoct ok thanks. After looking into this it appears that Bitbucket server does not auto assign ids to headers.

What I have done is introduce a new argument in 2.1.0 `namedAnchors` that should solve your use case?

```
--namedAnchors
Use HTML named anchors as fragment identifiers for engines that do not automatically assign header ids.
```

I hope this solves your problem.

Thanks...

**Comment by ncipollina** [comment]
@tgreyuk, this did the trick! Thanks for the quick response!
