### ISSUE TITLE
Links not Working when Displayed in Azure DevOps Wiki

### ISSUE THREAD

**Issue by ps-from-md** [tgreyuk/typedoc-plugin-markdown#75]
So far this has been working well for me, with only one exception.  This is the command I am running to generate documentation:

`
typedoc --theme markdown --namedAnchors --platform docusaurus --out ./docs
`

In Azure DevOps I have a wiki configured to pull markdown files from code (see this [description](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops))

The links that are generated in the wiki (which I believe is just exposing the .MD files,) do not work.  They appear to be anchors to areas lower in the page but when  you click on them nothing happens.

Here is an example of the URL
`
_wiki/wikis/admin?pagePath=%2Fmodules%2F_admin_&wikiVersion=GBmaster&pageId=27&anchor=const-admin_list_create_fulfilled
`

I do not see any errors  in the console and the links on the main page (Globals) work when linking to the child MD files.

Is there a workaround for this?

**Comment by tgreyuk** [comment]
@ps-from-md  Can you please try again with updated version (2.1.1). Adding ids to named html anchors appears to fix the issue. Thanks.
