### ISSUE TITLE
enhancement: custom platform

### ISSUE THREAD

**Issue by boneskull** [tgreyuk/typedoc-plugin-markdown#79]
Thanks for this plugin!

I'd like to use a custom "platform".  My use case is consuming the output of typedoc + typedoc-plugin-markdown in a Gatsby site.  To that end, I want to prepend custom frontmatter to the output.

Would you be interested in implementing this, or accepting a PR which would?

Currently investigating other ways to prepend frontmatter.

**Comment by tgreyuk** [comment]
@boneskull yes for sure. If I don't receive any prs will look at as soon as possible...

**Comment by tgreyuk** [comment]
You make a fair point. As you say the 'platforms' themes are just subclasses of the MarkdownTheme (which is itself is a subclass of typedoc 'Theme' class). I suppose the whole 'platform' concept was a bit of an add-on (and actually a bit of a distraction).  I think other plugins consuming the MarkdownTheme probably works better architecturally (i will give it a go). Also Front Matter should be provided as an option rather than being bound to certain themes.

**Comment by tgreyuk** [comment]
You have got me thinking that there is actually no requirement for an Markdown file extension. Examples of extension usage could be markdown, mdown, mkdn, mkd, md etc (or none in your case).

I was thinking proving an additional argument could work in this instance. Something like:

```
--fileExt
Markdown file extension. Pass `none` to omit file extension. Defaults to `md`.
```

This option would then be used by the renderer when building the urls, irrespective of the 'theme'.

Does this seem reasonable or is it a bit simplistic?

**Comment by boneskull** [comment]
I mean, you could add all manner of options... :smile:

It really just comes down to if you would rather do that (and maintain it) or refactor things in such a way that a user could extend the root theme however they see fit.

**Comment by tgreyuk** [comment]
Yep - i hear you.... will have a little play.

**Comment by boneskull** [comment]
@tgreyuk Great work!  This is pretty much exactly what I needed.  I was able to whip up a quick theme that does what I need:

```js
const {DefaultTheme, UrlMapping} = require('typedoc');
const {default: MarkdownTheme} = require('typedoc-plugin-markdown/dist/theme');
const {
  FrontMatterComponent
} = require('typedoc-plugin-markdown/dist/components/front-matter.component');

// all I need here is the "title", but may add more later
class GatsbyFrontMatter extends FrontMatterComponent {
  getYamlString(page) {
    const yaml = `---
title: "${this.escapeYAMLString(this.getTitle(page))}"
---`;
    return yaml;
  }
}

module.exports = class GatsbyMarkdownTheme extends MarkdownTheme {
  constructor(renderer, basePath) {
    super(renderer, basePath);

    this.indexName = 'index';

    renderer.addComponent('frontmatter', new GatsbyFrontMatter(renderer));
  }

  // must remove trailing file extension from relative urls
  buildUrls(reflection, urls) {
    const mapping = DefaultTheme.getMapping(reflection);
    if (mapping) {
      if (!reflection.url || !DefaultTheme.URL_PREFIX.test(reflection.url)) {
        const url = mapping.directory + '/' + DefaultTheme.getUrl(reflection);
        urls.push(new UrlMapping(url, reflection, mapping.template));
        reflection.url = url;
        reflection.hasOwnDocument = true;
      }
      for (const child of reflection.children || []) {
        if (mapping.isLeaf) {
          this.applyAnchorUrl(child, reflection);
        } else {
          this.buildUrls(child, urls);
        }
      }
    } else if (reflection.parent) {
      this.applyAnchorUrl(reflection, reflection.parent);
    }
    return urls;
  }
};
```

A couple suggestions/questions:

1. Maybe break up `buildUrls()` into separate functions.  All I needed to do differently in my implementation was to remove `+ this.fileExt`. from the `const url  = ..` line
1. I'm not sure I understand why `theme.js` is the convention.  Why not go with `index.js` and let node's module resolution figure it out?
1. Can anything else other than `partials` be "shadowed", like `helpers`?

**Comment by tgreyuk** [comment]
@boneskull thanks..

1) Good suggestion - i will have a look at breaking buildUrls down.

2) This is how TypeDoc core internally loads a custom theme https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/renderer.ts#L203 - 

3) Yes you can shadow and/or write your own helpers. Add custom helpers to a helpers directory and TypeDoc will then register them.

helpers/custom-helper.js
```
exports.customHelper = () => {
  return 'MY CUSTOM HELPER';
};
```
partials/header.hbs
```
Custom header
{{customHelper}}
```

**Comment by tgreyuk** [comment]
Have split out buildUrls so you can replace the above with:
```
toUrl(mapping, reflection) {
    return mapping.directory + '/' + this.getUrl(reflection);
  }
```

However if you just wanted to remove file ext you could also just set an empty fileExt:
```
this.fileExt = ''
```

**Comment by boneskull** [comment]
I can’t do that because the _files_ need an extension, but the URLs don’t. thanks, I’ll use this!

**Comment by boneskull** [comment]
I think I spoke too soon--it seems the files _do_ get rendered without their extensions either way (I think I was just looking at `globals.md`, which has a hardcoded extension).  So I need to figure out how to _only_ strip the extension from within the template.  I think I can use a custom helper here

**Comment by boneskull** [comment]
for now I just monkeypatched it:

```js

const relativeURL = Handlebars.helpers.relativeURL;
Handlebars.helpers.relativeURL = url => {
  return relativeURL(url).replace(/\..+$/, '');
};
```

**Comment by boneskull** [comment]
(the above doesn't _quite_ work, but thats the strategy, anyhow)

**Comment by boneskull** [comment]
OK, I've fixed my issues.  My complete implementation does two things of note (I'm dumping this here in case someone else can use it):

1. it removes a leading `_` from filenames (and URLs), since `gatsby-source-filesystem` doesn't like this.
1. it strips `.md` from URLs.  anchors remain in place, e.g., `foo.md#bar` becomes `foo#bar`

```js
const {ProjectReflection} = require('typedoc');
const Handlebars = require('handlebars');
const {default: MarkdownTheme} = require('typedoc-plugin-markdown/dist/theme');
const {
  FrontMatterComponent
} = require('typedoc-plugin-markdown/dist/components/front-matter.component');

class GatsbyFrontMatter extends FrontMatterComponent {
  /**
   * @param {import('typedoc/dist/lib/output/events').PageEvent} page
   */
  getYamlString(page) {
    const yaml = `---
title: "${this.escapeYAMLString(this.getTitle(page))}"
---`;
    return yaml;
  }
}

const relativeURL = Handlebars.helpers.relativeURL;
Handlebars.helpers.relativeURL = /** @param {string} url */ url =>
  relativeURL(url).replace('.md', '');

module.exports = class GatsbyMarkdownTheme extends MarkdownTheme {
  /**
   * @param {import('typedoc').Renderer} renderer
   * @param {string} basePath
   */
  constructor(renderer, basePath) {
    super(renderer, basePath);

    this.indexName = 'index';

    renderer.addComponent('frontmatter', new GatsbyFrontMatter(renderer));
  }

  /**
   * @param {import('typedoc').Reflection} reflection
   * @param {import('typedoc').Reflection?} relative
   * @param {string} separator
   */
  getUrl(reflection, relative, separator = '.') {
    let url = reflection.getAlias();
    // gatsby-source-filesystem doesn't like files beginning with underscore
    url = url.replace(/^_/, '');
    if (
      reflection.parent &&
      reflection.parent !== relative &&
      !(reflection.parent instanceof ProjectReflection)
    ) {
      url =
        this.getUrl(reflection.parent, relative, separator) + separator + url;
    }
    return url;
  }
};
```

The output files render properly using `gatsby-source-plugin` & `gatsby-plugin-mdx`.

The frontmatter might also want other fields, so I expect further additions would be there.

Might be worth publishing as a module?  Don't know.

**Comment by tgreyuk** [comment]
Thanks for documenting this.
