### ISSUE TITLE
bug: unquoted string in frontmatter (docusaurus)

### ISSUE THREAD

**Issue by boneskull** [tgreyuk/typedoc-plugin-markdown#80]
Per the [YAML specification](https://yaml.org/spec/1.0/#id2559720), a value beginning with `@` is considered an "indicator"--`@` is "reserved"--and must be quoted if we're to use it as a string.

This is a problem if a _module name_ happens to be scoped (e.g., in a monorepo):

```md
---
id: index
title: @scoped/package
sidebar_label: README
---
```

The result is a parsing error (may be implementation-dependent).  An example is `gatsby-plugin-mdx`, which attempts to parse YAML frontmatter:

```
end of the stream or a document separator is expected at line 3, column 8:
    title: @report-toolkit/transformers.redact
           ^/Users/boneskull/projects/boneskull/report-toolkit/packages/docs/src/pages/api/modules/_report_toolkit_transformers.redact.md: end of the stream or a document separator is expected at line 3, column 8:
    title: @report-toolkit/transformers.redact
           ^
```

A suggested fix would be to wrap the title in single or double-quotes.

**Comment by boneskull** [comment]
It looks like this was addressed insofar as the _project name_, but not the module name itself.

Module names beginning with `@` are generated by [typedoc-plugin-external-module-name](https://npm.im/typedoc-plugin-external-module-name)

**Comment by tgreyuk** [comment]
@boneskull thanks for comments / suggestions. would be happy to accept any PRs on this as I think you seem to have a better grip on this area. But also happy to look at myself in due course.

**Comment by boneskull** [comment]
np, working on it
