### ISSUE TITLE
bug? tests run on install

### ISSUE THREAD

**Issue by boneskull** [tgreyuk/typedoc-plugin-markdown#81]
This seems unneeded (IMO).  Cloning this repo and running `npm install` means the tests will run as well, which is not fast:

```
Test Suites: 28 passed, 28 total
Tests:       56 passed, 56 total
Snapshots:   31 passed, 31 total
Time:        33.636s
Ran all test suites.
```

If you want to avoid, you can use the `prepublishOnly` lifecycle script instead of `prepare`.

**Comment by tgreyuk** [comment]
@boneskull yeah thanks that's a good point...
