### ISSUE TITLE
Docusaurus themes generates filenames like 'index'.html (i.e. with the quotes)

### ISSUE THREAD

**Issue by Vinnl** [tgreyuk/typedoc-plugin-markdown#86]
For some reason, the files generated through the Docusaurus template have quotes wrapped around their name, before the extension. So e.g. `'index'.html` instead of `index.html`.

![image](https://user-images.githubusercontent.com/4251/63935927-d45b4a80-ca5e-11e9-802a-85a485ac04fb.png)

*Edit:* Just realised that those are generated by Docusaurus, of course. The problem is that the values in the front matter of the generated files have single quotes around them.

**Comment by tgreyuk** [comment]
closing as per your pr..
