### ISSUE TITLE
installing this package's 2.2.x prevents using another typedoc theme or even the default one

### ISSUE THREAD

**Issue by cancerberoSgx** [tgreyuk/typedoc-plugin-markdown#93]
From version 2.2, if I install this module, then typedoc will always output this plugin's theme even if I don't pass --plugin typedoc-plugin-markdown . This is an important issue since it's not possible to use the default output theme or other plugin's theme at all if installing version 2.2.x . Example:

```
npm i -D typedoc-plugin-markdown typedoc typescript
npx typedoc --out ./api --readme none --mode modules src/index.ts
```

Expected ./api to have the default typedoc's theme HTML output
But actually it has this plugin's markdown output

Didn't found any workaround than downgrading this package to version 2.1.9 where this issue doesn't happen

**Comment by cancerberoSgx** [comment]
I'm sorry, seems that typedoc now loads all plugins if --plugin is not passed so actually using --plugin none solves this problem.

**Comment by tgreyuk** [comment]
@cancerberoSgx I will put something on the readme to explain to use `--plugin none` to switch the plugin off - thanks..
